### ISSUE TITLE
Large number of failed jobs after upgrading to ActiveRecord4

### ISSUE THREAD

**Issue by deckchairhq** [mperham/sidekiq#1047]
I'm looking into a potential issue with ActiveRecord4 and Sidekiq.

Since upgrading to AR4, my failure rate shot through the roof - from under 100 failures in 2 weeks to 1000 failures in the first hour after upgrading.

The error presented is this:

```
ActiveRecord::ConnectionTimeoutError: could not obtain a database connection within 5.000 seconds (waited 5.001 seconds)
```

I have an ActiveRecord connection pool of 20. The first 20 jobs go through fine and I can see my connection pool growing, however when it hits 20, the errors start occurring.

It appears that either the connections aren't getting released or checked out appropriately.

If I replace the following line from the ActiveRecord Sidekiq middleware:

``` ruby
::ActiveRecord::Base.clear_active_connections! if defined?(::ActiveRecord)
```

...with a full disconnect:

``` ruby
::ActiveRecord::Base.clear_all_connections!
```

All works fine again - though obviously very inefficient.

I'm using a barebones ruby script for my worker that connects to ActiveRecord without rails:

``` ruby
      ::ActiveRecord::Base.establish_connection(
        :adapter  => configuration[:adapter],
        :host     => configuration[:host],
        :username => configuration[:username],
        :password => configuration[:password],
        :database => configuration[:database],
        :pool     => configuration[:pool],
        :port     => configuration[:port],
        :reaping_frequency => 10
      )

      self[:activerecord_cache] = ::ActiveSupport::Cache::MemoryStore.new
```

It's all very simple and the queue was running fine until now.

I'll plug away at this a bit more and if no luck, will get a skeleton repo up to reproduce it. Any input is appreciated.

**Comment by Silex** [comment]
I'm a bit confused about wether we should call `ActiveRecord::Base.connection_pool.with_connection` in our workers or not, if we do not create threads in them (just use the ActiveRecord models).

**Comment by mperham** [comment]
You do not need to do anything special.

**Comment by Silex** [comment]
@mperham: thanks! What happens if we have more concurrent workers than available database pool size tho?

My current pool size is 100, I run rails 5. At the moment I never have more than 80 concurrent jobs _and_ my workers all use `ActiveRecord::Base.connection_pool.with_connection` because I thought it was better practice.

I'm in the middle of a refactor where my goal is to remove the need for a DB connection for most of my jobs, so they have all the information they need to perform. Then another job's goal si to collect the result and do the necessary DB operations. That should remove the need for a high database pool. I'll also remove the wrapping with `ActiveRecord::Base.connection_pool.with_connection` based on your advice.

**Comment by Silex** [comment]
(I just realised that editing answers on github does not work well with email workflows because you only receive the first text that was submitted. I thus resubmit the whole text and delete my previous reply)

---

@mperham: thanks! What happens if we have more concurrent workers than available database pool size tho?

My current pool size is 100, I run rails 5. At the moment I never have more than 80 concurrent jobs and my workers all use ActiveRecord::Base.connection_pool.with_connection because I thought it was better practice and avoided "max DB connexion reached" issues.

I'm in the middle of a refactor where my goal is to remove the need for a DB connection for most of my jobs, so they have all the information they need to perform. Then another job's goal will be to collect the results and do the necessary DB operations... That was it should remove the need for a high database pool. I'll also remove the wrapping with ActiveRecord::Base.connection_pool.with_connection based on your advice.

**Comment by mperham** [comment]
ActiveRecord keeps a pool of connections to the database, **per-process**.  You should not run more than a concurrency of 50 in Sidekiq and I recommend setting the pool size == concurrency.  The pool is lazy so AR will open up to 50 connections if you have a lot of jobs processing at the same time in the process.

In Sidekiq <5, Sidekiq's ActiveRecord middleware cleans up the job's db connection after execution.
In Sidekiq 5+, the ActiveSupport::Executor will clean up the job's db connection after execution.  In either case, you don't need to do anything special in your code unless you are trying to do something special, like minimize connection checkout time.

**Comment by Silex** [comment]
@mperham: ah, great thanks a lot for the clarifications!

In my case I use Sidekiq 5+ for jobs where I download images from ~130 IP cameras at regular intervals (each 10 minutes), so I kinda need the high concurrency. Maybe this needs to be designed differently...

**Comment by mperham** [comment]
Why can't you run more processes?

**Comment by Silex** [comment]
@mperham: ah multiple sidekiq processes? yes I can do that, that way I can limit each Sidekiq process to a concurrency of 50 or less like you recommand and also the database connection pool becomes less of an issue. I just didn't think of it.

Thanks again! 

p.s: for everyone wondering "why 50", the explanation is in https://github.com/mperham/sidekiq/wiki/Advanced-Options
