### ISSUE TITLE
Stack level too deep: Celluloid::FiberStackError

### ISSUE THREAD

**Issue by joshsmith** [mperham/sidekiq#1129]
I'm getting a `Celluloid::FiberStackError` while on Ruby 2.0.0p247. I got directed to the Celluloid wiki but it obviously won't solve my problem.

I'm pointed to `sidekiq/processor:112`, as well.

Any thoughts?

**Comment by hayesgm** [comment]
FYI, I had a similar error using rails' `sanitize()` function with a large block of HTML.  This was due to sidekiq's `Fiber` running out of stack space, and fixed by setting the environment variable `RUBY_FIBER_VM_STACK_SIZE=524288`.  When facing this issue, you might want to try running your job's code in a Fiber, e.g.:

```ruby
Fiber.new do
   # your job code causing this error
end.resume
```

This might easily reproduce the issue.
