### ISSUE TITLE
[PRO] rubygem dead

### ISSUE THREAD

**Issue by fabien7337** [mperham/sidekiq#1220]
Can't bundle anymore:

Fetching source index from http://www.mikeperham.com/rubygems/
Could not fetch specs from http://www.mikeperham.com/rubygems/
((chain-or (bundle check "--path=vendor/bundle") (bundle install "--path=vendor/bundle " --clean))) returned exit code 17action bundle install failed

**Comment by nickmerwin** [comment]
> $ bundle
Fetching source index from http://www.mikeperham.com/rubygems/
Retrying source fetch due to error (2/3): Bundler::HTTPError Could not fetch specs from http://www.mikeperham.com/rubygems/
Retrying source fetch due to error (3/3): Bundler::HTTPError Could not fetch specs from http://www.mikeperham.com/rubygems/
Could not fetch specs from http://www.mikeperham.com/rubygems/

Just received this. Is there a known issue with your gem server @mperham ?

**Comment by ryansch** [comment]
That's the old server.  You should be using gems.contribsys.com now.

**Comment by nickmerwin** [comment]
Thanks @ryansch, worked.
