### ISSUE TITLE
Sidekiq.dump_json must not fail

### ISSUE THREAD

**Issue by avit** [mperham/sidekiq#1705]
We had an encoding exception (originally caused in another part of the system) which triggered a retry, but the error reporting within Sidekiq caused RetryJobs to fail and drop the job.

Here is a trace: 

```
Encoding::UndefinedConversionError: "\xC3" from ASCII-8BIT to UTF-8

/gems/json-1.8.1/lib/json/common.rb:223 in "encode"
/gems/json-1.8.1/lib/json/common.rb:223 in "generate"
/gems/json-1.8.1/lib/json/common.rb:223 in "generate"
/gems/sidekiq-2.17.3/lib/sidekiq.rb:105 in "dump_json"
/gems/sidekiq-2.17.3/lib/sidekiq/middleware/server/retry_jobs.rb:97 in "rescue in call"
/gems/sidekiq-2.17.3/lib/sidekiq/middleware/server/retry_jobs.rb:62 in "call"
/gems/sidekiq-2.17.3/lib/sidekiq/middleware/chain.rb:124 in "block in invoke"
```

I think there should be a rescue clause within `dump_json` for any bad input that trickles into the error handling code.

**Comment by mingca** [comment]
Getting this error message again in v5.0.5 sidekiq pro.

```        }, 
        {
          "method": "dump_json", 
          "lineno": 175, 
          "filename": "/usr/local/rvm/gems/ruby-2.4.4@railsapp-production/gems/sidekiq-5.0.5/lib/sidekiq.rb"
        }, 
        {
          "method": "generate", 
          "lineno": 224, 
          "filename": "/usr/local/rvm/gems/ruby-2.4.4@railsapp-production/gems/json-2.1.0/lib/json/common.rb"
        }, 
        {
          "method": "generate", 
          "lineno": 224, 
          "filename": "/usr/local/rvm/gems/ruby-2.4.4@railsapp-production/gems/json-2.1.0/lib/json/common.rb"
        }, 
        {
          "method": "encode", 
          "lineno": 224, 
          "filename": "/usr/local/rvm/gems/ruby-2.4.4@railsapp-production/gems/json-2.1.0/lib/json/common.rb"
        }
      ], 
      "exception": {
        "message": "\"\\xE2\" from ASCII-8BIT to UTF-8", 
        "class": "Encoding::UndefinedConversionError"
      }, ```

**Comment by pelargir** [comment]
I was having a similar problem and traced it back to reading an incoming Stripe webhook request containing a UTF-8 character. I was calling `request.body.read` instead of `request.raw_post` (on an `ActiveDispatch::Request` object). The former assumes ASCII-8BIT (binary) encoding which was causing `JSON.generate` to blow up when trying to serialize the body. The latter correctly uses UTF-8 encoding so the body can be serialized without blowing up. Hope this helps someone. See https://apidock.com/rails/ActionDispatch/Request/raw_post
