### ISSUE TITLE
Configure a worker for all queues?

### ISSUE THREAD

**Issue by softwaregravy** [mperham/sidekiq#1709]
I'm trying to create a worker that can pull off of all queues. Can't really figure it out. 

In our app, we have many custom named queues. I'd like to have a worker that can pull a job off of any of them. I can just list them all on the command-line, but that's error prone as we add more queues. 

Suggestions?

**Comment by fabn** [comment]
@mperham Sorry to bother you with an already closed issue. 

I think this should be implemented even if you think it's a smell. There are a number of custom queues created by third party code there are out of user control. I was recently bitten by a typo in `config/sidekiq.yml`, I wrote `mailer` instead of `mailers` and all my messages remained in queue because of this.

There are lot of gems ([ActionMailer](https://github.com/rails/rails/blob/10d0c43c7937f65b2fc6fb87a87b1023bbd85674/actionmailer/lib/action_mailer/delivery_methods.rb#L20), [rollbar](https://github.com/rollbar/rollbar-gem#using-sidekiq), [searchkick](https://github.com/ankane/searchkick#stay-synced), [carrierwave_backgrounder](https://github.com/lardawge/carrierwave_backgrounder#installation-and-usage) to list some of them) that in their default configuration use named queues and if one doesn't list them (or make some errors) in sidekiq config their jobs won't be processed.

**Comment by deneuxa** [comment]
I could be really great, even for development purposes.
Would be way much simpler to define a worker with -q all for example :)

**Comment by roberto-vasquez-enermarket** [comment]
This is biting me right now. I too think there should be an "all" option.
