### ISSUE TITLE
Pluggable interchange format

### ISSUE THREAD

**Issue by nirvdrum** [mperham/sidekiq#197]
Similar to what was proposed in #185, it'd be great if the message interchange format were pluggable.  I understand the rationale for having a resque-compatible JSON format, but I found it unsuitable when using resque and would like to move away from it with sidekiq.  E.g., it's more efficient to just pass around serialized objects than to keep hammering the DB to fetch data by a passed ID.  Likewise, I'd like to gzip payloads so I don't have to worry as much about redis filling up.

I was hoping to do this with middleware, but it appears there's no way to actually modify the message.  But even that would be a bit hacky.  A pluggable interface for message generation and loading would be ideal.

**Comment by nijikon** [comment]
@mperham Is this still a no?

**Comment by mperham** [comment]
Still a no.

**Comment by mensfeld** [comment]
:(

**Comment by jonhyman** [comment]
Fwiw there are a few places where we do this. We have a custom job parameter encoding class that can encode and decode objects (using a combination of marshaling, gzipping and base64 encoding). It has been very beneficial for a few different places. We do it on a case by case basis. I'll tell you that when we upgraded from Rails 3 to Rails 4 it was a challenge because one object had contained an active support timezone in an instance variable, which changed representations between 3 and 4 and we had to write custom logic to handle that for in flight or scheduled jobs that were marshalled in Rails 3. So you need to take care for this. I'm supportive of @mperham not including this option. Imo you should know what you're doing and be aware of the consequences if you pass around encoded objects.
