### ISSUE TITLE
Feature request: limit number of workers per queue

### ISSUE THREAD

**Issue by golive** [mperham/sidekiq#200]
Hi!

Do you think it's possible add a parameter to limit the number of workers for a given queue?
This would be useful if we have a queue that we don't want to consume too many workers, and, in the case I want, to create a sequencial queue (1 worker).

Thanks!

**Comment by alflennik** [comment]
This would be simple to add (some people in this thread have implemented it themselves), and extremely useful for any sufficiently complicated project. Deciding not to include this is a mistake.

**Comment by brandoncc** [comment]
I agree with @alflennik, but I'm probably partial since I need the feature and am not a Sidekiq pro user so I can't use https://github.com/brainopia/sidekiq-limit_fetch.

**Comment by brandoncc** [comment]
Oh, I totally skipped the first sentence in the Requirements section. I only saw "Requirements" and "sidekiq pro" *kicks himself*

**Comment by stonefield** [comment]
+1 Definition of queue within *computing*: a list of data items, commands, etc., stored so as to be retrievable in a definite order, usually the order of insertion.
Ref: https://www.google.com/search?client=firefox-b-d&q=definition+of+queue

**Comment by Adamantish** [comment]
I'd be interested to hear the reasoning why this is unsuitable to be included in core. Genuinely interested because as far as I can see @mperham is pretty damn skilled and there's perhaps something to learn.

I appreciate that sidekiq has succeeded partly due to its great respect for SRP. Still, the fact that I can choose to limit all of sidekiq to one thread seems similar (from a user's view) to the proposed option to limit a queue to 1 thread.

**Comment by scottrobertson** [comment]
I would love this to be a core feature. Using limit_fetch is not an option, as it's unmaintained, and does not seem to work well with all the latest features of Sidekiq Pro/Ent such as super_fetch.

**Comment by mperham** [comment]
Because Sidekiq talks directly to Redis, throttling is difficult to implement in a scalable manner. You must use Lua and, with Redis being single threaded, you'll burn a lot of that single core when throttling.  Additionally limit_fetch does not work with the reliability feature so you can lose jobs.

Faktory uses a different architecture where it is a single point of access for jobs; it can implement throttling in a safe and efficient manner. Faktory Enterprise will provide a throttling feature and is due for release this month (Jan 2020).

https://github.com/contribsys/faktory/wiki/Ent-Throttling

**Comment by leoplct** [comment]
Anyone found a solution on this?
How to set concurrency to 1 only for one specific queue? I'd max 1 job for a particular queue.

**Comment by scottrobertson** [comment]
> Anyone found a solution on this?
> 
> How to set concurrency to 1 only for one specific queue? I'd max 1 job for a particular queue.

Just limit a process to listen to one queue and set a concurrency of one.

**Comment by leoplct** [comment]
Thank you. I've solved with this Procfile

```
web: bundle exec puma -C config/puma.rb 
worker: bundle exec sidekiq --config config/sidekiq.yml
slow_worker: bundle exec sidekiq -q low -c 1
```

**Comment by yboulkaid** [comment]
Sidekiq 7 introduces [capsules](https://github.com/mperham/sidekiq/blob/7-0/docs/7.0-Upgrade.md#capsules), which could be a suitable solution for this if you don't mind dedicating one thread to the throttled queue

**Comment by kreintjes** [comment]
@yboulkaid would Capsules also work for this when having multiple Heroku workers each running a separate Sidekiq instance with concurrency 1? Since limiting through capsules seems to be focussed on threads within one Sidekiq instance, while with sidekiq-limit_fetch you can set a maximum amount of workers per queue.

We would want a few (say 3) Heroku workers running jobs from the heavy queue, while all the remaining Heroku workers run jobs from all the other queues. We would also like to combine this with auto scaling, where we scale up the number of workers when the (total) amount of jobs in the queue(s) increase. How can we achieve this with capsules or would we still need the sidekiq-limit_fetch gem?

**Comment by ddhatchinamoorthi-rpx** [comment]
Anyone found a solution on this? How to set concurrency to 1 only for one specific queue? I'd max 1 job for a particular queue.

-Ans: Using the gem 'sidekiq-limit_fetch', I was able to fix the issue, setting a limit for each queue in config/sidkiq.yml.

#config/sidkiq.yml.
development:
  :concurrency: 2
test:
   :concurrency: 2
production:
  :concurrency: 2
:queues:
  - default
  - my_queue
:limits:
  default: 1
  my_queue: 1
