### ISSUE TITLE
How do you go about rescheduling jobs?

### ISSUE THREAD

**Issue by ewamarciniak** [mperham/sidekiq#2145]
Hi, I have read a few posts here about the rescheduling feature and I think that method is now part of the SortedEntry class but although I can grab what I think is the jid when the job is scheduled first, I am not sure how to proceed with rescheduling this job, what to pass in the arguments. Can you please post an example how this should be done? thanks

**Comment by ryansch** [comment]
We schedule the job as new while marking the existing one as canceled using a variation of https://github.com/mperham/sidekiq/wiki/FAQ#how-do-i-cancel-a-sidekiq-job.

**Comment by ewamarciniak** [comment]
I managed to put together this code before you answered:
```
          scheduler = Sidekiq::ScheduledSet.new
          job = scheduler.select {|s| s.klass == 'MessagesWorker' && s.jid == @message.jid }.first

          entry = Sidekiq::SortedEntry.new(job.parent, job.score, job.item)
          entry.reschedule(params[:message][:deliver_at]) if !@message.sent_at
```
It works but just wondering why would you cancel instead of reschedule?

**Comment by ryansch** [comment]
The motivation came from this issue: https://github.com/mperham/sidekiq/issues/1886

Our problem is that we'd have to search our quite large set of scheduled jobs and then additionally delete some and we do this often.  You might want to wait for @mperham for some guidance on which parts of this algorithm are inefficient.

**Comment by ewamarciniak** [comment]
The problem is that in order to cancel a job I also must find it first or can this be done another way?

**Comment by aprescott** [comment]
I'm confused why this isn't simply a case of calling `FooJob` with the same arguments and a different scheduled time, letting the current job simply return without performing any other work. Is there a reason that doesn't work here?

**Comment by aprescott** [comment]
Oh I think I assumed this was within a `perform` call. That's probably why :)

**Comment by ewamarciniak** [comment]
No, sorry I didn't mention that- I was scheduling for specific time in the future and using perform_in of course :)

**Comment by ryansch** [comment]
The approach we use to 'cancel' a job is actually to turn it into a no-op with some of our existing domain models.  We don't actually leverage redis in that way.

My bigger question is: Are we providing a method `reschedule` that is considered harmful?  What are the use cases when it should be used?  Is this one of them?

**Comment by ryansch** [comment]
@ewamarciniak That's the upside to turning the existing jobs into no-ops.  You don't have to store `jid`s and look them up to cancel/reschedule stuff.

**Comment by mperham** [comment]
Ewa, the Sidekiq data structures in Redis are indexed for certain types of
lookups.  Looking up an entry in a sorted set by JID is not one of those
fast lookups.  As Ryan said, if your set is really large, this will impact
Redis performance.  Your code will work fine with 100 entries.  It will
work terribly with 100,000 entries.  That's why I publicly recommend
everyone use the other method that Ryan mentioned: it scales much better.

Note that Sidekiq Pro does have some API extensions that perform much
better and would be usable (using Redis 2.8's ZSCAN support) if you had to
use the API.  The *SCAN commands are amazing.

Mike

**Comment by jonhyman** [comment]
We have millions of jobs in our `ScheduledSet` at any given time, and what @mperham is saying about looking up the job by JID rings very true to us. We used to search the set and even zscan it to find jobs when we needed to cancel them, but it was too inefficient.

We have a small set of jobs which are user-cancelable or reschedulable, maybe a few thousand of the millions. The way in which we handle that is by breaking the abstraction barrier somewhat. When we schedule those jobs at a given UNIX timestamp (e.g., 1421947789), we also generate six digits of random jitter to be used as microseconds, so it would actually get enqueued at something like 1421947789.489211. We then store the timestamp, the jitter as an integer (databases can be hard at getting the precision right), and the jid.

With those three pieces of information, we can use `ScheduledSet.new.fetch(score, jid)` which is `O(log(M)+N)`. `N` should by and large always be 1 because of the microsecond precision, and `O(log(M))` is not the fastest, but it's fine even at millions of elements. This way, we can access the job ourselves to delete it.

The solution proposed by @ryansch that's on the wiki also sounds pretty good, just add some middleware or pre-perform check for jobs that are canceled and return early.

**Comment by ryansch** [comment]
Our use case is for orders that users can schedule in the future.  They can reschedule them at any point for any other point.  We have a solution that allows the order worker to be scheduled n times while only running once (we had to use some locking).
