### ISSUE TITLE
How can you enable the ability to see Failed jobs like you can inspect the "Dead" queue?

### ISSUE THREAD

**Issue by bobber205** [mperham/sidekiq#2163]
Why is this not clickable?

![sidekiq 2015-01-28 09-55-35](https://cloud.githubusercontent.com/assets/5841107/5943396/6ceca44c-a6d3-11e4-80d2-7b468b54e16c.png)

Other than process, it's literally the only link on the top bar that isn't clickable. Sometimes I want to see what jobs have failed without having to wait for them to appear in the dead queue or having them programmatically going there right away.

**Comment by mperham** [comment]
Failed jobs are "retries" in Sidekiq.  Don't disable retries.

**Comment by bobber205** [comment]
We're currently only specifying retries = 0. Does this prevent it from going straight to the dead queue?

**Comment by mperham** [comment]
Jobs with retry = 0 should go to the dead queue immediately if they fail.

**Comment by userrails** [comment]
@mperham The behavior is correct, but still we should be able to know what was the reason for failure so that we can fix it and retry that worker right?

**Comment by mistaguy** [comment]
@mperham the issue is that when `sidekiq_options retry:false`, there is no way of knowing why some jobs failed. In my case i have over 80K jobs running in a hour at times. And so if a job fails it would be nice to come back and see the reasons as to why some specific job out of the 80K that failed. If this cant be added, alternative i will built some other notification mechanism anyways

**Comment by mperham** [comment]
The Error Handling wiki page discusses best practices and trade offs. I don’t have anything further to add unless you have specific questions.

**Comment by azmatrana** [comment]
We just want an option to see the processed and failed jobs as well. Just like dead, retries, enqueued, busy.

**Comment by mperham** [comment]
@azmatrana isn't that the purpose of logs?

**Comment by josh-m-sharpe** [comment]
<img width="1188" alt="Stocks" src="https://user-images.githubusercontent.com/39473/177076159-b47911fc-b6c5-4506-aeac-e1c937e6b998.png">

I ran a bunch of jobs producing 259 retries and they all eventually succeeded, but sidekiq can't tell me why they failed the first time.

`isn't that the purpose of logs`
Why do I need to go add custom logging for this scenario, but not the "failed 25 times and ended up in the dead queue" scenario?

**Comment by mperham** [comment]
Sidekiq automatically collects error info with each retry and will show it
in the Web UI unless you disable it. Did you disable backtraces?

**Comment by josh-m-sharpe** [comment]
I have not disabled backtraces.  I'm not sure where these "failed" backtraces would be.  I suppose I'd expect `Failed` to be clickable and see them there.

**Comment by mperham** [comment]
Click the Retries tab and then any entry in the list.

**Comment by Halphas** [comment]
@mperham I think you did not quite understand the question entirely. It's regarding the failing jobs.

**Comment by georgeu2000** [comment]
@mperham - Thank you for providing such an awesome gem.

I too have this issue. I don't want to retry jobs because they should not fail. If they fail, then I want to fix the issue, not retry.

> Jobs with retry = 0 should die and go to the morgue immediately if they fail.

Does this mean Dead jobs section? I don't have any dead jobs, so maybe this is a bug?

![image](https://github.com/user-attachments/assets/42bd5d0e-e069-4fe2-8c38-284d97be5e22)

I think you should be able to click on **Failed** to see the failed jobs, both for this particular use case and from a UX perspective. 

It would be nice to see the processed jobs as well.

**Comment by mperham** [comment]
The morgue is the Dead tab, yes.

The Failed counter counts failed job executions, but some jobs are still retrying. Permanently failed jobs can be found in the Dead tab. Please re-read the Error Handling wiki page for exact details.

**Comment by nik-holo** [comment]
For those who are here confused still after thread here is simple answer:

> The “Failed” counter in the Sidekiq dashboard simply reflects the number of times jobs raised an exception during execution — not how many jobs are currently in the Retry or Dead queues.
>
> It's a running total of how many jobs have failed at least once, whether or not they were retried, succeeded later, or discarded.

That means if you have 0 in `retries` and 0 in `dead` - you're good, all jobs succeeded. If you want to know what happened - you check your honeybadger or sentry. 

What most people find frustrating (me included) and i believe deserves a second look is initial issue - retires are clickable and already show error reason - why not use same view and same data in retries just without retry option? Almost no additional work and such a time saver. 

Or is trace and error data flushed after successfull retry? @mperham

**Comment by mperham** [comment]
Trace and error data is stored in the job itself. If the job fails and you configure it not to retry, Sidekiq discards it completely. There's nothing to see because it is gone.

**Comment by alexrudall** [comment]
> [@mperham](https://github.com/mperham) the issue is that when `sidekiq_options retry:false`, there is no way of knowing why some jobs failed. In my case i have over 80K jobs running in a hour at times. And so if a job fails it would be nice to come back and see the reasons as to why some specific job out of the 80K that failed. If this cant be added, alternative i will built some other notification mechanism anyways

I believe the root cause of the confusion here is that people are setting retry config to `false` when they should be setting it to `0`! 

See "Altering the lifecycle" from the [docs](https://github.com/sidekiq/sidekiq/wiki/Job-Lifecycle#altering-the-lifecycle):

```
class SomeJob
  # will be completely ephemeral, not in Retry or Dead
  sidekiq_options retry: false
  # will go immediately to the Dead tab upon first failure
  sidekiq_options retry: 0
```

**You probably want `0`, not `false`.**
