### ISSUE TITLE
Repeating job was terminated

### ISSUE THREAD

**Issue by russellquinn** [mperham/sidekiq#2176]
I have a job that repeats every minute. It does its work, then reschedules itself to run again in a minute's time.

It's been running for long time without problem, but yesterday it didn't reschedule itself or got deleted. I can't find anything in the logs to suggest why. 

Does anyone have an idea for a safer way to ensure a job repeats?

**Comment by mperham** [comment]
Use whenever + cron:

https://github.com/mperham/sidekiq/wiki/Scheduled-Jobs#recurring-jobs

**Comment by davydovanton** [comment]
i think that you can use [sidetiq](https://github.com/tobiassvn/sidetiq) *(this gem based on `whenever`)* for this, for me it's better solution than `whenever` + `cron` because you can see in web dashbord all schedulers and call any. And if you might be interested this i can send some dashbord screenshots :eyes:

**Comment by russellquinn** [comment]
Ah, great. Thanks everyone!
