### ISSUE TITLE
Memory keep growing even no running jobs

### ISSUE THREAD

**Issue by samnang** [mperham/sidekiq#2177]
When I look at my memory log, I notice the memory is growing for sidekiq workers. Then I setup a blank projec[0]t. Then I just run `bundle exec sidekiq` to start the workers. After that I watch memory growing even I don't run the rails app to push some jobs into the queue. By watching the memory grow, I use both commands:

```
$ top -pid [pid]

$ watch 'ps u|grep sidekiq'
```

[0] https://github.com/samnang/sidekiq_memory

**Comment by mperham** [comment]
You're going to have to show a lot more data before I believe you.  People report memory leaks all the time.

**Comment by alexfalkowski** [comment]
I am seeing the same thing. I had to restart the process twice now. What data would you like?

**Comment by mperham** [comment]
What version of Ruby?

**Comment by alexfalkowski** [comment]
I am using MRI 2.2.0

**Comment by alexfalkowski** [comment]
Seems to also be happening in 2.2.1 as well (need more analysis)

**Comment by crispincornett** [comment]
I am also seeing this on MRI 2.2.0 and 2.2.1.  Memory usage increasing steadily even with no running jobs.  What can I provide to help track this down?

**Comment by mperham** [comment]
Provide a simple app which repro's the problem.

**Comment by alexfalkowski** [comment]
@samnang provided https://github.com/samnang/sidekiq_memory does this not suffice?

**Comment by mperham** [comment]
Ah, for some reason I thought that was a sidekiq extension he was using to monitor memory, not the repro case.  Thanks.

**Comment by mperham** [comment]
If I start up sidekiq as a bare ruby process (`bundle exec sidekiq -r ./empty.rb`), it starts at 28104KB of memory.  Eight minutes later, it's at 30140KB but I can also see the number drop occasionally too.  I don't know if this is simply the VM warming up or if there's a real bug.

**Comment by mperham** [comment]
After an hour or two, I don't see any significant increase in RAM usage.  If you can show me an empty app whose memory usage continues to grow over 24 hours, I'd be happy to investigate further.

**Comment by alexfalkowski** [comment]
Yep its is hard to reproduce memory problems. Since I have restarted it the process is already using 2.5 GB of memory:

When I do pmap -x PID

PID:   sidekiq 3.3.2 mortice [0 of 20 busy]
Address           Kbytes     RSS   Dirty Mode   Mapping
0000000000400000       4       4       0 r-x--  ruby
0000000000600000       4       4       4 rw---  ruby
0000000001283000   19052   19012   19012 rw---    [ anon ]
000000000251e000  207556  165972  165972 rw---    [ anon ]
00000033a3600000       4       4       0 r-x--  libaio.so.1.0.1
00000033a3601000    2044       0       0 -----  libaio.so.1.0.1
00000033a3800000       4       4       4 rw---  libaio.so.1.0.1
00000036b0a00000     128     100       0 r-x--  ld-2.12.so
00000036b0c1f000       4       4       4 r----  ld-2.12.so
00000036b0c20000       4       4       4 rw---  ld-2.12.so
00000036b0c21000       4       4       4 rw---    [ anon ]
00000036b0e00000    1580     668       0 r-x--  libc-2.12.so
00000036b0f8b000    2044       0       0 -----  libc-2.12.so
00000036b118a000      16      16       8 r----  libc-2.12.so
00000036b118e000       4       4       4 rw---  libc-2.12.so
00000036b118f000      20      20      20 rw---    [ anon ]
00000036b1200000       8       8       0 r-x--  libdl-2.12.so
00000036b1202000    2048       0       0 -----  libdl-2.12.so
00000036b1402000       4       4       4 r----  libdl-2.12.so
00000036b1403000       4       4       4 rw---  libdl-2.12.so
00000036b1600000      92      72       0 r-x--  libpthread-2.12.so
00000036b1617000    2048       0       0 -----  libpthread-2.12.so
00000036b1817000       4       4       4 r----  libpthread-2.12.so
00000036b1818000       4       4       4 rw---  libpthread-2.12.so
00000036b1819000      16       4       4 rw---    [ anon ]
00000036b1a00000      28      12       0 r-x--  librt-2.12.so
00000036b1a07000    2044       0       0 -----  librt-2.12.so
00000036b1c06000       4       4       4 r----  librt-2.12.so
00000036b1c07000       4       4       4 rw---  librt-2.12.so
00000036b1e00000     524      72       0 r-x--  libm-2.12.so
00000036b1e83000    2044       0       0 -----  libm-2.12.so
00000036b2082000       4       4       4 r----  libm-2.12.so
00000036b2083000       4       4       4 rw---  libm-2.12.so
00000036b2200000      84      40       0 r-x--  libz.so.1.2.3
00000036b2215000    2044       0       0 -----  libz.so.1.2.3
00000036b2414000       4       4       4 r----  libz.so.1.2.3
00000036b2415000       4       4       4 rw---  libz.so.1.2.3
00000036b2600000     116       8       0 r-x--  libselinux.so.1
00000036b261d000    2044       0       0 -----  libselinux.so.1
00000036b281c000       4       4       4 r----  libselinux.so.1
00000036b281d000       4       4       4 rw---  libselinux.so.1
00000036b281e000       4       4       4 rw---    [ anon ]
00000036b2a00000      32      28       0 r-x--  libnuma.so.1
00000036b2a08000    2048       0       0 -----  libnuma.so.1
00000036b2c08000       4       4       4 rw---  libnuma.so.1
00000036b2e00000      88      52       0 r-x--  libresolv-2.12.so
00000036b2e16000    2048       0       0 -----  libresolv-2.12.so
00000036b3016000       4       4       4 r----  libresolv-2.12.so
00000036b3017000       4       4       4 rw---  libresolv-2.12.so
00000036b3018000       8       4       4 rw---    [ anon ]
00000036b3200000     116      24       0 r-x--  libtinfo.so.5.7
00000036b321d000    2048       0       0 -----  libtinfo.so.5.7
00000036b341d000      16      12       4 rw---  libtinfo.so.5.7
00000036b3600000     452       4       0 r-x--  libfreebl3.so
00000036b3671000    2044       0       0 -----  libfreebl3.so
00000036b3870000       8       8       4 r----  libfreebl3.so
00000036b3872000       4       4       4 rw---  libfreebl3.so
00000036b3873000      16       0       0 rw---    [ anon ]
00000036b3a00000      28       4       0 r-x--  libcrypt-2.12.so
00000036b3a07000    2048       0       0 -----  libcrypt-2.12.so
00000036b3c07000       4       4       4 r----  libcrypt-2.12.so
00000036b3c08000       4       4       4 rw---  libcrypt-2.12.so
00000036b3c09000     184       0       0 rw---    [ anon ]
00000036b3e00000      88      24       0 r-x--  libnsl-2.12.so
00000036b3e16000    2044       0       0 -----  libnsl-2.12.so
00000036b4015000       4       4       4 r----  libnsl-2.12.so
00000036b4016000       4       4       4 rw---  libnsl-2.12.so
00000036b4017000       8       0       0 rw---    [ anon ]
00000036b4200000      88      16       0 r-x--  libgcc_s-4.4.7-20120601.so.1
00000036b4216000    2044       0       0 -----  libgcc_s-4.4.7-20120601.so.1
00000036b4415000       4       4       4 rw---  libgcc_s-4.4.7-20120601.so.1
00000036b5600000      12       4       0 r-x--  libcom_err.so.2.1
00000036b5603000    2044       0       0 -----  libcom_err.so.2.1
00000036b5802000       4       4       4 r----  libcom_err.so.2.1
00000036b5803000       4       4       4 rw---  libcom_err.so.2.1
00000036b6a00000       8       4       0 r-x--  libkeyutils.so.1.3
00000036b6a02000    2044       0       0 -----  libkeyutils.so.1.3
00000036b6c01000       4       4       4 r----  libkeyutils.so.1.3
00000036b6c02000       4       4       4 rw---  libkeyutils.so.1.3
00000036b6e00000    1748     788       0 r-x--  libcrypto.so.1.0.1e
00000036b6fb5000    2048       0       0 -----  libcrypto.so.1.0.1e
00000036b71b5000     108      92       4 r----  libcrypto.so.1.0.1e
00000036b71d0000      48      48      12 rw---  libcrypto.so.1.0.1e
00000036b71dc000      16      16      16 rw---    [ anon ]
00000036b7200000      40       8       0 r-x--  libkrb5support.so.0.1
00000036b720a000    2044       0       0 -----  libkrb5support.so.0.1
00000036b7409000       4       4       4 r----  libkrb5support.so.0.1
00000036b740a000       4       4       4 rw---  libkrb5support.so.0.1
00000036b7600000     876      44       0 r-x--  libkrb5.so.3.3
00000036b76db000    2044       0       0 -----  libkrb5.so.3.3
00000036b78da000      40       8       4 r----  libkrb5.so.3.3
00000036b78e4000       8       8       8 rw---  libkrb5.so.3.3
00000036b7a00000     164       8       0 r-x--  libk5crypto.so.3.1
00000036b7a29000    2048       0       0 -----  libk5crypto.so.3.1
00000036b7c29000       4       4       4 r----  libk5crypto.so.3.1
00000036b7c2a000       4       4       4 rw---  libk5crypto.so.3.1
00000036b7c2b000       4       0       0 rw---    [ anon ]
00000036b8e00000     260      20       0 r-x--  libgssapi_krb5.so.2.2
00000036b8e41000    2048       0       0 -----  libgssapi_krb5.so.2.2
00000036b9041000       4       4       4 r----  libgssapi_krb5.so.2.2
00000036b9042000       8       8       8 rw---  libgssapi_krb5.so.2.2
00000036bae00000     388     224       0 r-x--  libssl.so.1.0.1e
00000036bae61000    2048       0       0 -----  libssl.so.1.0.1e
00000036bb061000      16      16       4 r----  libssl.so.1.0.1e
00000036bb065000      28      28      12 rw---  libssl.so.1.0.1e
00007f1428000000   21392     848     848 rw---    [ anon ]
00007f14294e4000   44144       0       0 -----    [ anon ]
00007f1430000000   50812   49792   49792 rw---    [ anon ]
00007f143319f000   14724       0       0 -----    [ anon ]
00007f1434000000   12512   12124   12124 rw---    [ anon ]
00007f1434c38000   53024       0       0 -----    [ anon ]
00007f1438000000   32200   22128   22128 rw---    [ anon ]
00007f1439f72000   33336       0       0 -----    [ anon ]
00007f1440000000   53180   48636   48636 rw---    [ anon ]
00007f14433ef000   12356       0       0 -----    [ anon ]
00007f1448000000   64632   64176   64176 rw---    [ anon ]
00007f144bf1e000     904       0       0 -----    [ anon ]
00007f1450000000   53640   51028   51028 rw---    [ anon ]
00007f1453462000   11896       0       0 -----    [ anon ]
00007f1454000000   58816   58588   58588 rw---    [ anon ]
00007f1457970000    6720       0       0 -----    [ anon ]
00007f1458000000   65496   62588   62588 rw---    [ anon ]
00007f145bff6000      40       0       0 -----    [ anon ]
00007f145c000000   45376   44924   44924 rw---    [ anon ]
00007f145ec50000   20160       0       0 -----    [ anon ]
00007f1460000000   45404   45180   45180 rw---    [ anon ]
00007f1462c57000   20132       0       0 -----    [ anon ]
00007f1464000000   64744   64216   64216 rw---    [ anon ]
00007f1467f3a000     792       0       0 -----    [ anon ]
00007f1469f62000       4       0       0 -----    [ anon ]
00007f1469f63000    1024      12      12 rwx--    [ anon ]
00007f146a063000       4       0       0 -----    [ anon ]
00007f146a064000     508      44      44 rw---    [ anon ]
00007f146a263000       4       0       0 -----    [ anon ]
00007f146a264000     508     120     120 rw---    [ anon ]
00007f146a3e3000       4       0       0 -----    [ anon ]
00007f146a3e4000     508      12      12 rw---    [ anon ]
00007f146a463000       4       0       0 -----    [ anon ]
00007f146a464000     508     104     104 rw---    [ anon ]
00007f146a5e3000       4       0       0 -----    [ anon ]
00007f146a5e4000     508     104     104 rw---    [ anon ]
00007f146a6e3000       4       0       0 -----    [ anon ]
00007f146a6e4000     508     120     120 rw---    [ anon ]
00007f146a7e2000       4       0       0 -----    [ anon ]
00007f146a7e3000    1024      12      12 rwx--    [ anon ]
00007f146a8e3000       4       0       0 -----    [ anon ]
00007f146a8e4000    1024      12      12 rwx--    [ anon ]
00007f146a9e4000    1028      12      12 rw---    [ anon ]
00007f146aae5000    1144     764     764 rw---    [ anon ]
00007f146ac56000       4       0       0 -----    [ anon ]
00007f146ac57000     508      44      44 rw---    [ anon ]
00007f146acd6000      88      20       0 r-x--  single_byte.so
00007f146acec000    2048       0       0 -----  single_byte.so
00007f146aeec000      20      20      20 rw---  single_byte.so
00007f146aef1000    1028      12      12 rw---    [ anon ]
00007f146aff2000       4       0       0 -----    [ anon ]
00007f146aff3000    1024      16      16 rwx--    [ anon ]
00007f146b0f3000       4       0       0 -----    [ anon ]
00007f146b0f4000    1024      16      16 rwx--    [ anon ]
00007f146b1f4000    1028      12      12 rw---    [ anon ]
00007f146b2f5000       4       0       0 -----    [ anon ]
00007f146b2f6000     508      44      44 rw---    [ anon ]
00007f146b4f5000       4       0       0 -----    [ anon ]
00007f146b4f6000    1024      48      48 rwx--    [ anon ]
00007f146b5f6000    1028      12      12 rw---    [ anon ]
00007f146b6f7000       4       0       0 -----    [ anon ]
00007f146b6f8000    1024      40      40 rwx--    [ anon ]
00007f146b7f8000    1028      12      12 rw---    [ anon ]
00007f146b8f9000       4       0       0 -----    [ anon ]
00007f146b8fa000    1024      16      16 rwx--    [ anon ]
00007f146b9fa000    1028      12      12 rw---    [ anon ]
00007f146bafb000       4       0       0 -----    [ anon ]
00007f146bafc000    1024      32      32 rwx--    [ anon ]
00007f146bbfc000    1028      12      12 rw---    [ anon ]
00007f146bcfd000       4       0       0 -----    [ anon ]
00007f146bcfe000    1024      16      16 rwx--    [ anon ]
00007f146bdfe000    1028      12      12 rw---    [ anon ]
00007f146beff000       4       0       0 -----    [ anon ]
00007f146bf00000    1024      16      16 rwx--    [ anon ]
00007f146c000000   65536   65480   65480 rw---    [ anon ]
00007f1470000000   65536   65472   65472 rw---    [ anon ]
00007f1474000000   65536   65472   65472 rw---    [ anon ]
00007f1478000000   65536   65480   65480 rw---    [ anon ]
00007f147c000000   65520   59456   59456 rw---    [ anon ]
00007f147fffc000      16       0       0 -----    [ anon ]
00007f1480000000   65536   65468   65468 rw---    [ anon ]
00007f1484000000   58784   58180   58180 rw---    [ anon ]
00007f1487968000    6752       0       0 -----    [ anon ]
00007f1488000000   65536   65536   65536 rw---    [ anon ]
00007f148c000000   65536   65400   65400 rw---    [ anon ]
00007f1490000000   63736   62360   62360 rw---    [ anon ]
00007f1493e3e000    1800       0       0 -----    [ anon ]
00007f1494000000   65532   65496   65496 rw---    [ anon ]
00007f1497fff000       4       0       0 -----    [ anon ]
00007f149807d000    1028      12      12 rw---    [ anon ]
00007f149817e000       4       0       0 -----    [ anon ]
00007f149817f000    1024      16      16 rwx--    [ anon ]
00007f149827f000    1028      12      12 rw---    [ anon ]
00007f1498380000       4       0       0 -----    [ anon ]
00007f1498381000    1024      16      16 rwx--    [ anon ]
00007f1498481000    1028      12      12 rw---    [ anon ]
00007f1498582000       4       0       0 -----    [ anon ]
00007f1498583000    1024      16      16 rwx--    [ anon ]
00007f1498683000    1028      12      12 rw---    [ anon ]
00007f1498784000       4       0       0 -----    [ anon ]
00007f1498785000    1024      16      16 rwx--    [ anon ]
00007f1498885000    1028      12      12 rw---    [ anon ]
00007f1498986000       4       0       0 -----    [ anon ]
00007f1498987000    1024      16      16 rwx--    [ anon ]
00007f1498a87000    1028      12      12 rw---    [ anon ]
00007f1498b88000       4       0       0 -----    [ anon ]
00007f1498b89000    1024      16      16 rwx--    [ anon ]
00007f1498c89000    1028      12      12 rw---    [ anon ]
00007f1498d8a000       4       0       0 -----    [ anon ]
00007f1498d8b000    1024      16      16 rwx--    [ anon ]
00007f1498e8b000    1028      12      12 rw---    [ anon ]
00007f1498f8c000       4       0       0 -----    [ anon ]
00007f1498f8d000    1024      16      16 rwx--    [ anon ]
00007f149908d000  113100     660       0 r-x--  libociei.so
00007f149ff00000    1020       0       0 -----  libociei.so
00007f149ffff000       4       4       4 rw---  libociei.so
00007f14a0000000   65536   65500   65500 rw---    [ anon ]
00007f14a4068000    1028      12      12 rw---    [ anon ]
00007f14a4169000       4       0       0 -----    [ anon ]
00007f14a416a000    1024      16      16 rwx--    [ anon ]
00007f14a426a000    1028      12      12 rw---    [ anon ]
00007f14a436b000       4       0       0 -----    [ anon ]
00007f14a436c000    1024      16      16 rwx--    [ anon ]
00007f14a446c000    1028      12      12 rw---    [ anon ]
00007f14a456d000       4       0       0 -----    [ anon ]
00007f14a456e000    1024      16      16 rwx--    [ anon ]
00007f14a466e000    1028      12      12 rw---    [ anon ]
00007f14a476f000       4       0       0 -----    [ anon ]
00007f14a4770000    1024      16      16 rwx--    [ anon ]
00007f14a4870000    1028      12      12 rw---    [ anon ]
00007f14a4971000       4       0       0 -----    [ anon ]
00007f14a4972000    1024      36      36 rwx--    [ anon ]
00007f14a4a72000    1028      12      12 rw---    [ anon ]
00007f14a4b73000       4       0       0 -----    [ anon ]
00007f14a4b74000    1024      16      16 rwx--    [ anon ]
00007f14a4c74000    1028      12      12 rw---    [ anon ]
00007f14a4d75000       4       0       0 -----    [ anon ]
00007f14a4d76000    1024      16      16 rwx--    [ anon ]
00007f14a4e76000    1028      12      12 rw---    [ anon ]
00007f14a4f77000       4       0       0 -----    [ anon ]
00007f14a4f78000    1024      16      16 rwx--    [ anon ]
00007f14a5078000    1028      12      12 rw---    [ anon ]
00007f14a5179000       4       0       0 -----    [ anon ]
00007f14a517a000    1024      48      48 rwx--    [ anon ]
00007f14a527a000    1028      12      12 rw---    [ anon ]
00007f14a537b000       4       0       0 -----    [ anon ]
00007f14a537c000    1024      48      48 rwx--    [ anon ]
00007f14a547c000    1288     272     272 rw---    [ anon ]
00007f14a55be000       8       4       0 r-x--  iso_8859_1.so
00007f14a55c0000    2044       0       0 -----  iso_8859_1.so
00007f14a57bf000       4       4       4 rw---  iso_8859_1.so
00007f14a57c0000   38456    8716       0 r-x--  libclntsh.so.11.1
00007f14a7d4e000    1024       0       0 -----  libclntsh.so.11.1
00007f14a7e4e000    1588    1584    1572 rw---  libclntsh.so.11.1
00007f14a7fdb000     148      56      56 rw---    [ anon ]
00007f14a8000000   62488   62184   62184 rw---    [ anon ]
00007f14abd06000    3048       0       0 -----    [ anon ]
00007f14ac000000   65536   65488   65488 rw---    [ anon ]
00007f14b0000000   15956    3712    3712 rw---    [ anon ]
00007f14b0f95000   49580       0       0 -----    [ anon ]
00007f14b4034000     328     328     328 rw---    [ anon ]
00007f14b4086000      20      12       0 r-x--  libnss_dns-2.12.so
00007f14b408b000    2044       0       0 -----  libnss_dns-2.12.so
00007f14b428a000       4       4       4 r----  libnss_dns-2.12.so
00007f14b428b000       4       4       4 rw---  libnss_dns-2.12.so
00007f14b428c000       4       0       0 -----    [ anon ]
00007f14b428d000    1024      16      16 rwx--    [ anon ]
00007f14b438d000    1028      12      12 rw---    [ anon ]
00007f14b448e000       4       0       0 -----    [ anon ]
00007f14b448f000    1024      68      68 rwx--    [ anon ]
00007f14b458f000    1028      16      16 rw---    [ anon ]
00007f14b4690000     136      32       0 r-x--  libncurses.so.5.7
00007f14b46b2000    2044       0       0 -----  libncurses.so.5.7
00007f14b48b1000       4       4       4 rw---  libncurses.so.5.7
00007f14b48b2000     232      92       0 r-x--  libreadline.so.6.0
00007f14b48ec000    2048       0       0 -----  libreadline.so.6.0
00007f14b4aec000      32      32      32 rw---  libreadline.so.6.0
00007f14b4af4000       4       4       4 rw---    [ anon ]
00007f14b4af5000      28      24       0 r-x--  readline.so
00007f14b4afc000    2048       0       0 -----  readline.so
00007f14b4cfc000       4       4       4 rw---  readline.so
00007f14b4cfd000      28      12       0 r-x--  bcrypt_ext.so
00007f14b4d04000    2044       0       0 -----  bcrypt_ext.so
00007f14b4f03000       4       4       4 rw---  bcrypt_ext.so
00007f14b4f04000     928     372       0 r-x--  libstdc++.so.6.0.13
00007f14b4fec000    2048       0       0 -----  libstdc++.so.6.0.13
00007f14b51ec000      28      28      28 r----  libstdc++.so.6.0.13
00007f14b51f3000       8       8       8 rw---  libstdc++.so.6.0.13
00007f14b51f5000      84       4       4 rw---    [ anon ]
00007f14b520a000    6368    2192       0 r-x--  init.so
00007f14b5842000    2044       0       0 -----  init.so
00007f14b5a41000     244     244     244 rw---  init.so
00007f14b5a7e000      12       8       8 rw---    [ anon ]
00007f14b5a81000       4       0       0 -----    [ anon ]
00007f14b5a82000    1024      12      12 rwx--    [ anon ]
00007f14b5b82000    1028      12      12 rw---    [ anon ]
00007f14b5c83000       4       0       0 -----    [ anon ]
00007f14b5c84000    1024      12      12 rwx--    [ anon ]
00007f14b5d84000    1028      12      12 rw---    [ anon ]
00007f14b5e85000     368      32       0 r-x--  nokogumboc.so
00007f14b5ee1000    2044       0       0 -----  nokogumboc.so
00007f14b60e0000      12      12      12 rw---  nokogumboc.so
00007f14b60e3000      48      36       0 r-x--  libnss_files-2.12.so
00007f14b60ef000    2048       0       0 -----  libnss_files-2.12.so
00007f14b62ef000       4       4       4 r----  libnss_files-2.12.so
00007f14b62f0000       4       4       4 rw---  libnss_files-2.12.so
00007f14b62f1000     284     184     184 rw---    [ anon ]
00007f14b6338000    2580     380       0 r-x--  libnnz11.so
00007f14b65bd000    1020       0       0 -----  libnnz11.so
00007f14b66bc000     264     224     224 rw---  libnnz11.so
00007f14b66fe000       8       4       4 rw---    [ anon ]
00007f14b6700000     172     144       0 r-x--  oci8lib_220.so
00007f14b672b000    2048       0       0 -----  oci8lib_220.so
00007f14b692b000       8       8       8 rw---  oci8lib_220.so
00007f14b692d000      92       8       0 r-x--  CP932.so
00007f14b6944000    2044       0       0 -----  CP932.so
00007f14b6b43000       4       4       4 r----  CP932.so
00007f14b6b44000       4       4       4 rw---  CP932.so
00007f14b6b45000    2204     892       0 r-x--  nokogiri.so
00007f14b6d6c000    2048       0       0 -----  nokogiri.so
00007f14b6f6c000      48      48      48 rw---  nokogiri.so
00007f14b6f78000       8       8       8 rw---    [ anon ]
00007f14b6f7a000       4       4       0 r-x--  md5.so
00007f14b6f7b000    2044       0       0 -----  md5.so
00007f14b717a000       4       4       4 rw---  md5.so
00007f14b717b000      16      16       0 r-x--  cparse.so
00007f14b717f000    2044       0       0 -----  cparse.so
00007f14b737e000       4       4       4 rw---  cparse.so
00007f14b737f000      80      52       0 r-x--  bigdecimal.so
00007f14b7393000    2044       0       0 -----  bigdecimal.so
00007f14b7592000       4       4       4 rw---  bigdecimal.so
00007f14b7593000       4       0       0 -----    [ anon ]
00007f14b7594000     772     128     128 rw---    [ anon ]
00007f14b7655000       4       0       0 -----    [ anon ]
00007f14b7656000    1024      16      16 rwx--    [ anon ]
00007f14b7756000    1292      36      36 rw---    [ anon ]
00007f14b7899000       4       0       0 -----    [ anon ]
00007f14b789a000    1024      16      16 rwx--    [ anon ]
00007f14b799a000    1028      12      12 rw---    [ anon ]
00007f14b7abc000       4       0       0 -----    [ anon ]
00007f14b7abd000     508      44      44 rw---    [ anon ]
00007f14b7b3c000       4       0       0 -----    [ anon ]
00007f14b7b3d000    1024      16      16 rwx--    [ anon ]
00007f14b7c3d000    1028      12      12 rw---    [ anon ]
00007f14b7e5f000     132      12      12 rw---    [ anon ]
00007f14b7e80000       4       0       0 -----    [ anon ]
00007f14b7e81000    1024      16      16 rwx--    [ anon ]
00007f14b7f81000    1028      12      12 rw---    [ anon ]
00007f14b8082000      12      12       0 r-x--  hitimes.so
00007f14b8085000    2044       0       0 -----  hitimes.so
00007f14b8284000       4       4       4 rw---  hitimes.so
00007f14b8285000       4       4       0 r-x--  fiber.so
00007f14b8286000    2044       0       0 -----  fiber.so
00007f14b8485000       4       4       4 rw---  fiber.so
00007f14b8486000      40      36       0 r-x--  generator.so
00007f14b8490000    2044       0       0 -----  generator.so
00007f14b868f000       4       4       4 rw---  generator.so
00007f14b8690000       4       4       0 r-x--  utf_32le.so
00007f14b8691000    2044       0       0 -----  utf_32le.so
00007f14b8890000       4       4       4 rw---  utf_32le.so
00007f14b8891000       4       4       0 r-x--  utf_32be.so
00007f14b8892000    2044       0       0 -----  utf_32be.so
00007f14b8a91000       4       4       4 rw---  utf_32be.so
00007f14b8a92000       4       4       0 r-x--  utf_16le.so
00007f14b8a93000    2048       0       0 -----  utf_16le.so
00007f14b8c93000       4       4       4 rw---  utf_16le.so
00007f14b8c94000       4       4       0 r-x--  utf_16be.so
00007f14b8c95000    2048       0       0 -----  utf_16be.so
00007f14b8e95000       4       4       4 rw---  utf_16be.so
00007f14b8e96000      24      20       0 r-x--  parser.so
00007f14b8e9c000    2044       0       0 -----  parser.so
00007f14b909b000       4       4       4 rw---  parser.so
00007f14b909c000     124     112       0 r-x--  libyaml-0.so.2.0.4
00007f14b90bb000    2044       0       0 -----  libyaml-0.so.2.0.4
00007f14b92ba000       4       4       4 rw---  libyaml-0.so.2.0.4
00007f14b92bb000      24      24       0 r-x--  psych.so
00007f14b92c1000    2048       0       0 -----  psych.so
00007f14b94c1000       4       4       4 rw---  psych.so
00007f14b94c2000      20      20       0 r-x--  strscan.so
00007f14b94c7000    2048       0       0 -----  strscan.so
00007f14b96c7000       4       4       4 rw---  strscan.so
00007f14b96c8000       4       4       0 r-x--  fcntl.so
00007f14b96c9000    2044       0       0 -----  fcntl.so
00007f14b98c8000       4       4       4 rw---  fcntl.so
00007f14b98c9000     320     176       0 r-x--  openssl.so
00007f14b9919000    2048       0       0 -----  openssl.so
00007f14b9b19000      16      16      16 rw---  openssl.so
00007f14b9b1d000     212     156       0 r-x--  date_core.so
00007f14b9b52000    2044       0       0 -----  date_core.so
00007f14b9d51000       8       8       8 rw---  date_core.so
00007f14b9d53000       4       4       4 rw---    [ anon ]
00007f14b9d54000      12       4       0 r-x--  windows_31j.so
00007f14b9d57000    2044       0       0 -----  windows_31j.so
00007f14b9f56000       4       4       4 rw---  windows_31j.so
00007f14b9f57000      28      24       0 r-x--  stringio.so
00007f14b9f5e000    2048       0       0 -----  stringio.so
00007f14ba15e000       4       4       4 rw---  stringio.so
00007f14ba15f000      60      40       0 r-x--  zlib.so
00007f14ba16e000    2048       0       0 -----  zlib.so
00007f14ba36e000       4       4       4 rw---  zlib.so
00007f14ba36f000     164      88       0 r-x--  socket.so
00007f14ba398000    2044       0       0 -----  socket.so
00007f14ba597000       4       4       4 rw---  socket.so
00007f14ba598000      12      12       0 r-x--  digest.so
00007f14ba59b000    2048       0       0 -----  digest.so
00007f14ba79b000       4       4       4 rw---  digest.so
00007f14ba79c000       4       4       0 r-x--  sha1.so
00007f14ba79d000    2044       0       0 -----  sha1.so
00007f14ba99c000       4       4       4 rw---  sha1.so
00007f14ba99d000      24      12       0 r-x--  etc.so
00007f14ba9a3000    2044       0       0 -----  etc.so
00007f14baba2000       4       4       4 rw---  etc.so
00007f14baba3000      12       4       0 r-x--  console.so
00007f14baba6000    2044       0       0 -----  console.so
00007f14bada5000       4       4       4 rw---  console.so
00007f14bada6000      28      24       0 r-x--  pathname.so
00007f14badad000    2044       0       0 -----  pathname.so
00007f14bafac000       4       4       4 rw---  pathname.so
00007f14bafad000      12      12       0 r-x--  thread.so
00007f14bafb0000    2048       0       0 -----  thread.so
00007f14bb1b0000       4       4       4 rw---  thread.so
00007f14bb1b1000       8       8       0 r-x--  transdb.so
00007f14bb1b3000    2048       0       0 -----  transdb.so
00007f14bb3b3000       4       4       4 rw---  transdb.so
00007f14bb3b4000       8       4       0 r-x--  encdb.so
00007f14bb3b6000    2044       0       0 -----  encdb.so
00007f14bb5b5000       4       4       4 rw---  encdb.so
00007f14bb5b6000      28       8       0 r--s-  gconv-modules.cache
00007f14bb5bd000       4       0       0 -----    [ anon ]
00007f14bb5be000      12       8       8 rwx--    [ anon ]
00007f14bb5c1000    1028      28      28 rw---    [ anon ]
00007f14bb6c2000   96836      12       0 r----  locale-archive
00007f14c1553000      24      24      24 rw---    [ anon ]
00007f14c1565000    2616    2012       0 r-x--  libruby.so.2.2.0
00007f14c17f3000    2044       0       0 -----  libruby.so.2.2.0
00007f14c19f2000      32      32      32 rw---  libruby.so.2.2.0
00007f14c19fa000      72      56      56 rw---    [ anon ]
00007fff921e6000     128      92      92 rwx--    [ stack ]
00007fff92206000       4       4       4 rw---    [ anon ]
00007fff923d9000       4       4       0 r-x--    [ anon ]
ffffffffff600000       4       0       0 r-x--    [ anon ]
----------------  ------  ------  ------
total kB         2495300 1635380 1616400

**Comment by alexfalkowski** [comment]
So I have been monitoring our process for the last 24 hours and the process has grown from 1.59637 GB to 2.226264 GB that is about 630MB. Not sure how to interpret this yet. Will carry out more experiments.

**Comment by mperham** [comment]
Please open a new issue when you have solid proof of an bug in Sidekiq.  I don't want to leave ambiguous issues like this one open.  Memory leaks can come from any point in an app.

**Comment by alexfalkowski** [comment]
OK I understand your point of view. Right now I have an issue that after a few days the server gets exhausted of memory, because of the sidekiq process. When I have the time I will see if I can find a way to replicate this. Right now I am mitigating it by restarting the process every day.

If I can't find a solution I will be forced to look for an alternate solution.

Thanks for your help with this.

**Comment by mperham** [comment]
Restarting it nightly is quite common. We deployed daily, meaning it wasn't an issue. I recommend using Inspeqtor or monit to monitor memory and restart when necessary.

**Comment by alexfalkowski** [comment]
Cool I will look at that.
