### ISSUE TITLE
Proposal: Use GIDs if available

### ISSUE THREAD

**Issue by miksago** [mperham/sidekiq#2299]
Following on from https://github.com/mperham/sidekiq/issues/2298, it turns out I'd been passing an entire ActiveRecord object, which was killing the YAML serialisation. A better solution than serialising to YAML would be to make use of Global IDs (https://github.com/rails/globalid) if available.

**Comment by seuros** [comment]
You can use ActiveJob if you want to use Globalid for example. 
Sidekiq should not be coupled with Rails.

**Comment by mperham** [comment]
I think this is a good idea. Yaml is a really heavyweight serialization scheme that we should avoid if we can use GID instead.

**Comment by miksago** [comment]
I don't actually have any ActiveJob or Sidekiq Worker code, as in my code I'm using:

```
PersonMailer.delay.welcome_email(@person)
```

Which seems like the DRY-est and cleanest way to do what I want to do. Creating an ActiveJob for each email type I want to send seems super messy.

**Comment by seuros** [comment]
You can use ```PersonMailer.welcome_email(@person).deliver_later```

**Comment by miksago** [comment]
hmm, true, I can; but then how do I set the queue it'll use? I'm not too familiar with the internals here.

**Comment by aprescott** [comment]
This seems like it could be good in the general case for any worker/job, although I'm not sure if it might push people into the habit of unknowingly serializing other objects that don't have a global ID. Right now, if you're not using ActiveJob, you can trust that whatever you give to `perform_async` will get dumped into Redis as YAML. This would obviously change that behavior depending on the object being passed as an argument.

**Comment by mperham** [comment]
If we can switch delay to serialize with nothing but JSON types + GlobalID where possible, I think that could be a win.  YAML serialization includes the full object state, which is an anti-pattern, and can lead to very large job arguments.

**Comment by aprescott** [comment]
Yeah that's definitely a place where I want it. I'm not sold on using ActiveJob over straight Sidekiq at the moment, but currently that means async mail sending requires a whole Sidekiq class just to send mail (because I don't want a serialized complex object). So having GlobalID support is probably a win.

**Comment by meoooh** [comment]
Is any update for this?

**Comment by mperham** [comment]
I think tying Sidekiq to GlobalID would be a mistake.  I've been very clear since day one: use simple, JSON-native types for job arguments.  Trying to transparently marshal large objects leads to slow, messy serialization code.  ActiveJob is a reasonable choice if you wish to use GlobalID with Sidekiq, it just won't be native for the time being.

I've also made it clear that `delay` is a crutch and not recommended long-term.  It was added for compatibility and as a migration path off Delayed::Job.  It is not recommended precisely because it can lead to gigantic job arguments and slow performance.  If you are careful to pass small types to `delay`, it will work great for sending mails really easily.
