### ISSUE TITLE
Getting information about jobs in various states

### ISSUE THREAD

**Issue by ujjwal** [mperham/sidekiq#2335]
I am wondering if there is a way to get more detailed about jobs from the web ui. The *Processed* and *Failed* tabs aren't clickable. Is there anyway to get more information?

![ui](https://cloud.githubusercontent.com/assets/108404/7507139/d18bd2ee-f41f-11e4-80fc-a784ae508035.png)

I am using Redis 2.6.13, Sidekiq-Pro 2.0.1, Sidekiq 3.3.2. Thanks!

**Comment by mperham** [comment]
What information do you want?

**Comment by ujjwal** [comment]
The failed jobs are more interesting for debugging - any kind of stack or error message would be useful.

**Comment by mperham** [comment]
That's what retries are. Please read the error handling wiki page.

**Comment by ujjwal** [comment]
Thanks! I'll check it out

**Comment by aprescott** [comment]
When I first started using Sidekiq, I thought I needed that information, but the reality is I haven't ever actually needed it. Any error information that you need to reference for jobs that failed but later succeeded should be caught by the same error tracking (such as New Relic) as the rest of your application. I've yet to find a concrete use case for more specific information about succeeding jobs or failing jobs, personally. There *is* a slight need for aggregate data beyond what New Relic gives us, but we're looking at solving that with a separate tracking approach, not through the web UI.

I mention that only because I'm curious if you have a specific problem you're trying to solve.
