### ISSUE TITLE
Undefined method `settings' for NewRelic::Rack::BrowserMonitoring on Sidekiq Pro 2.0.2

### ISSUE THREAD

**Issue by aprescott** [mperham/sidekiq#2344]
Based on the 2.0.2 changelog, I think the new Sidekiq Pro `Sharding` class is hitting an integration problem with New Relic where it tries to call `@app.settings.redis_pool` and there is no such `settings` method for the `NewRelic::Rack::BrowserMonitoring` middleware?

This causes an error when trying to view the web UI:

```
NoMethodError: undefined method `settings' for #<NewRelic::Rack::BrowserMonitoring:0x007f0be4ecb8e0>

path/to/gems/sidekiq-pro-2.0.2/lib/sidekiq/pro/web.rb:60:in `call'
...
```

Seen with:

* Sidekiq Pro 2.0.2.
* Sidekiq 3.3.4.
* newrelic_rpm 3.11.1.284

I'm not sure if this is a Sidekiq Pro problem or not.

**Comment by mperham** [comment]
I tested that feature with plain Sinatra, no other Rack middleware.  I wonder if NR is wrapping the Sinatra @app object.

**Comment by aprescott** [comment]
Based on [`agent_middleware.rb`](https://github.com/newrelic/rpm/blob/3.11.1.284/lib/new_relic/rack/agent_middleware.rb) and [`browser_monitoring.rb`](https://github.com/newrelic/rpm/blob/3.11.1.284/lib/new_relic/rack/browser_monitoring.rb), I think it's plain Rack middleware, but it happens to sit between Sidekiq and Sinatra?

It seems like Sidekiq Pro assumes that `@app` is always a Sinatra object that has `settings`, but it could in fact be anything else. Unless Sidekiq Pro can directly change Sinatra settings not just `@app`'s, the only fix I can see is to have each application specifically control the ordering of middleware such that Sidekiq Pro sits immediately in front of Sinatra, with nothing else between them.

**Comment by mperham** [comment]
I'm still confused.  One middleware should not be able to affect another middleware's view of the world.  Sinatra is setting up the Rack app as part of the middleware chain and NewRelic's hooks should be transparent.  The first stack on #2345 shows NR is injecting itself between every middleware.

**Comment by jasonrclark** [comment]
When NR's automated middleware instrumentation is enabled, we do wrap a number of things, so seems likely we're doing something wrong there.

Where does the `@app.settings` call happen from? Is that within a Sinatra route, or somewhere else? Going to see if I can dup, but don't have a copy of Pro to test against.

**Comment by jasonrclark** [comment]
On that note, setting `disable_middleware_instrumentation: true` in your `newrelic.yml` (or NEW_RELIC_DISABLE_MIDDLEWARE_INSTRUMENATION=true in your ENV) will get things clear. If you're running Sidekiq web somewhere that you don't need web tracing, that'd get you running again, but will definitely look to fix whatever's broken here.

**Comment by mperham** [comment]
NewRelic is a Pro customer, you can get source access if you want it.  ;-)

**Comment by jasonrclark** [comment]
Didn't realize we were! Will follow up on that, thanks.

**Comment by jasonrclark** [comment]
Got to the bottom of this, but not sure how we'd prefer to get it fixed.

The issue isn't actually the middleware tracing itself, but the fact that we default to using New Relic's middleware from Sinatra. The code in question that injects the middlewares during building the app is at https://github.com/newrelic/rpm/blob/6b310a9428618d4b611806c83014cb6e5365adc2/lib/new_relic/agent/instrumentation/sinatra.rb#L95-L102.

The `Sharding` middleware in Sidekiq Pro assumes that it's `@app` will be `Sidekiq::Web`, but it gets our middlewares instead.

I see a couple ways around this:

* `Sharding` could call `Sidekiq::Web.settings` instead of `@app.settings`. Because of how Sinatra does things, those are equivalent, and then `Sharding` avoids ordering assumptions.
* New Relic's Sinatra instrumentation could check for a method on the app during `build_with_newrelic` to ask whether to add middlewares. `Sidekiq::Web` could define that method and opt out.
* Although I'm leery of it, New Relic's agent middlewares could add `method_missing`, under the assumption that any call we don't recognize was meant for some other middleware/app we've been unknowingly inserted around. :see_no_evil: 

Thoughts on those options @mperham?

**Comment by aprescott** [comment]
I'm not @mperham but calling `Sidekiq::Web.settings` seems far cleaner.

**Comment by mperham** [comment]
I guess I don't understand what `@app` is supposed to be.  The name doesn't imply that it's the previous middleware entry.  With Sinatra, the app is supposed to be an instance of your application class.  If you're wrapping that app instance, you should use `method_missing` to delegate any unknown method to the underlying instance.

**Comment by aprescott** [comment]
Maybe I don't understand middleware either, but isn't `@app` also potentially a piece of middleware, which is where there is an ordering issue depending on which piece of middleware is added at which time? Conceptually a piece of middleware looks exactly like the application: they both expose `call`, because the application is also "Rack-compliant". So `@app.foo` could be calling the Real App's `foo`, or it could be calling a piece of middleware's `foo`.

**Comment by mperham** [comment]
@aprescott That wouldn't work because the app needs to have instance-specific data: the redis pool to use.  In effect I create "instances" by creating custom subclasses for each sharded instance of `Sidekiq::Pro::Web`.  Sinatra allows this because `settings` is per-class.

**Comment by jasonrclark** [comment]
All the agent's does here is add middlewares to Sinatra's list for startup. So `app` passed to `Sharding#initialize` is just the next callable thing in the middleware chain. Without the agent it's the Sinatra app, with the agent it happens to be one of our middlewares instead.

I see why the custom subclasses messes with accessing settings. Didn't have sharding configured on the test app, so I missed that.

Because we're just a standard middleware, though, `method_missing` doesn't seem right. I mean, you don't expect all middlewares to forward arbitrary method calls they receive, right? That's all that's happening here--the agent's put middlewares in that `Sharding` wasn't expecting.

Option 2 seems best to me--we provide an opt-out that `Sidekiq::Web` could tap into. I can get that in the next agent release if you're game @mperham.

**Comment by mperham** [comment]
I still don't see why Sidekiq needs to work around this.  If I do this:

```ruby
require 'rack/logger'
app.use Rack::Logger
app.use Sharding
```

it works just fine, i.e. the issue is specific to the NR middleware.  I agree that the Rack spec is nebulous here.  I would prefer a solution which does not require a vendor-specific solution.  I still maintain that NewRelic, as a profiling hook, should be transparent to the rest of the system.

**Comment by aprescott** [comment]
@mperham if you switch the `app.use` lines, does it still work?

With `Rack::Logger` followed by `Sharding`, `Rack::Logger` is called first, which asks `Sharding` for a response, which then goes to the app. So it's working because `Sharding`'s `@app` is the application itself.

If you flip the two, do you get the `NoMethodError` from `@app.settings`? My guess is yes, because `Sharding` is calling out to `Rack::Logger`, and asking it to set `@app.settings`, which `Rack::Logger` won't have.

> I mean, you don't expect all middlewares to forward arbitrary method calls they receive, right? That's all that's happening here--the agent's put middlewares in that `Sharding` wasn't expecting.

+1 to this.

**Comment by aprescott** [comment]
http://verboselogging.com/2010/01/20/proper-rack-middleware-ordering + its images might be useful to anyone trying to visualise the Rack middleware ordering.

**Comment by jasonrclark** [comment]
Yeah, with this ordering it also fails:

```
app.use Sharding

require 'rack/logger'
app.use Rack::Logger
```

That said, I share your sentiment that NR should be transparent, so I'll think more about `method_missing`. It feels weird, but might be better than the perils of trying to change our position in the middleware stack.

**Comment by aprescott** [comment]
I don't think NR _isn't_ transparent here. The main contract `@app` has from within a piece of middleware, really, is that you can call `call` on it. NR's middleware isn't violating that. Which is why to me this looks like a Sidekiq Pro middleware issue.

**Comment by mperham** [comment]
The ultimate problem is that I can't implement this feature without access to the original app instance.  Can I get access to the original `@app` somehow or ensure that my middleware is always first?

**Comment by aprescott** [comment]
I don't think you can automatically ensure the middleware is first (or last, depending on your view, I guess?). You'd have to enforce that requirement on each application that uses `Sharding`. But that feels like a pretty onerous requirement. If any other piece of middleware had the same requirement of taking priority, the two would never be compatible in the same application, which sort of defeats the point.

I'm not sure if there's a way to access to the "original" application in general, given that everything is supposed to be modular and composed. But maybe there's something related to [the `@run` ivar](https://github.com/rack/rack/blob/e364ecbcca9c5b32204bb1361cbcadfa715dd2f5/lib/rack/builder.rb#L104)?

**Comment by jasonrclark** [comment]
Rack doesn't provide any way to get at the stack. Trust me, if there was, I'd know about it and my life would have been much simpler :grin: The only options to force yourself first are also pretty hacky.

I think, though, that Sinatra's got you covered. What if instead of this:
```
      app.use Sharding
```

you did this:
```
      app.before do
        Thread.current[:sidekiq_redis_pool] = self.settings.redis_pool
      end

      app.after do
        Thread.current[:sidekiq_redis_pool] = nil
      end
```

`before/after` blocks execute within the context of the app, so `self` should be the right thing there. If you had other middlewares this might be a problem (since you wouldn't have the pool set when they ran), but from what I can see, `Sharding` was the only instance of middleware used with `Sidekiq::Web`, OSS or Pro.

I don't see how to get the Pro web to use that `with` method to generate custom subclasses, but it worked fine in the base case, with and without New Relic.

**Comment by mperham** [comment]
Awesome, thanks for the help, I will try this tomorrow.

**Comment by mperham** [comment]
Seems to work perfect, will release 2.0.3 as soon as I finish #2347

**Comment by aprescott** [comment]
Thank you both so much! :heart:

**Comment by mperham** [comment]
2.0.3 is out

**Comment by jasonrclark** [comment]
:rocket: :sparkles:
