### ISSUE TITLE
After restart it still shows that jobs are running

### ISSUE THREAD

**Issue by rudkovsky** [mperham/sidekiq#2448]
I noticed that when I restart sidekiq and there's no running jobs anymore in the interface it still shows that these jobs are running. It's not an issue until you're using and rely on sidekiq-status gem to show in interface whether job is in progress or not. What helps in this case it's only to flushdb in Redis.

**Comment by mperham** [comment]
If Sidekiq exits cleanly, all jobs should be cleaned out of Redis.  If you `kill -9` Sidekiq, the jobs will linger up to one minute in Redis.

If you are running in Heroku, unclean shutdown means jobs can linger forever since I can't use the PID to distinguish between old and new processes.  You can try lowering the shutdown timeout in that case: `-t 5` to give Sidekiq more time to shutdown cleanly.
