### ISSUE TITLE
Job Profiling

### ISSUE THREAD

**Issue by davydovanton** [mperham/sidekiq#2503]
Hello, 

I want to create something like job profiling (see [GSoC idea for more details](https://github.com/rubygsoc/rubygsoc/wiki/Ideas-for-Sidekiq#job-profiling)).
Now I am thinking about creating middleware, in which I will call job code with profiling tool. For example:

``` ruby
# in worker
class MyWorker
  enable_profile

  def prerform
    # run my job code
  end
end

# in middleware

module Sidekiq
  class Profiler
    def call(worker, msg, queue)
      # I use abstract Profiler tool
      Profiler.start do
        yield
      end
    end
  end
edn
```

After that I want save and process information.

**Pros**:
- simple
- reliability

**Cons**:
- for each platform its instrument (https://github.com/ruby-prof/ruby-prof, https://github.com/rubinius/rubinius-profiler, https://github.com/jruby/jruby/wiki/Profiling-jruby)
- I think that jobs will work slowly

Your ideas?

**Comment by seuros** [comment]
As a gem : :+1: . I don't think @mperham wants to add such feature to sidekiq core.

PS: I have something like that. we can work on OSS it.

**Comment by davydovanton** [comment]
@seuros yes, of course it will separate plugin for sidekiq like as [sidekiq-statistic](https://github.com/davydovanton/sidekiq-statistic) (or may be it will one part of this plugin).

In this thread I want discuss this feature and how I or we can create this.

**Comment by davydovanton** [comment]
@mperham and what do you think?

**Comment by mperham** [comment]
Rather than enabling profiling for all jobs of a single type, you should use a job key to enable profiling for a single job:

```ruby
class SomeWorker
  include Sidekiq::Worker
  sidekiq_options :profile => true
end

# or...
Sidekiq::Client.push('class' => ..., 'args' => ..., 'profile' => true)
```

I tried to do this 6 months ago and stopped because [Ruby's profiling APIs can't target a single thread](https://bugs.ruby-lang.org/issues/10602) so it is effectively impossible to build a good profiler for Sidekiq with MRI.  You might be able to get something working well on JRuby or Rubinius but I have not investigated those platforms in detail.
