### ISSUE TITLE
Sidekiq 3.5.0 does not need the Rack::Session::Cookie middleware configured in standalone setups

### ISSUE THREAD

**Issue by urkle** [mperham/sidekiq#2555]
We upgraded to sidekiq 3.5.0 which added an ```enable :sessions``` setting to the Sidekiq::Web sinatra application.  This has the side affect of initializing the Rack::Session::Cookie middlware automatically.  Thus when you have the ```use``` line in your config.ru it causes two session middlewares to be active with different secrets causing the session to be recycled every request.  And this makes all posts fail (due to CSRF being regenerated every request).

Please update the documentation to reflect that this line is not needed and instead will cause issues.

Thanks!

**Comment by mperham** [comment]
3.5.0 is several weeks old; if your statement is true, shouldn't we be seeing a bunch of people reporting it as not working?

**Comment by urkle** [comment]
Only if people noticed the issue in 3.4.2 when you added Rack::Protection..  So the only users who would run into this are the ones who first upgraded to 3.4.2 and then later upgraded to 3.5.0.

And yes this issue does occur as I spent the last hour tracking it down.   If you look at https://github.com/sinatra/sinatra/blob/v1.4.6/lib/sinatra/base.rb#L1770  you'll see that when you ```enable :sessions``` it sets up the session middleware for you with a random session secret (generated further up in the file).

**Comment by mperham** [comment]
Ok, thanks, fair enough.  I updated the wiki to remove those lines.

**Comment by sivalingams** [comment]
/Users/user/.rvm/gems/ruby-2.1.5/gems/sidekiq-3.5.0/lib/sidekiq/web.rb:267: warning: toplevel constant Session referenced by ActionDispatch::Request::Session

Just now upgraded sidekiq to 3.5.0 and I'm getting this warning in rails console.

**Comment by inkstak** [comment]
Hi, I'm facing a similar problem using Sidekiq 3.5.1 with Rails and Devise.

My Rails session is shared between subdomains :

    #config/initializers/session_store.rb
    Rails.application.config.session_store :cookie_store, key: '_foo', domain: :all, tld_length: 2

Sidekiq is mounted in an engine, which use a sudomain :

    #config/routes.rb
    mount Jobs::Engine, at: '/', constraints: { subdomain: 'jobs' }

    #engines/jobs/config/routes
    mount Sidekiq::Web => '/sidekiq'

When I go to `//jobs.localhost.dev/sidekiq`, it creates two cookies when only the first is needed :
* _foo_session @ .localhsot.dev
* _foo_session @ jobs.localhsot.dev

So I fixed it by disabling sessions in a sub class, that I mounted instead of Sidekiq::Web

    module Jobs
      class SidekiqWeb < ::Sidekiq::Web
        disable :sessions
      end
    end

It seems to work fine like this, but am I subject to any risk doing that ?

**Comment by antulik** [comment]
+1 it's very very annoying bug, spent hours tracking it, using sidekiq 3.5.1

solution from @inkstak worked, but also curious about implications

**Comment by kgx** [comment]
I am also having an issue with Sidekiq::Web's sessions using Sidekiq 3.5.4 and Rails 3.2.22, and I am using the DB session store.  Just upgraded from a pre 3.4.2 version, which did not have this issue.  The @inkstak fix worked for me as well.

**Comment by TylerRick** [comment]
I also ran into some troubles related to Sidekiq::Web's sessions and was able to resolve them using...
```
Sidekiq::Web.class_eval do
  disable :sessions
end
```

My app is using sidekiq 4.1.0 on rails 3.2 and mounting `Sidekiq::Web` into the main Rails app in  `config/routes.rb` using:
```
        constraints CanManageQueue do
          mount Sidekiq::Web => '/sidekiq', as: :queue_dashboard
        end

```
(the constraint checks for an authenticated admin user)

The main Rails app uses
```
config.session_store :active_record_store
```

The problem I was running into was that, after authenticating as an admin user in the main app, when a Sidekiq route such as `/admin/sidekiq/javascripts/application.js` was requested, it loaded fine the first time, but at the conclusion of the request, it reset the session due to this warning:

```
Warning! Rack::Session::Cookie data size exceeds 4K.
Warning! Rack::Session::Cookie failed to save session. Content dropped.
```

such that the very next request to any Sidekiq route (such as `/admin/sidekiq/javascripts/application.js`) resulted in a 404 / routing error.

Indeed, the main Rails app's session data exceeds 4K, but since it *should* be storing that data in an ActiveRecordStore, this *shouldn't* be a problem.

**Expected behavior**: That it would share the same session as the main Rails app, out of the box.

**Observed behavior**: Sinatra's default `Rack::Session::Cookie` store somehow prevents that from happening.

It may not be worth chasing down this issue since it is with an old Rails, but I thought I'd post in case it helped future Googlers (as @inkstak's post-issue-close comment sure helped me out—thank you!)...
