### ISSUE TITLE
`require': cannot load such file -- sinatra/base (LoadError)

### ISSUE THREAD

**Issue by sajjadmurtaza49** [mperham/sidekiq#2566]
Why we need to add gem 'sinatra', :require => nil in your Gemfile.?
While a person is working on ruby on rails - then why.?

**Comment by natematykiewicz** [comment]
Sinatra is only required if you want to use the UI, since that's what the UI was made with.

They needed to use some framework to make a small web app for the UI. Sidekiq does not require Rails in order to be used, so you can't assume that that Rails will be available. Sinatra is a light-weight Ruby framework, which is probably why they chose to use it.

**Comment by mperham** [comment]
Thanks for helping @natematykiewicz
