### ISSUE TITLE
Sidekiq::Manager doesn't reliably terminate on shutdown (Heroku)

### ISSUE THREAD

**Issue by smidwap** [mperham/sidekiq#2591]
When Heroku asks Sidekiq to shutdown via SIGTERM, Sidekiq gives running workers 8 seconds to finish before placing the unfinished jobs back in the queue. I believe this behavior was added as a result of https://github.com/mperham/sidekiq/issues/110.

Recently, I had an instance where this expected behavior didn't occur. Heroku killed the Sidekiq process via SIGKILL before Sidekiq had a chance to place the jobs back in the queue.

From my logs, here's the series of events:

````
15:16:22 - Heroku cycles all dynos
15:16:25 - Heroku sends SIGTERM to Sidekiq
15:16:26 - Sidekiq says it's shutting down
15:16:27 - Sidekiq says it'll pause up to 8 seconds to allow processes to finish
15:16:35 - Heroku kills Sidekiq, saying Sidekiq failed to exit within 10 seconds of SIGTERM
15:16:37 - Sidekiq process exists with status 137 (failed to exit within 10 seconds)
````

The result was an unfinished job got lost in cyberspace and, well, bad things happened :)

It looks like there's a delay between when Heroku sends the SIGTERM and when Sidekiq starts to shutdown. And looks like that delay is variable, and if it's too long, Sidekiq may not shutdown before Heroku sends SIGKILL.

I ran tests on this behavior on a Heroku app using this test job:

```ruby
class TestJob < ApplicationJob
  def perform
    sleep
  end
end
```

I wasn't able to reproduce Heroku killing Sidekiq before Sidekiq pushed its unfinished jobs back in the queue, but I did get a few close calls. For example, in one test case, Heroku sent SIGKILL *before* Sidekiq shutdown, but Sidekiq somehow still managed to wrap up its work and push the unfinished job back in the queue. Here's the order of log messages:

```
12:00:32 heroku/sidekiq.1:  Error R12 (Exit timeout) -> At least one process failed to exit within 10 seconds of SIGTERM 
12:00:32 heroku/sidekiq.1:  Stopping remaining processes with SIGKILL 
12:00:32 app/sidekiq.1:  WARN: Terminating 1 busy worker threads 
12:00:32 app/sidekiq.1:  WARN: Work still in progress [#<struct Sidekiq::BasicFetch::UnitOfWork queue="queue:default", message="{\"retry\":true,\"queue\":\"default\",\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"TestJob\",\"args\":[{\"job_class\":\"TestJob\",\"job_id\":\"4d4560e0-8aac-4e35-91b5-7aaee312bde2\",\"queue_name\":\"default\",\"arguments\":[]}],\"jid\":\"2099a16a97f5430eec1bf566\",\"enqueued_at\":1444146380.568534}">] 
12:00:32 app/sidekiq.1:  INFO: Pushed 1 messages back to Redis 

```

I'm not yet familiar with the Sidekiq internals, but the root problem could be that there's a delay between when Heroku sends SIGTERM and Sidekiq acting on it.

One solution might be for me to set the timeout to 7 seconds, or maybe even less. Would it make sense to make 7 seconds the default?

**Comment by mperham** [comment]
The shutdown timeout is definitely not millisecond-precise.  Things like lots of threads and slow Redis can delay it significantly.

**Comment by mperham** [comment]
I'm rewriting the manager right now and making the shutdown timeout more strict is one of my goals.

**Comment by smidwap** [comment]
@mperham That sounds great, thanks for all your hard work on this.

So am I correct to think that a bandaid would be to lower the timeout to 7, maybe even 6 seconds?

**Comment by mperham** [comment]
Yes.

**Comment by stevenharman** [comment]
@mperham Is there an issue or PR we can track (perhaps this one) w/r/t

> I'm rewriting the manager right now and making the shutdown timeout more strict

We're going to try setting our `-t` option to 6 or 7 seconds for now, but would like to have something to track to know if/when we can remove that workaround and go back to the defaults.

**Comment by mperham** [comment]
The rewrite is part of Sidekiq 4.0, which is #2593

**Comment by mperham** [comment]
If you could try 4.0.0.pre2, it should shutdown more precisely.

gem 'sidekiq', '4.0.0.pre2'

**Comment by BenTalagan** [comment]
Hi Mike,

I think I've been seeing this issue quite a few times during the last days on heroku with sidekiq 4.0.1. I got aware of it because I did a few restarts in a row, and they generated leaking ActiveRecord connections due to Sidekiq not being able to close cleanly. Here is a timed log example :

```
2015-12-23T11:32:57.698980+00:00 heroku[worker.1]: Stopping all processes with SIGTERM
2015-12-23T11:32:59.228777+00:00 app[worker.1]: 3 TID-otfjmd27o INFO: Shutting down
2015-12-23T11:32:59.228813+00:00 app[worker.1]: 3 TID-otfjmd27o INFO: Terminating quiet workers 
2015-12-23T11:32:59.229701+00:00 app[worker.1]: 3 TID-otfk55174 INFO: Scheduler exiting...
2015-12-23T11:32:59.734053+00:00 app[worker.1]: 3 TID-otfjmd27o INFO: Pausing to allow workers to finish...
2015-12-23T11:33:00.679737+00:00 heroku[worker.1]: Stopping all processes with SIGTERM
2015-12-23T11:33:01.394094+00:00 heroku[worker.1]: Starting process with command `bundle exec sidekiq`
[... A sidekiq job is continuing and printing stuff ...]
2015-12-23T11:33:02.028291+00:00 heroku[worker.1]: State changed from starting to up
[... A sidekiq job is continuing and printing stuff ...]
2015-12-23T11:33:06.842651+00:00 app[worker.1]: 3 TID-otfjmd27o WARN: Work still in progress [#<struct Sidekiq::LimitFetch::UnitOfWork etc etc>]
2015-12-23T11:33:06.842179+00:00 app[worker.1]: 3 TID-otfjmd27o WARN: Terminating 1 busy worker threads
2015-12-23T11:33:07.863726+00:00 heroku[worker.1]: Error R12 (Exit timeout) -> At least one process failed to exit within 10 seconds of SIGTERM
2015-12-23T11:33:07.863726+00:00 heroku[worker.1]: Stopping remaining processes with SIGKILL
```

I've seen the `:timeout` option in sidekiq with is used by the launcher as a deadline for the hard shutdown of workers, but have not played with it yet. But it's set to 8 seconds by default, shouldn't it be lowered since a lot of people are using heroku? Note that I had only 1 long running worker in my example ; to be precise it was doing a `Restclient.post` on a slow remote client at the time of the shutdown.

**Comment by mperham** [comment]
I don't understand your issue. If you want a lower timeout, then lower it with -t.

**Comment by BenTalagan** [comment]
Hi Mike ;  I don't really have an issue, I know I can lower it. I was just pointing out that the **default** value of 8 seconds may be a bit too big as it seems problems will occur quite frequently on heroku.

**Comment by mperham** [comment]
@BenTalagan If you lower it, you increase the odds of duplicate job execution.  The correct answer is to use USR1 or the `Sidekiq::Process#quiet!` API to signal your deploy in advance.

**Comment by BenTalagan** [comment]
@mperham Really sorry, I think I'm still not clear at all. Correct me if I'm wrong, what I understand about sidekiq's behaviour on shutdown is the following : 

1 - On SIGTERM, stop polling for jobs
2 - Wait 'timeout' seconds (8 by default) for every running job to have a chance to finish gracefully.
3 - Send a Sidekiq::Shutdown interrupt to any remaining thread to 'kill' them, then call wait on each thread to ensure they have been terminated. This is the "hard_shutdown" of the manager that calls processor.kill for each processor. 
4 - Do the remaining cleanup (close connections & the like).

What I have seen on heroku is that quite often, I get a SIGKILL from heroku during 3), because small lags may appear here and there. So 4) is never executed and things may stay unclean (especially, leaking connections on PostGres side because Sidekiq could not close them). 

I think it's important to have that final cleanup executed in any case, that's why I was suggesting to lower the timeout *just a bit*, to let some time to Sidekiq to execute that cleanup. I did a few tests today and currently have set the timeout to 7 which seems to give better luck. But it's hard to tweak.

**Comment by stevenharman** [comment]
For anyone coming back to this, years later... it seems Heroku has, quietly, increased the `SIGTERM` timeout from 10 to 30 seconds. I don't recall seeing any announcement to that effect, but it's mentioned in two different spots in the Heroku Dev Center docs:

1. https://devcenter.heroku.com/articles/dynos#shutdown
2. https://devcenter.heroku.com/articles/limits#exit-timeout

Still not ideal, but better, I guess.
