### ISSUE TITLE
Support Ruby's frozen string mode

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#2741]
Ruby 2.3 allows a new frozen string magic comment.  Add the comment to the top of all Sidekiq source files, remove all `.freeze` calls, get the test suite running and smoke test the system.

**Comment by mperham** [comment]
I realize this will backslide performance a little bit on Ruby 2.2 if we remove .freeze but I'm ok with that.  We'll call it 4.1 and recommend Ruby 2.3.

**Comment by petergoldstein** [comment]
@mperham You may want to wait on a formal release until Ruby 2.3.1 is out.

I know that there's at least one showstopper bug preventing us from moving to Ruby 2.3.0 that will be fixed in 2.3.1 - Resolv::IPv6.create is completely broken because of frozen string issues.  You can see details here - https://github.com/ruby/ruby/commit/a3b53cd9919ff01567ef04af4057b3dec3192471

**Comment by mperham** [comment]
@petergoldstein I'm not sure I understand your concern.  How does a bug in Ruby's Resolv prevent us from using frozen strings?

**Comment by petergoldstein** [comment]
@mperham My concern is that I think 2.3.0 isn't quite ready for prime time.  The frozen string change was a big one that impacted most of the Ruby code base.  Significant bugs (e.g. the IPv6 one) that impact large swaths of functionality are being found just a few days after the 2.3.0 release.

So making 2.3.0 the 'recommended' Ruby for use with Sidekiq feels premature to me.  But it's a judgment call, which is why I suggested that you may want to wait until 2.3.1 is out (or you may not).

**Comment by mperham** [comment]
Oh, I see.  Yeah, it might be a bit premature to recommend a Ruby that is a week old.  :-)  Fair enough.

**Comment by mperham** [comment]
Looks like frozen strings aren't all that.  Will reconsider if new data comes to light.
