### ISSUE TITLE
Shutdown is visibly slower in Sidekiq 4

### ISSUE THREAD

**Issue by Nowaker** [mperham/sidekiq#2774]
^C is visibly slower on my laptop after I bumped from 3 to 4. Shutdown (on idle) wasn't super fast even on 3, now it's even worse. It matters for development where we need to restart Sidekiq as there's no live-reload.

**Comment by mperham** [comment]
Caused by [this](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/manager.rb#L67)  It might be reasonable to change this:

```diff
- PAUSE_TIME = $TESTING ? 0.1 : 0.5
+ PAUSE_TIME = (development? || testing?) ? 0.1 : 0.5
```

I'll do some thinking about alternatives but we really want to give the shutdown event handlers time to run in production.  Perhaps we can change them into Concurrent::Futures and give them a max of 0.5 sec to run before bailing.

**Comment by Nowaker** [comment]
Production is a different story. Do what's best in there. But development should respond to ^C (Interrupt) as fast as possible. I wouldn't mind PAUSE_TIME = 0 for development.
