### ISSUE TITLE
Feature Request: Improved enterprise statsd integration

### ISSUE THREAD

**Issue by jcarlson** [mperham/sidekiq#2815]
Beyond the stats Sidekiq collects built in, we'd like to be able to add some additional stats at collection time, including a per-queue measure of latency. It would be great to see the stats collector customizable.

Some additional thoughts: our StatsD agent is actually a DataDog client, which supports a superset of features compared with a standard StatsD client; namely DataDog adds support for tagging. So it would be nice to be able to customize the built in stats with tags, override the built in stats, or remove/replace them entirely.

As an example, instead of:

```
$statsd.gauge("sidekiq.enqueued", total_jobs_enqueued)
```

We'd like to be able to do something like:

```
Sidekiq::Queue.all.each do |queue|
  $dogstatsd.gauge("sidekiq.enqueued", queue.count, tags: ["queue:#{queue.name}"]
end
```

Reporting each queue's depth individually to the same metric name with a unique tag gives us lots of report-time flexibility that we might not get if each queue was reported as a separate metric, e.g. `"sidekiq.enqueued.default"`.

**Comment by seuros** [comment]
I think if this feature is only available for DataDog, it should be in a separate gem.  
I don't think we should implement vendor specific features in the core.

**Comment by jcarlson** [comment]
No, I'm not suggesting that Sidekiq add support for vendor-specific features. But it would be nice if Sidekiq provided an extensible way for me to customize the stats collection process without having to monkey-patch the built-in code (which is what I've done in my app today).

**Comment by natematykiewicz** [comment]
Would this be something that could be done with a custom middleware?

**Comment by mperham** [comment]
@natematykiewicz Not really.  Middleware is run on every job execution, so if you are executing 1000 jobs/sec, you'll get 1000 pings/sec to statsd.  Enterprise's historical metrics instead are sent to statsd once every 30 seconds so it's far more efficient.

**Comment by jhoffner** [comment]
Doesn't statsd batch requests by default every 10s?

**Comment by mperham** [comment]
It doesn't batch unless you ask it to and it doesn't aggregate metrics over a time period on the client-side.

**Comment by jhoffner** [comment]
Ah, I see now that `Statsd::Batch.new($statsd)` has to be used.

**Comment by jhoffner** [comment]
Ah, I see now that `Statsd::Batch.new($statsd)` has to be used. @mperham time periods are not collected? How?

@jcarlson Why not just do this?
```ruby
Thread.new do
  loop do
    Sidekiq::Queue.all.each do |queue|
      $dogstatsd.gauge("sidekiq.enqueued", queue.count, tags: ["queue:#{queue.name}"]
    end
    sleep 30
  end
end
```

Thats what I'm doing (at 10s intervals). Is there something wrong with this approach?

**Comment by SuperQ** [comment]
Another option would be to use the Prometheus[0] metrics library.  It tracks stats locally instead of having to do batching.  It should be easy enough two have something that polls the Prometheus metrics endpoint and shovels it to datadog for those that need it.

FYI, I'm looking into how we can extract metrics from Sidekiq into GitLab's Prometheus integration.

[0]: https://github.com/prometheus/client_ruby

**Comment by joestump** [comment]
The Datadog agent ships with [DogStatsD](http://docs.datadoghq.com/guides/dogstatsd/) and they have what appears to be an API compatible [client](https://github.com/DataDog/dogstatsd-ruby). This should be a drop-in for the existing middleware?

**Comment by mperham** [comment]
Yessirree, that's correct.

**Comment by mperham** [comment]
I've added the ability to collect custom metrics as part of the history collection.  You can now pass a block to `save_history` and capture additional metrics within that block.

```ruby
statsd = Statsd.new(...)
Sidekiq.configure_server do |config|
  config.save_history(statsd) do |statsd, stats|
    # statsd is the Statsd client
    # stats is the Sidekiq::Stats object which is being saved.
    statsd.batch do
      statsd.gauge(...)
    end
  end
end
```

Unfortunately I don't see any way to cleanly override or modify the existing metrics capture without redefining the entire thing.  I've refactored the code so that the default metrics capture can easily be monkeypatched out of existence.  You can use the custom capture block to define your own metrics capture.  This work will be in 1.6.0.
