### ISSUE TITLE
4.0 isn't recovering gracefully when Redis disappears?

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#2866]
I fixed one problem recently but have two reports now that jobs just sit enqueued and aren't processed.  Investigate.

**Comment by 01010000101001100** [comment]
@mperham thanks for your efforts, appreciate it. Actually, in my case jobs don't even go to "enqueued", sidekiq doesn't even initiate them although he runs in idle. This happens when I restart heroku, means some configs with heroku are lost because if I push the initial code with clean database, everything works just fine. Weird stuff.
