### ISSUE TITLE
Sidekiq does not de-allocate the memory

### ISSUE THREAD

**Issue by kskaran94** [mperham/sidekiq#2871]
I have multiple sidekiq jobs running, But after they have finished they do not de-allocate memory.
I am not including any "trouble-some " gems.

**Comment by mikegee** [comment]
Perhaps your application doesn't work well with Ruby's default memory management. This is very unlikely a problem with Sidekiq. Check out this article for an overview of how Ruby uses memory: http://www.sitepoint.com/ruby-uses-memory/

Please try to determine if the problem is actually with Sidekiq or your application. Stackoverflow would be the right place to get help with your application's usage of Sidekiq.
