### ISSUE TITLE
Using environment variables in sidekiq

### ISSUE THREAD

**Issue by makshark** [mperham/sidekiq#2894]
Hi, I am new in sidekiq. I need to advise. How I can create and manage environment variables in sidekiq (for example use .env or Figaro) if I do not run rails environment.

**Comment by mikegee** [comment]
Your problem is stated so generally, I don't know how to respond. What specifically are you trying to do? What have you tried? Did it not work as you expected?

By the way, Sidekiq's issues are typically reserved for bug reports, not support requests. Wanna ask on StackOverflow? Perhaps drop the link to that thread here.
