### ISSUE TITLE
Feature request: "Clear queue" button in Sidekiq Dashboard

### ISSUE THREAD

**Issue by jonathan-upstart** [mperham/sidekiq#2981]
The "Queues" tab in the Sidekiq Dashboard has a "Delete" button for each queue. We rarely (actually never) want to delete an entire queue, but we sometimes want to clear all jobs in a queue. I'd like to request that we add a "Clear" button to this page, so that we can clear the queue without deleting it entirely.

Currently we do this in a prod console: `Sidekiq::Queue.new(:queue_name).clear`.

I'm happy to submit a PR if you like this idea @mperham .

**Comment by mperham** [comment]
I believe delete and clear are semantically identical.

**Comment by jonathan-upstart** [comment]
Ahh my bad, thanks!

**Comment by aprescott** [comment]
Perhaps "Clear" is a better word for the web UI to use? I initially avoided even considering using "Delete" as a Sidekiq user, because it seemed like it might do something drastic, like block incoming jobs. (I now know that that's sort of a silly idea to have, but... :))

**Comment by mperham** [comment]
Sounds good. Do we have a translation for 'Clear'?  I hate to change wording only in English.

**Comment by Persola** [comment]
@mperham Is there a certain set of locales you'd like included?

**Comment by mperham** [comment]
@Persola We're not changing the wording.

**Comment by axos88** [comment]
Umm. why? It's super confusing.

**Comment by skatenerd** [comment]
FWIW I was scared to hit 'delete' until I found this issue.

**Comment by juffel** [comment]
> FWIW I was scared to hit 'delete' until I found this issue.

Just FYI: The queue will disappear from the WebUI after you clicked 'delete', but will reappear as soon as another job is added to that queue.

**Comment by abury** [comment]
Chiming in here, also feel like 'delete' will delete the entire queue, not the jobs within the queue.

**Comment by brandondrew** [comment]
> I believe delete and clear are semantically identical.

@mperham 

I don't doubt that you intended them to mean the same thing, and therefore _they mean the same thing **to you**_, but we have empirical evidence that other people don't understand them the same way, shown in the comments on this issue, and the existence of the issue itself.

We can think of the word "meaning" as having 3 main meanings:

1. what is intended by the speaker (or writer)
2. what is understood by the listeners (or readers)
3. what is recorded in dictionaries (simply a compilation by lexicographers of examples of 1 and 2)

Since you obviously understand your intended meaning (# 1), it may be hard for you to understand how the rest of the world reads "delete queue" (# 2), and to believe that they don't understand it the way you intended it, but I'll do my best to explain how I understood it, and how I see others understanding it here.

Deleting a queue implies to many of us that the queue itself is going away, which may lead one to wonder what problems might occur.  Will jobs meant for that queue have no where to go once the queue is deleted? Clearing a queue simply means deleting the jobs in the queue.  

Remember that the rest of the world cannot rely on intimate knowledge of the inner workings of Sidekiq to disambiguate the terms.  In addition to knowing what you meant, you know that there's no harm caused by "deleting" the queue.  But most everyone else is limited to what is written on the button, and their knowledge of how those words are normally used.

If you're still not convinced, please think about the use of these words in other contexts.  Let's start with a document.  If you're working in a word processor, and you're asked to clear the document, wouldn't probably mean deleting the text inside the document?  If you're asked to delete the document, wouldn't that mean deleting the file from the file system?

Please reconsider changing the wording.

I'd be happy to help with localization.  I speak Spanish and Portuguese, and I know many native speakers who can verify or improve my translation.  I also know native speakers of many other languages (Arabic, Chinese, French...)

**Comment by brandondrew** [comment]
That would certainly be helpful, yes.

**Comment by mperham** [comment]
I've added explanatory text as a tooltip and on the Are You Sure? dialog.
