### ISSUE TITLE
Bundler and sidekiqswarm

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#3025]
Several customers are reporting incompatibilities between swarm's auto-require of the :default gem group and the Rails bootup.  Swarm should provide a flag to disable any Bundler pre-load; this will negate any CoW memory savings but still provide the advantage of a single point of control for all N processes and maximum compatibility with existing apps.

**Comment by danielnc** [comment]
We're having an issue with Cancancan gem because of Bundler pre-load and loading gems in the wrong order.

Because of this: https://github.com/CanCanCommunity/cancancan/blob/develop/lib/cancan/controller_additions.rb#L397 we're getting load_and_authorize_resource undefined method errors

My assumption is that ActionController::Base is not loaded when Cancancan gem is making that method unavailable to the controllers.

A quick fix I did was to manually do the specific include on my ApplicationController and that fixed the issue.

Any suggestion on how to perma-fix this issue without waiting for your patch that will disable Bundle.require(:default)?

**Comment by mperham** [comment]
Can you gist your Gemfile (minus any ent credentials of course)?

**Comment by danielnc** [comment]
Sure:

https://gist.github.com/danielnc/ceec0a76ddfa7b0fb717b2a7b6a4856b

**Comment by mperham** [comment]
Hmmm, I don't see any smoking guns there.  Can you post the error here?

**Comment by mperham** [comment]
Released 1.2.2 https://github.com/mperham/sidekiq/wiki/Ent-Multi-Process#bundler-preload

**Comment by danielnc** [comment]
Will create a minimal rails app that reproduces this specific error tomorrow morning and send the link here
