### ISSUE TITLE
Redis::TimeoutError

### ISSUE THREAD

**Issue by edaraanand** [mperham/sidekiq#3035]
Hi,
we are experiencing Redis::TimeoutError in our production environment. This happens every one hour.
Log from airbrake:
File	/gems/redis-3.2.2/lib/redis/connection/ruby.rb:55
Error type	Redis::TimeoutError
Error message	Connection timed out
Where	sidekiq#

**Comment by mperham** [comment]
Hi there, the issue tracker is not a place to get help with system debugging.  The wiki contains a good amount of content about [troubleshooting](https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting) but you'll need to track down the source of your error as it is most likely due to application, network and environmental settings, not a bug in Sidekiq.  If you feel there is a Sidekiq bug at the root, please open an issue with your findings.
