### ISSUE TITLE
PG::UnableToSend: server closed the connection unexpectedly This probably means the server terminated abnormally before or while processing the request.

### ISSUE THREAD

**Issue by igorkasyanchuk** [mperham/sidekiq#3128]
lease help resolve issue with

Message PG::UnableToSend: server closed the connection unexpectedly This probably means the server terminated abnormally before or while processing the request. Traceback PG::UnableToSend: server closed the connection unexpectedly This probably means the server terminated abnormally before or while processing the request.

full log: https://gist.githubusercontent.com/igorkasyanchuk/cc96dba31b0b0f83b77faadf077433e8/raw/70af94105b0a7649b6ad0dde086ac539902d1d3f/gistfile1.txt

we have 2 app servers + 1 db. we have pool 25 and workers 20, rails, sidekiq, pg.

it happen only with sidekiq background workers.

thanks for advices

**Comment by mperham** [comment]
StackOverflow is the right place to get help with application config issues.

**Comment by pmichaeljones** [comment]
Hi Mike. I know this is an old issue that has **nothing** to do with Sidekiq, but this might help others that are looking for the same bug. Congrats on reaching Sidekiq's 6th birthday as well. 

I have a super simple Sidekiq job that uploads a file to Filestack, using their Ruby SDK. After they return the URL for the saved file, I save it in my DB. Everything goes smoothly until I try to save the new database model. I've gotten every type of PG error possible: PG::UnableToSend, PG::ConnectionBad: PQconsumeInput(), PG::UnableToSend: SSL connection has been closed unexpectedly. You name it.

I've been haunted by this bug for two days and have wasted a solid 10 hours fixing it. In reality, I've learned a ton about AR in those 10 hours. Turns out, in my case, it was because the Parallel gem, which Filestack uses, was finishing its external API call, then then closing the AR connection.

I did absolutely everything everyone recommended for this bug on SO, adjusting connection pool, reaper frequency, TCP idle and timeout, nothing worked.

[Here's the Parallel issue:] (https://github.com/grosser/parallel/issues/62)

Anyways, if any other developers out there stumble upon this comment, take a look if you're using the Parallel gem and make sure it's updated.

I'm going to write a blog post about this because it was such a bugger to find.

**Comment by mperham** [comment]
Yep, you are using parallel to fork multiple processes, those processes are all trying to use the same socket at the same time.  This is a race condition and leads to unpredictable, weird errors.  Don't use parallel without resetting any necessary sockets in each forked copy.
