### ISSUE TITLE
Spurious swarm 'restarting' messages

### ISSUE THREAD

**Issue by ryansch** [mperham/sidekiq#3138]
Ruby version:
Sidekiq / Pro / Enterprise version(s): 4.1.3/3.3.3/1.3.2

If relevant, please include your initializer and any error message with the full backtrace.
`[swarm] Child exited, PID 2952, code 0, restarting...`

I have a log full of these messages but none of them appear to correspond to the actual sidekiq process.  My theory is that `waitpid2` is collecting processes that the workers are starting.  Checking the returned pid against the sidekiq processes first might help.

**Comment by mperham** [comment]
I suspect you are correct: sounds like a Worker is [forking a child process](http://apidock.com/ruby/v1_9_3_392/Process/detach/class) but not `wait`ing for its exit or `detach`ing so the child can be reaped cleanly.  The Sidekiq Enterprise master process is waiting for all child processes and so coincidentally cleaning up this child process that would otherwise [go zombie](https://en.wikipedia.org/wiki/Zombie_process).

Since this is technically a bug, should we more aggressively log something which points out the bug to the app developer?

Is this a bug in your app code or in another gem you are using?

**Comment by mperham** [comment]
Any followup?

**Comment by ryansch** [comment]
Sorry just noticed your original reply.  I'll have to investigate.

**Comment by ryansch** [comment]
@mperham Perfect.
