### ISSUE TITLE
Think again about pr/3114

### ISSUE THREAD

**Issue by devvit** [mperham/sidekiq#3159]
From v4.2.0, [pr/3114](https://github.com/mperham/sidekiq/pull/3114) merged

No, we cannot use 'require' like this.

Read http://ruby-doc.org/core-2.3.1/Kernel.html#method-i-require first, please.

```ruby
...
# "Loads the given name, returning true if successful and false if the feature is already loaded." from rubydoc
# You cannot decide file loaded or not with true|false
# So require(options[:require]) will be false forever
require(options[:require]) || raise(ArgumentError, not_required_message)
...
```

The correct way is still like before
```ruby
...
require(options[:require])
...
```

If you got errors about redis, you'd better check your code, but dont use 'require', :)

**Comment by Tonkonozhenko** [comment]
I know that it checks that file is loaded or not. 

If you run `sidekiq -r sidekiq.rb`, `require(options[:require])` returns false `because` it knows that `sidekiq` library is loaded and we will not get any error that file `sidekiq.rb` was not loaded.

I got the error about Redis because I had valid config but I was not loaded and didn't raise any exception.

**Comment by mperham** [comment]
The file that is specified by `-r` should never be loaded before Sidekiq tries to load it.  If it was, that indicates an error on the developer's part.
