### ISSUE TITLE
Unable to process jobs - Work still in progress & Pushed to Redis messages

### ISSUE THREAD

**Issue by dhakadamit** [mperham/sidekiq#3187]
Ruby version: 2.2.3
Sidekiq: 4.0.0

Our workers on heroku were unable to process jobs from one of the queues. We run multiple queues, the rest of them were working fine. Only one of the queue got stuck.

- Starting worker to process 'stuck' queue, was resulting in '**unable to establish DB connection**' error on heroku
- Restarting worker was showing a warning '**work still in progress; pushed jobs back to redis**'

 We tried the following without any luck:

1) Flushing Redis
2) Killing client connections on Redis
3) Pointing to a new instance of Redis
4) Restarting heroku workers
5) Starting workers on a new heroku application 

None of these worked. Finally, we had to queue jobs on a new queue and that did the trick. The older queue is still not getting processed.

Any ideas?

**Comment by mperham** [comment]
Upgrade.

**Comment by dhakadamit** [comment]
Has this been reported earlier? Can you point me to the issue and the fix? 

We had significant downtime for about 20 minutes due to this issue today in production. We have been using this version for almost 10 months and never faced any issue. It happened for the first time today. Need to ensure that this will not occur in the new version.

Thanks for your quick response.

**Comment by mperham** [comment]
If you have been using Sidekiq 4.0.0 for the last 10 months without issue and then suddenly bad stuff happens, you should dig into what changed recently.

x.0.0 releases often have many bugs.  I keep an [extensive changelog here](https://github.com/mperham/sidekiq/blob/master/Changes.md) which you can scan to see if you've experienced any of the issues.  I recommended an upgrade because that version is almost a year old.

**Comment by dhakadamit** [comment]
Thanks. Will check it out.
