### ISSUE TITLE
Sidekiq dropping jobs

### ISSUE THREAD

**Issue by spinx** [mperham/sidekiq#3414]
Latest Ruby and Sidekiq, Pro and Enterprise.

Sidekiq is dropping jobs. 

We've seen a couple of cases when this happens, and there might be more:
- Worker class is not present
- Arguments with non-utf8 characters break encoding 

Even though these are all app issues, I'd expect Sidekiq to fail them or something better than just deleting the job completely. 

Sidekiq also doesn't track dropped jobs in Metrics in Pro version - It would be good to track those so that we can alert on them.

**Comment by mperham** [comment]
Both your issues are solved in Sidekiq 5.0. The worker class not present issue is fixed since constantize is called within the global retry block.  The non-UTF8 data breaks JSON parsing and invalid JSON payloads are now pushed immediately to the Dead set.

Sidekiq doesn't ever want to drop jobs.  There's no metrics for dropped jobs because I don't want it to happen.

See #3301 for 5.0 details.
