### ISSUE TITLE
Handling NameError Well

### ISSUE THREAD

**Issue by Ataraxic** [mperham/sidekiq#3541]
Ruby version: 2.4.1
Sidekiq: 4.2.10 
Pro: 3.5.0
Enterprise version(s): 1.5.4

Something we've run into is that sometimes the constantize call will fail. This can occur in a few different ways, but we've mostly run into it with rollbacks where a new worker will queue up jobs that are unprocessable after a rollback occurs. I believe it can also happen when workers are being rotated and different versions are running side by side for a short period of time. 

There is one solution we're considering where all new workers will be required to be deployed as a dummy class whose only action is to move the job to a `name_errored` queue and otherwise complete successfully. This should ensure that the jobs are not lost and can be identified upon rollback. We don't want the jobs to get lose so we do not use a no-op, and we don't raise because I think that retrying is technically wrong in this scenario. If we do manage to release this new worker later on it's possible that a job could be delayed for a significant period of time with the exponential backoff. 

Reasons why we don't want to use this dummy class
1. It's harder to enforce when working with a large team, someone can easily forget
2. This must be done for each new worker
3. Treating this as a migration slows down development/releases

Instead I'm considering a monkey patch for the Sidekiq::Processor like so
```ruby
def process(work)
  # untouched
  @reloader.call do
    begin
     klass  = job_hash['class'.freeze].constantize
     # untouched, includes stats { execute_job } block
    rescue NameError => e
     # LogError
      Sidekiq::Client.push(
        'class' => job_hash['class'.freeze],
        'queue' => :name_errored,
        'args' => job_hash['args'.freeze]
      )
      ack = true
    end
  end
  # untouched
end
```

This should allow us to manually intervene and inspect the specific `name_errored` queue to determine what to do without losing the job in a private queue. This also lets us know very quickly that this occurred  as the RetrySet can be quite large.

Any thoughts appreciated.

**Comment by mperham** [comment]
This isn't a problem I hear about often; I don't understand why it's such a problem for you but the general rule is to treat worker changes like database migrations since jobs are persistent data.  If you want to change worker names or arguments, you should carefully consider forwards and backwards compatibility, especially if you have a deploy system that is rolling back often.

It should also be noted that Sidekiq 5.0 refactors the Processor so that constantize failures immediately go into the retry queue rather than sticking in the super_fetch's private queue.

**Comment by buddhistpirate** [comment]
We actually don't rollback often, which is the problem. It is a bit of overhead to deploy a dummy job before the actual change, when we rollback infrequently. However, in the case that we do rollback, it is very painful. That's why we're interested in making this change. Rolling back becomes less painful, without having to add developer overhead.

> It should also be noted that Sidekiq 5.0 refactors the Processor so that constantize failures immediately go into the retry queue rather than sticking in super_fetch's private queue.

I think this will work well enough for us. Thanks @mperham !
