### ISSUE TITLE
Obsolete workers shown in sidekiq web console on heroku

### ISSUE THREAD

**Issue by jeremyhaile** [mperham/sidekiq#3547]
Ruby version: 2.3.4
Sidekiq version: 4.2.10

The sidekiq web console shows a worker that is busy, but I've stopped all worker threads on heroku. I've then restarted all dynos. Still, the obsolete worker will not disappear out of the web view. 

Is there any way I can clear it manually?

**Comment by mperham** [comment]
There's no easy way to clear it manually.  You'd have to remove the data from Redis.  Sidekiq hasn't had a leaky worker data problem since 4.1.{2,3} a year ago.  Did you recently upgrade?

Run the scripts associated with those versions in the changelog and see if that clears the data for you.

https://github.com/mperham/sidekiq/blob/master/Changes.md#413

**Comment by jeremyhaile** [comment]
@mperham yes, we upgraded fairly recently. The script in the changelog fixed it. Thanks!
