### ISSUE TITLE
Questions about Sharding usage

### ISSUE THREAD

**Issue by fgrehm** [mperham/sidekiq#3605]
Ruby version: Ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux-gnu]
Sidekiq / Pro / Enterprise version(s): Sidekiq 4.1.2, Sidekiq Pro 3.3.1, Sidekiq Enterprise 1.3.1 

--------

We know that [docs says Sharding](https://github.com/mperham/sidekiq/wiki/Sharding) should be the last thing we should do but unfortunately we reached the point of having to do that as a temporary solution.

### App Configuration

Unfortunately there is not much information on the wiki about configuration changes required for starting a worker connected to the other Redis instance / DB (LMK if they are somewhere else) so we are wondering if the setup outlined in this gist represents a good approach on getting it going: https://gist.github.com/fgrehm/f189719f664e30bba78bf5256da96008

### Usage

Do we need to take some special caution when it comes to sending jobs to the new Redis instance besides sticking this to on our workers?

```ruby
class SomeWorker
  sidekiq_options pool: connection_pool_to_the_other_redis_instance
  # ...
end
```

Thanks in advance!

**Comment by mperham** [comment]
Part of the reason I don't document sharding well is because it is supposed to be painful/last resort.  It's better to start breaking your monolith into smaller services if you've reached the point of saturating a Redis instance.  One local Redis running on your own hardware can do 5,000+ jobs/sec.  Moving to stream processing is another alternative, like Kafka, that can handle 100,000+ items/sec.

## About Sharding

- A single Sidekiq process will always fetch from a single Redis.  You will have a cluster of Sidekiq processes for each Redis.
- The clients can push jobs to any Redis.  They can do this by setting up a connection pool for each Redis in the initializer:

```ruby
POOL_A = ConnectionPool.new { Redis.new(hostname: "redis-a.example.com") }
POOL_B = ConnectionPool.new { Redis.new(hostname: "redis-b.example.com") }
```

And then targeting a Redis either statically or dynamically when pushing jobs:

```ruby
class SomeWorker
  include Sidekiq::Worker
  sidekiq_options pool: POOL_A # statically
```

Dynamically:

```ruby
  pool = go_to_b? ? POOL_B : POOL_A
  Sidekiq::Client.via(pool) do
    SomeWorker.perform_async
  end
```

Your Sidekiq process can set its Redis target any way it wants in the initializer:

```ruby
Sidekiq.configure_server do |config|
  config.redis =  go_to_b? ? POOL_B : POOL_A
end
```

**Comment by fgrehm** [comment]
> Part of the reason I don't document sharding well is because it is supposed to be painful/last resort. It's better to start breaking your monolith into smaller services if you've reached the point of saturating a Redis instance.

Yeah, we are looking into breaking our monolith apart but as we all know that's a hard move to make 😄  This is a temporary solution to prevent potential bugs that might come from different teams that have a need to touch the mothership while we figure out that move.

Unfortunately we've had 2 really bad outages caused by different issues (not in Sidekiq but in our app itself) and we can't risk losing mission critical data that might be in Redis when that happens 😅 

> About Sharding

Thanks a lot for that info! LMK if u want me to update the Wiki or if u prefer to keep it as it is 🍻
