### ISSUE TITLE
Feature request: configurable maximum reschedules in Sidekiq::Limiter

### ISSUE THREAD

**Issue by rafaelsales** [mperham/sidekiq#3629]
Sidekiq Ent 1.5.4

The maximum reschedules is currently hard-coded to 20 in Sidekiq Ent which might not work for every project.

**Comment by mperham** [comment]
What would you propose?  I made it a standalone method so others could
monkeypatch it but I’d love ideas on how to make it a configurable knob.

Mike

**Comment by rafaelsales** [comment]
IMO using the same approach as the limiter backoff provides all flexibility needed, since the developer can do any calculation based on the limiter and the job

```ruby
Sidekiq::Limiter.configure do |config|
  config.maximum_reschedules = ->(limiter, job) do
    # some creepy calculation to return an integer
  end
end
```

**Comment by mperham** [comment]
Would it be too complex to roll it into the existing backoff?  job["overrated"] gives you the current count, you could return nil once the max retries has passed, hinting to Enterprise to trigger a retry, something like:

```ruby
Sidekiq::Limiter.configure do |config|
  config.backoff = ->(limiter, job) do
    if job["class"].constantize.is_a?(QuickJob)
      return nil if job["overrated"] > 5
    end
    60
  end
end
```

I'm not sure if the logic would get too complex and it's better to stick with your suggestion of two separate procs.

**Comment by rafaelsales** [comment]
That would work, but it feels quite subtle to me that you have to define the backoff proc to have a custom max reschedules...
From the implementation standpoint, I think it's more straightforward to keep it separate as well

**Comment by mperham** [comment]
Thank you for your patience here, sometimes I have to step away and ponder to determine the best approach.  Here's what you will be able to do starting in Ent 1.7.2:

```ruby
class SomeWorker
  include Sidekiq::Worker
  sidekiq_options max_limiter_retries: 10
```

The value is job-specific but you can add it to the worker default options if you want it to apply everywhere.  The limiter backoff is linear and the default retries of 20 leads to about 24 hours of limiter retries.  You can increase or decrease as necessary; once limiter retries are exhausted, further errors result in normal job retries with exponential backoff.

**Comment by rafaelsales** [comment]
@mperham Thanks!

**Comment by scottgratton** [comment]
Hey, I'm looking into making this change as well as generally, the errors added to the overlimit errors list retrying 20 times ([total of about 6d 13h 15m 16s](https://github.com/mperham/sidekiq/wiki/Error-Handling#automatic-job-retry)) is a lot when I'm really expecting mostly very temporary/intermittent api errors to be caught and retried- if jobs are actually blocked from API issues for more than a few hours, then I want to start hearing about it sooner than 6 days if I'm not watching the scheduled queue. I'm looking to back our global option down to 10 retries (being about 4 hours of retrying) before I start hearing about it. Really love this feature-- all of this to say, would you consider adding the job-specific example as well as global option on the documentation as I couldn't find it anywhere but this issue here? I'm assuming that setting `Sidekiq.options[:max_limiter_retries] = 10` in my initializer will update it globally for all jobs.

https://github.com/mperham/sidekiq/wiki/Ent-Rate-Limiting

Thanks!

**Comment by mperham** [comment]
I don’t believe that will work. You’d need to do this in the latest version:

Sidekiq::Limiter::DEFAULT_OPTIONS[:reschedule] = 10

**Comment by scottgratton** [comment]
@mperham thank you for the quick reply!
