### ISSUE TITLE
Enhancement:  Sidekiq swarm rolling restarts

### ISSUE THREAD

**Issue by HParker** [mperham/sidekiq#3631]
# Question

Could Sidekiq manage its own restarts better than upstart can?

# Motivation

Today, restarting Sidekiq probably means sending a `TERM` to Sidekiq waiting for work to finish and processes to exit then start Sidekiq again. Some downsides to this approach are,

- Sidekiq processes that take some significant amount of time need to either be killed and retried or set Sidekiq's timeout high enough that they are very likely to complete before being killed.

- Sidekiq processes that have finished and are not processing work won't restart and start processing work again until all processes have finished and exit.

# Proposal

Since Sidekiq swarm already manages the lifecycle of Sidekiq workers, it could also manage restarting workers similar to how passenger manages its processes.

A deploy would look something like,

1. Send `USR1`/`TSTP` (depending on Sidekiq version)
2. Get new code
3. Send `TERM` to Sidekiq worker managed by swarm
4. Swarm restarts workers with new code after they exit.

# Advantages

- Workers spend more time processing work and less time waiting to stop or start.

- Sidekiq is less likely to retry work due to a deploy killing a job.

# Disadvantages

- The Sidekiq swarm manager process never dies. The intended use for the swarm process is to take advantage of CoW GC in ruby. This is not a light weight process that is designed to live theoretically indefinitely.

- Workers processing as few as one job can still take up to the timeout waiting to exit.

**Comment by mperham** [comment]
As you note, this would require a new process manager binary which is designed to load no Ruby code and run "forever".  No such thing exists today and its responsibilities would overlap significantly with the sidekiqswarm binary.  Deploying with long-running jobs is a common support issue so providing some solution long-term is something I'd like to offer.  I like the direction you're proposing and I'll keep thinking about how to implement this.

**Comment by mperham** [comment]
I'm implementing rolling restart and long-running job support within Sidekiq Enterprise.  Thoughts:

The USR2 signal will be used to trigger a rolling restart.  The process manager will start a new swarm and send USR2 to the old swarm.  The old Sidekiqs will get USR2, in response they will quiet and **unlike TERM** immediately exit once all their jobs are complete; there will be no time limit/deadline to exit.  An old Sidekiq may process a job for many hours after USR2.

Today when a child goes over memory limits, sidekiqswarm issues `TSTP ; sleep 60; TERM` to the child: they have a hard shutdown.  We can change this to `USR2` so they exit ASAP but can run as long as necessary.

There's no plan to minimize memory usage during rolling restarts.  If you have lots of long jobs running, the old Sidekiqs and new Sidekiqs might run in parallel and use lots of memory.  Since we don't know when the old processes will exit, we can't wait around for an undetermined amount of time.

I'm not sure if USR2 is  available on JRuby; alternative suggestions for how to trigger a restart are welcome.

**Comment by mperham** [comment]
1.7 is out with this feature
