### ISSUE TITLE
Kubernetes liveness probe for worker

### ISSUE THREAD

**Issue by rosskevin** [mperham/sidekiq#3648]
Ruby version:
Sidekiq / Pro / Enterprise version(s):
5.0.5

I'd like to have/implement a [kubernetes liveness probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes) for a sidekiq worker.  

The liveness probe will `GET :8080/` and look for an HTTP 200 response. Effectively, I need to know that the worker is alive and successfully pinging redis, but I need to know this from outside.

My threading is rusty, but I was considering threading a [simple http server](https://stackoverflow.com/questions/25280521/ruby-http-server-in-separate-thread) that responds with a 200 ok.

If the main worker thread dies, I want the http thread to die as well.

1. Has this already been done? If so, any pointers to it?
2. If not, does this sound like a reasonable plan?  Any pointers?

Something like:

```ruby
require 'socket'
LIVENESS_PORT = 8080

Sidekiq.configure_server do |config|
  config.on(:startup) do
     Sidekiq::Logging.logger.info "Starting liveness server on #{LIVENESS_PORT}"
     Thread.start do
       server = TCPServer.new('localhost', LIVENESS_PORT)
       loop do
         Thread.start(server.accept) do |socket|
           request = socket.gets # Read the first line of the request (the Request-Line)
           ::Sidekiq.redis do |r|
             sidekiq_response = r.ping
           end

           if !sidekiq_response.eql? 'PONG'
             response = "Sidekiq is not ready: Sidekiq.redis.ping returned #{res.inspect} instead of PONG\n"
             Sidekiq::Logging.logger.error response
           else
             response = "Live!\n"
           end
           socket.print "HTTP/1.1 200 OK\r\n" +
                            "Content-Type: text/plain\r\n" +
                            "Content-Length: #{response.bytesize}\r\n" +
                            "Connection: close\r\n"
           socket.print "\r\n" # blank line separates the header from the body, as required by the protocol
           socket.print response
           socket.close
         end
       end
     end
  end
end
```

Thoughts?

**Comment by mperham** [comment]
Hi Kevin, that's a simple impl but it looks like it covers your needs.  It would die in the case of a network error so you might need some `rescue`ing in order to recover.

However: a user might have 20 Sidekiq processes on a single machine.  Would you expect them to take port 8080-8100?  Is that not the way k8s works, more like one process per container/IP?

**Comment by rosskevin** [comment]
My worker is a docker `container`, technically a kubernetes `pod`.  A `pod` can have multiple containers, though it is discouraged, but sometimes it can be necessary - this is usually called a `sidecar`.

So, I can run 20 worker pods (likely just 1 with horizontal autoscale on). All can run on 8080, kubernetes will map this, but 8080 itself is only exposed for kubernetes liveness probing. I think in the case of network error here (local network within the kube cluster), I might as well restart the worker.  I'll have to think about that, but thanks for looking it over.  I'll give it a shot.

**Comment by ramontayag** [comment]
@rosskevin did this work for you? Currently I don't check to see if the worker is up.

**Comment by rosskevin** [comment]
Last I checked I believe it did. We brought down that infrastructure and are about to bring it up again, so I can't give you a definite answer. It is certainly in the neighborhood of being correct.

**Comment by arturictus** [comment]
Hi,
I just released a gem using approach discussed here.
This approach worked really good for me.
Hope that helps. 
https://github.com/arturictus/sidekiq_alive

**Comment by pyromaniac** [comment]
Folks, what do you think about an alternative solution (purely for Sidekiq 6 though). Would it do the same job?

```
#!/usr/bin/env ruby
require_relative '../config/boot'
require 'sidekiq/api'

processes = Sidekiq::ProcessSet.new.size
$stdout.puts "Sidekiq processes: #{processes}"

processes.zero? and exit 1
```

It returns exit code 1 if there are no running processes.

**Comment by fabn** [comment]
> Folks, what do you think about an alternative solution (purely for Sidekiq 6 though). Would it do the same job?
> 
> ```
> #!/usr/bin/env ruby
> require_relative '../config/boot'
> require 'sidekiq/api'
> 
> processes = Sidekiq::ProcessSet.new.size
> $stdout.puts "Sidekiq processes: #{processes}"
> 
> processes.zero? and exit 1
> ```
> 
> It returns exit code 1 if there are no running processes.

It depends on your setup but this is not good as k8s liveness script because it monitors the whole process set.

By looking at sidekiq internals I think that can be tweaked in this way:

```ruby
require 'socket'
require 'sidekiq/api'
hostname = Socket.gethostname
me = Sidekiq::ProcessSet.new.find { |ps| ps['hostname'] == hostname }
# A process has its info expired => restart
unless me
  $stderr.puts "No matching sidekiq process in process table, restaring..."
  exit 1
end
```

This will work under the assumption that your k8s pod will run a single sidekiq worker (that will get pid 1) so its [identity](https://github.com/mperham/sidekiq/blob/8cc43f72fe63cd97bf60fabddb6e347a68cc1edd/lib/sidekiq/util.rb#L76) will be something like `sidekiq-worker-5fccc85768-xtzd9:1:ca8e3c680c42` and it will the only sidekiq worker with an hostname field set to `sidekiq-worker-5fccc85768-xtzd9`

@mperham are my assumptions correct?

Thanks.

**Comment by mperham** [comment]
I don't understand. Your code isn't determining if the current process is alive, but rather that there is at least one active process in your Sidekiq cluster? That's not the same thing. If you have two processes and one is dead, this code will still work fine. I would think a liveness check is as simple as `Sidekiq.redis { |c| c.ping }` as noted in the first comment.

I audited the sidekiq_alive codebase and it violates a number of my own personal rules. It may work fine for others but I would avoid it. The code in the first comment is still the best live check I've seen so far.

**Comment by fabn** [comment]
> I don't understand. Your code isn't determining if the current process is alive, but rather that there is at least one active process in your Sidekiq cluster? That's not the same thing. If you have two processes and one is dead, this code will still work fine. 

@mperham I agree with this sentence if you're referring to the previous snippet, i.e. the one from [this comment](https://github.com/mperham/sidekiq/issues/3648#issuecomment-740390095) that essentially does this check

```ruby
Sidekiq::ProcessSet.new.size > 0
```

> I would think a liveness check is as simple as `Sidekiq.redis { |c| c.ping }` as noted in the first comment.

I think this is not a livecheck for sidekiq itself but for redis instance and this kind of liveness check is already configured in redis k8s deployments, it does not provide any value to do that in sidekiq pods.

My proposal is slightly different and it does a check in a pod with this code:

```ruby
Sidekiq::ProcessSet.new.find { |ps| ps['hostname'] == Socket.gethostname } or exit(1)
```

This will exit if, and only if, sidekiq worker running on a specific pod is not reporting its hearthbeat. It works under the assumption that given a unique hostname there's only a single sidekiq worker running on that host, otherwise it may lead to false positives. 

If, for whatever reason, a worker process get stuck and stop reporting its heartbeat in redis instance without crashing, after a while its previous heartbeat key will expire and this check should trigger a pod restart by k8s.

I was asking your opinion about this approach that in my opinion should work but it rely on sidekiq internals so a second look from sidekiq maintainer is very welcome.
 
> I audited the sidekiq_alive codebase and it violates a number of my own personal rules. It may work fine for others but I would avoid it. The code in the first comment is still the best live check I've seen so far.

I don't like that approach either so I was looking for something that not mess with creating jobs or stuff like that.

**Comment by mperham** [comment]
> I think this is not a livecheck for sidekiq itself but for redis instance and this kind of liveness check is already configured in redis k8s deployments, it does not provide any value to do that in sidekiq pods.

Not quite. This is a check that the Sidekiq process **can talk to** Redis, i.e. has network connectivity. Without it, Sidekiq is effectively dead.

> This will exit if, and only if, sidekiq worker running on a specific pod is not reporting its hearthbeat.

I don't know what a "worker" is. Do you mean process? What if a process is reporting its heartbeat but the job threads are deadlocked? At some point, we have to define what `alive` means in this context. My `ping` suggestion checks that the process is not frozen and has network connectivity to Redis. I guess I don't see the value in checking for heartbeat.

**Comment by fabn** [comment]
> I don't know what a "worker" is. Do you mean process? 

Yes, I mean a sidekiq process.

> What if a process is reporting its heartbeat but the job threads are deadlocked? At some point, we have to define what `alive` means in this context. My `ping` suggestion checks that the process is not frozen and has network connectivity to Redis. I guess I don't see the value in checking for heartbeat.

I understand your point. The point is that it doesn't exist a "perfect" liveness check. My approach reports that a process can both talk to redis and it's somehow functioning. I didn't read all sidekiq code so I don't know exactly in which phase heartbeat is written in redis, but is better than nothing and doesn't require any external gem or any hack to sidekiq code, just relies of what is inside the gem.

Thanks for your time.

**Comment by dferrazm** [comment]
Hi all. Stumbled on this only now as we also need a liveness / readiness probes for our sidekiq pods. But noticed that @rosskevin implementation in the first comment always returns a `200 Ok` response no matter what, even if the ping response is not `PONG`.

According to the [kubernetes docs ](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-liveness-http-request):

> Any code greater than or equal to 200 and less than 400 indicates success. Any other code indicates failure.

Shouldn't we return eg `503` instead to indicate sidekiq is not ready yet, additionally rescuing any redis conn related errors like `RedisClient::CannotConnectError` to also return `503`, instead of probably timing out? Or am I missing something?

Example:

```rb
# ...

_request = socket.gets # Read the first line of the request (the Request-Line)

redis_response = begin
  ::Sidekiq.redis(&:ping) # try to connect to redis
rescue RedisClient::CannotConnectError
  nil
end

if redis_response.eql? 'PONG'
  status = '200 OK'
  response = "Live!\n"
else
  status = '503 Service Unavailable'
  response = "Sidekiq is not ready: Sidekiq.redis.ping returned #{redis_response.inspect} instead of PONG\n"
  ::Sidekiq.logger.error response
end

socket.print "HTTP/1.1 #{status}\r\n" \
              "Content-Type: text/plain\r\n" \
              "Content-Length: #{response.bytesize}\r\n" \
              "Connection: close\r\n"
socket.print "\r\n" # blank line separates the header from the body, as required by the protocol
socket.print response
socket.close
```

c/c @mperham

**Comment by mperham** [comment]
Sidekiq Enterprise added a health check in 7.2.0:

https://github.com/sidekiq/sidekiq/blob/main/Ent-Changes.md#720
https://github.com/sidekiq/sidekiq/wiki/Kubernetes#health-checks
