### ISSUE TITLE
Support for redis cluster

### ISSUE THREAD

**Issue by samuelebistoletti** [mperham/sidekiq#3655]
Ruby version: 2.2.3
Sidekiq open source

Hi,
I would like to know if Sidekiq supports Redis Cluster (on latest version), and in the case how to configure it.
I cannot find any reference on docs.

Thanks

**Comment by mperham** [comment]
I don't have any docs on using Redis Cluster specifically, you are welcome to contribute something if you get something working.  Most choose to use a SaaS if they need HA.

**Comment by collimarco** [comment]
Redis Cluster support would be interesting for **horizontal scalability**, and not only for HA. The problem is that currently Sidekiq uses a **few hot keys** and thus it would require some deeper changes in order to get benefits from key sharding, which is what Redis Cluster provides.

I was reasoning about getting infinite [scalability for Rails applications using Kubernetes](http://kubernetes-rails.com), and at the moment the only solution for scaling Sidekiq to multiple Redis instances (and go above ~100k jobs/s) is to **use multiple K8s Deployments** (of the web app and sidekiq) **and associate each deployment group to a different Redis instance**. 

For example:
Web Deployment 1 and Sidekiq Deployment 1 talk to Redis instance 1; 
Web Deployment 2 and Sidekiq Deployment 2 talk to Redis instance 2; 
etc. 

It's **an hand-crafted form of sharding**... Probably there are also other ways to achieve sharding within the Rails application itself. For example using a module operator over the server ID we could distribute the jobs over different Redis instances. Maybe this could also be added as a feature to Sidekiq.

Also note that the separate Redis instances would be required only for Sidekiq and the other data produced by the jobs could be written to a Redis Cluster, which provides automatic sharding.
