### ISSUE TITLE
Fail job and retry without raising error?

### ISSUE THREAD

**Issue by bradherman** [mperham/sidekiq#3689]
Ruby version: 2.4.1p111
Sidekiq / Pro / Enterprise version(s): 4.2.10 / 3.5.1 / 1.6.0

Is it possible to mark a job as failed or for retry without raising an exception?

We have a batch that runs nightly and occasionally things go wrong and it floods our error handling service and puts us over our limit.  The errors are usually all related to one thing (like an API issue) and logging hundreds of thousands when the issue is intermittent is undesirable.  I'd like to rescue any exception, mark the jobs for retry/failure (so that the Sidekiq batch callback reporting will be accurate) and continue without raising an exception. 

Here's an example of how I'd like this to work:

```
class BatchWorker
  include Sidekiq::Worker

  def perform
    batch = Sidekiq::Batch.new
    batch.on(:complete, self, {})
    SomeLargeArrayOfData.each do |line|
      ProcessLineWorker.perform_async(line)
    end
  end

  def on_complete(status, opts)
    # generate a report of # of failed/retried jobs, etc
  end
end

class ProcessLineWorker
  include Sidekiq::Worker

  def perform(line)
    begin
      # do work
    rescue => e
      mark_job_for_retry! # enables standard Sidekiq retry handling
      mark_job_as_failed! # allows the batch to know about failure/retry in Batch status
      # rescue keeps error from going to Rollbar, but job retries and Batch knows this job failed
    end
  end
end
```

Is something like this possible?

**Comment by mperham** [comment]
You must raise an error.  Sidekiq's fundamental approach is that success == return, failure == exception.  You will not have a good time if you break that pattern.

Can you tell Rollbar to ignore that type of exception?

https://rollbar.com/docs/notifier/rollbar-gem/#exception-level-filters

**Comment by bradherman** [comment]
Thanks for the quick response @mperham!

I looked into ignoring the exception with them previously and unfortunately the API rate limits still apply to ignored errors being sent.  I can monkey patch our error sending to ignore a special type of error though.

**Comment by mperham** [comment]
That's a little strange.  Why would their client even be **sending** ignored errors to their service?  They don't have a "drop" mode where the error is simply dropped client-side?

**Comment by bradherman** [comment]
Oh wait, I didn't read what you sent!  I had looked at error ignoring within the Web app, where you can tell it to ignore the errors there... I didn't realize you could do it at the client level.  Thanks!

**Comment by emad-elsaid** [comment]
You can do that by rescheduling your job again with the same parameters, so ti make it nicer you can also abstract it to a method on the job base class

**Comment by allanoneflare** [comment]
had it like this
```ruby
    def perform
    # ...
    rescue Net::ReadTimeout => ex
      raise Rollbar::Ignore.new(ex.message)
    end
```

**Comment by scottgratton** [comment]
Hey adding to this answer since I have found a good way to handle this type of thing in our application. If you are using Sidekiq Enterprise, you can utilize the Sidekiq::Overlimit error functionality to quietly retry a job (by default 20 times) before it raises noisily. I'd prefer not to ignore errors in my error handling application when possible and I would definitely want to know if for some reason the job continues to get the same error after 20 retries. For that reason, I added an error class inside the sidekiq initializer called `Sidekiq::SoftRetry` and then added it to the `config.errors` so it behaves like an Overlimit error (not actually sure where the documentation is for that). 


```
# in my sidekiq initializer

module Sidekiq
  class SoftRetry < RuntimeError
  end
end

Sidekiq::Limiter.configure do |config|
  config.errors.concat(
    [
      Sidekiq::SoftRetry,
    ]
  )
end
```

Then when necessary, I'll rescue the intermittent API error in my job and then raise the `Sidekiq::SoftRetry` error. Works like a charm!
```
      rescue RestClient::RequestTimeout => e
        raise Sidekiq::SoftRetry.new(e.inspect)
```

**Comment by CoderMiguel** [comment]
Because this problem is not Sidekiq Enterprise or Rollbar specific, I would like to add my solution, that wound up being very similar to @scottgratton's, but found it after the fact. I have renamed thing to have it fall in line with that answer

I am using Honeybadger, so we exclude the custom error this way:
```ruby
Honeybadger.configure do |config|
  config.exceptions.ignore += [SoftRetry]
end
```

I implemented my custom error differently:
```ruby
class SoftRetry < StandardError # RuntimeError is fine too
  def initialize(error:)
    raise error unless method_to_throw_original_error_or_shush_it
    super()
  end
  
  private
  
  def method_to_throw_original_error_or_shush_it
     # this part is up to you
     # My custom error trips on hitting a threshold limit of retries.
  end
end
```  

This way I can implement the Custom Error while still throwing the original error and the logic for that is contained in the custom error class, instead of peppered throughout my error handling.  Your needs may be different and handling that in the rescue block may be more appropriate for your needs
```ruby
class SomeJob
  def perform
     # some job logic that intermittently throws an error
   rescue WhinyError => e
      raise SoftError.new(error:  e) 
   rescue OnceADayError => e
      raise shush? ? SoftError :  e     
   end
   
   private
   
   def shush?
      # handle the error for your job uniquely instead of in the SoftError Class
   end
end
```
![shusher](https://i.makeagif.com/media/12-09-2015/rAdr1B.gif)

**Comment by gdubicki** [comment]
If your error handling service is Sentry, you should look into https://docs.sentry.io/platforms/ruby/configuration/integration_options/#sentry-sidekiq
