### ISSUE TITLE
Sidekiq periodic worker manager scheduling and executing jobs out of schedule

### ISSUE THREAD

**Issue by andrejbl** [mperham/sidekiq#3974]
We have encountered an issue where a Sidekiq periodic worker manager/cluster leader is scheduling jobs with outdated timestamps that have already been enqueued and processed at those times, causing them to be re-executed:

![image](https://user-images.githubusercontent.com/36857192/45830457-10394c00-bcf5-11e8-88db-a2d0e9360edb.png)

![image](https://user-images.githubusercontent.com/36857192/45830728-a3728180-bcf5-11e8-8eed-3b46eedcf9fe.png)

This caused a full re-run of all our Sidekiq worker jobs at a time when they were not scheduled for:

<img width="1003" alt="screen shot 2018-09-20 at 16 50 33" src="https://user-images.githubusercontent.com/36857192/45830773-b7b67e80-bcf5-11e8-8bac-a8ae450ee6e6.png">

Looking at leader election in our cluster, we are seeing what appear to be some anomalies happening during that time frame, specifically, there doesn't seem to be a reported leader for the cluster during portions of the time frame, with some leaders reporting stepping down twice:

![image](https://user-images.githubusercontent.com/36857192/45831095-66f35580-bcf6-11e8-874c-d7807e10898a.png)

Ruby version: 2.4.4
Sidekiq / Pro / Enterprise version(s): Pro - 3.5.4; Enterprise - 1.5.4

Please include your initializer and any error message with the full backtrace.
Initializer code: https://gist.github.com/andrejbl/231ffd4bf55af2cf631aa103656a05d4 and https://gist.github.com/andrejbl/1ff61d52e8930a6fb7cb11d3c3f2d245
 
Error code/backtrace not applicable.

Are you using an old version? Yes 
Have you checked the changelogs to see if your issue has been fixed in a later version? Yes

https://github.com/mperham/sidekiq/blob/master/Changes.md
https://github.com/mperham/sidekiq/blob/master/Pro-Changes.md
https://github.com/mperham/sidekiq/blob/master/Ent-Changes.md

**Comment by andrejbl** [comment]
That would be our first guess, but we did not have any deployments during that time on either the delete-request-workers or longrunningworkers instances that were acting as leaders. 

Would you say this is an attempt by a leader to restart the jobs? We are confused by the timestamps - some of them reach back to two days ago, and other leaders have already scheduled these jobs before (every one of our sidekiq jobs actually got scheduled with a past timestamp at the time this occured). These specific jobs are not long running (the name of the instance is a bit confusing, it is not related to the issue).

**Comment by mperham** [comment]
I think I have an idea of what might be wrong.  On leadership change, the next occurrence timestamp of the job can be out of date.  The execution after that should be fine.  Does that describe what you are seeing: one set of out-of-date timestamps and then normal timestamps?

**Comment by mperham** [comment]
I think this issue only occurs on leaders who have previously been a leader, stepped down somehow and then regained leadership later.  I'm guessing that process 4ab6 was the leader two days ago when those out-of-date timestamps were current.  Do you know why your leadership was flapping a lot during that window?  Redis or network connectivity issues?

**Comment by andrejbl** [comment]
That exactly describes the issue. Our leadership flaps a lot. I believe in general it is due to us having a large number (dozens) of sidekiq worker fleets which are all allowed to participate in the election. We are thinking of reducing that to a smaller number of possible leaders. Would you think that might solve the issue?

**Comment by austinhalpin** [comment]
👋 I'm one of @andrejbl's colleagues & taking a look into this issue this week.

You're correct, all of our sidekiq processes share the same Redis & we are operating with a monolith. The sharding approach definitely will work, but due to the sheer amount of Sidekiq fleets we have, it would take significant time to implement (that doesn't mean we shouldn't do it at some point!) & we're keen not to do it in a hurry.

I started looking at our sidekiq initializer and had a question. 

We do this:
```
def register_workers(config)
    config.periodic do |cfg|
      WORKERS_DEFINITIONS.each { |worker| cfg.register(*worker) }
    end
end
``` 

Where WORKERS_DEFINITIONS is just an array of our cron syntax. Is a process eligible to become the leader if they don't run the `config.periodic` block? I'm wondering if we could have something along the lines of:
```
Sidekiq.configure_server do |config|
  register_workers(config) if ENV["LEADERSHIP_FLEET"]
end
```

The aim being that less processes would be eligible to become a leader & improve the situation somewhat!

**Comment by mperham** [comment]
I would prefer not to allow an escape hatch for leadership (e.g. follower only mode).  If you shut down all potential leaders, the cluster would be leaderless.  It's a footgun.

What versions of the gems are you using?

As far as I can tell, the code has a rare race condition.  When a process becomes leader, it fires the on(:leader) callback.  The periodic subsystem uses this to reset the job state according to when the jobs need to run next.  But the periodic thread is running concurrently, checks to see it is now leader and fires off the jobs.  If the job state is not reset before the jobs are fired off this tick, it will use the old job state with the old times.  This only happens if the process was previously a leader and has old job data, which your leadership flapping makes much more likely.  I'm thinking how to fix this...

**Comment by austinhalpin** [comment]
Yep, totally understand that it's not the most graceful solution. However, we have one ec2 autoscaling group processing all of the periodic jobs' queues, which is where it might make sense to pin the leadership to - as if all of these machines are shutdown then even if a leader enqueues a job it can't be processed!

This isn't a permanent fix but could kick the can down the road somewhat.

We're running `sidekiq (5.0.5)` & `sidekiq-ent (1.5.4)`

Appreciate the prompt back and forth btw! 🙂

**Comment by mperham** [comment]
Sure, I understand you feel you could use it safely.  I'm thinking of all customers, most of which are not as savvy as Intercom.

I believe I can fix the race condition, just give me time to think through it.

**Comment by mperham** [comment]
Ok, the data structure in question is now nil'd upon losing leadership.  If leadership is regained, the structure is rebuilt before firing jobs.

**Comment by austinhalpin** [comment]
Great, thanks!
