### ISSUE TITLE
Requeue jobs

### ISSUE THREAD

**Issue by kapso** [mperham/sidekiq#3975]
Is there a way to requeue currently running jobs. So basically something like `Sidekiq.current_job.requeue`

Calling `SomeWorker.perform_async(...)` again is not always the cleanest option, since the job business logic is contained outside *Worker classes, and does not have any visibility into parameters passed into the worker.

Our specific use is calling external APIs with is throwing `429` (api limit) and we would love the ability to `Sidekiq.current_job.requeue_in(2.minutes)`. I can always throw an exception, but then Sidekiq and our error notification system becomes too noise with errors.

**Comment by mperham** [comment]
I don't know if you are an Enterprise customer but the Rate Limiting feature has support for custom errors which trigger job backoff, it would handle this for you automatically.

https://github.com/mperham/sidekiq/wiki/Ent-Rate-Limiting#custom-errors

There is no easy API for a job to requeue itself.  This is by design in order to keep concerns about how and when a job is enqueued separate from the job itself.

**Comment by kapso** [comment]
We are not on enterprise version, also we have other requeue use cases apart from 429 errors.

So in the enterprise version, all I would need to do is `raise SomeLib::SlowDownPlease` and that will requeue the job without showing up as an exception in Sidekiq?

Perhaps you could stuff the current job context in the current thread, which is then available via a Sidekiq API anywhere in the current job execution context, but I am guessing this is easier said than done :) Also I understand why this may not be an easy design decision.

Thanks for the quick response.

**Comment by mperham** [comment]
Yes, raise and it will linear back off, as the page explains.

The middleware API has the capabilities you need, which is what Enterprise uses.
