### ISSUE TITLE
How many rate limiters are too many?

### ISSUE THREAD

**Issue by dhempy** [mperham/sidekiq#3981]
Ruby version:
sidekiq-ent (1.5.4)

We use Sidekiq::Limiter.concurrent() to good effect in several places. I'm about to implement a single-concurrency worker to ensure no duplicates get imported into a system in a race. (Detecting duplicates is complicated and cannot be implemented in the database). I started out with:

      Sidekiq::Limiter.concurrent('Importer', 1, wait_timeout: 0, lock_timeout: 60)

This is fine, except we're importing a LOT of records, and I'd like to take advantage of the many servers in our farm to process non-duplicate candidates. 

There are a dozen fields that contribute to uniqueness with some fuzzy matches. However, there is a key, "purchase_order_id" which distinguishes 99.9% of the records coming in at any one time. So, what I'd like to do is put that in the Limiter name, similar to the Stripe user example in the Sidekiq docs: 

      Sidekiq::Limiter.concurrent("Importer-#{purchase_order_id}, 1, wait_timeout: 0, lock_timeout: 60)

So, my question is...how many is too many? If we had thousands of these simultaneously processing, would that cause any problem?

If we churned through millions per hour, would that gum up Redis over time?

If either of those are issues, do you have a recommended threshhold?

**Comment by mperham** [comment]
I'm unsure as I don't have a lot of data on limiter scale.

There's a few things you can do to minimize risk:

1. Use a separate Redis instance for limiters.
2. Don't visit the Limiter page in the Web UI or things will go badly. I don't believe it implements paging.
3. Set the TTL to aggressively expire unused rate limiters: `ttl: 24.hours`

I would think you can use 1000s of limiters simultaneously.  I would try it in staging and let me know what you learn about scale.  Heavy usage will not gum anything up over time.

**Comment by dhempy** [comment]
Thanks, Mike. I missed the TTL option. I'll use `ttl: 1.day`, for sure. 

On further thought, I think we're going to use the last 3 digits of the ID for the rate limiter name, to avoid races between potentially matching records. We're only looking to improve parallelism -- not implement guaranteed uniqueness via the rate limiter.  This approach should give us both. 

If we generate any interesting data, I'll share it with you.

**Comment by raivil** [comment]
Hey,

Do you have more data on this issue? 
I'm facing a similar situation where the exclusive rate limiter Redis instance it almost using all the memory. 
App uses concurrent limiter of size 1 to make a distributed mutexes.

We're considering reducing some of the locks TTL to less than `24.hours` but before doing that I'd like to understand why it's not recommended to go below 24 hours, as written on https://github.com/mperham/sidekiq/wiki/Ent-Rate-Limiting#ttl

thanks.

**Comment by mperham** [comment]
I would wonder why you are running out of memory on Redis. You must be running a very small Redis instance or making many, many millions of limiters.

I recommend 24 hours because it should never, ever go lower than the max amount of time that the limiter might be held.  If you have a long-running job which takes the limiter, it might be held for hours.  If your jobs only hold the limiter for seconds or minutes, you can drop the TTL to a few hours.

**Comment by locofocos** [comment]
Thanks for the info. I came here from a search after reading https://github.com/mperham/sidekiq/wiki/Ent-Rate-Limiting#ttl which recommended 24 hours.

Just as another example, we're doing exactly what you mentioned- running millions of limiters 😆  We have a multi-tenant ecommerce software that uses a concurrent limiter. We use a limiter name based on the full product ID, I think to avoid concurrent updates for that product in other systems. Over the past 90 days, we've used Sidekiq::Limiter.concurrent for about 3.8 million records. Because sidekiq is generating redis keys for both `lmtr-c-whatever` and `lmtr-cfree` for each limiter, that put us at over 7 million redis keys!

As someone a little new to sidekiq, it took me a while to figure out where the redis keys were coming from. One thing that would have helped me figure this out sooner: if there was sidekiq documentation to the effect of
> If your redis instance is using too much memory / has to many keys, use an rdb analyzer to grab the unique keys. If you see key names like `lmtr-cfree-asdf` and `lmtr-c-asdf`, those are created when you call `Sidekiq::Limiter.concurrent('asdf', ...)`. 

Thanks again for the tips!

**Comment by mperham** [comment]
@locofocos The wiki is publicly editable. This is great content that you are welcome to add to the page. 😎

**Comment by karlhe** [comment]
> I recommend 24 hours because it should never, ever go lower than the max amount of time that the limiter might be held. If you have a long-running job which takes the limiter, it might be held for hours. If your jobs only hold the limiter for seconds or minutes, you can drop the TTL to a few hours.

Would you mind on how the TTL works?

e.g. if I have 10 jobs using the same dynamically created limiter with a TTL of 5 minutes, and each runs sequentially for 1 minute each, what would I expect to happen?

1. The TTL gets refreshed to 5 minutes as each job is run
2. The limiter expires after the 5th job, then gets re-created with the 6th job
3. Something bad happens (?)

**Comment by mperham** [comment]
It would be (3). Right now the concurrent limiter uses four structures in Redis but only refreshes the TTL of one structure every time you use the limiter. The other three structures retain the initial TTL and will disappear after five minutes.

The TTL is guaranteed from the time the limiter is created. If you set the TTL for 5 minutes, that limiter instance is only guaranteed good for 5 minutes. If each job is calling `Sidekiq::Limiter.concurrent` inside the job, that creates a new instance and all should be well since each job only holds it for one minute. If each job references a limiter constant that is created on boot, you'll have a bad time.

```ruby
LIMITER = Sidekiq::Limiter.concurrent("name", 10, ttl: 300) # bad idea
```

**Comment by meagar** [comment]
Apologies for the very broad question, but I'm wondering if this constitutes an abuse of limiters:

If the goal is to make sure a given job cannot run concurrently for the same database record (not to rate-limit some downstream API, but to help facilitate idempotency), given the choice between a `Sidekiq::Limiter` with a concurrency of 1 (the distributed mutex use case) or database-level locking when there exists a record we can lock `FOR UPDATE`, which would you steer people towards?

For example, a contrived job that syncs users with some 3rd party API, but shouldn't run twice:

```
# limiters
def perform(user_id)
  user = User.find(user_id)
  return if user.last_sync > user.updated_at # already up-to-date, no sync required

  Sidekiq::Limiter.new("user_sync_{user.id}", concurrency: 1).within_limit do
    user.sync_to_3rd_party_service!
    user.update!(last_sync: Time.now)
  endk
end
```
# 

```
# locks
def perform(id)
  User.transaction do
    user = User.lock.find_by(id) # SELECT ... FOR UPDATE
    return if user.last_sync > user.updated_at # already up-to-date, no sync required
    user.sync_to_3rd_party_service!
    user.update!(last_sync: Time.now)
  end
end
```

Is this kind of unbounded creation of limiters a good idea? We'll eventually have millions, one for each user for each job using this pattern.

**Comment by mperham** [comment]
Without more context, I would prefer row-level database locks over rate limiters as they are more scoped to exactly what you are trying to achieve: a mutex on that record.
