### ISSUE TITLE
Slow queries through Sidekiq

### ISSUE THREAD

**Issue by sarmiena** [mperham/sidekiq#3991]
Ruby version: 2.1.1
Sidekiq / Pro / Enterprise version(s):
Sidekiq 3.4.2
Rails version: 4.0
Concurrency: 90
Machine: Ubuntu 18.04 / 32GB ram / Intel Optane p4800x 750GB
DB: PostgreSQL 9.4

Queries from within Sidekiq are considerably slower. We are using ActiveSupport::Notifications to log queries, and within Sidekiq simple queries that take ~1ms in console take 5-7 seconds through sidekiq.

We are opening up console via rails c on the same machine sidekiq is running on, and those are the ones that also run lightning fast. If we write the query for sidekiq to execute, we get the huge delays.

Is this a Global Interpreter Lock problem with high concurrency?

**Comment by mperham** [comment]
Yes, that concurrency is WAY too high. Don’t go more than the default, 25.

Your Sidekiq version is very old. Please upgrade.

**Comment by sarmiena** [comment]
I see. Is this a common issue (slow ruby execution) with high concurrency?

Also, could we launch 5 instances of Sidekiq with 25 each? 

Lastly, we're a little stuck on Rails 4.0... which is why we haven't upgraded Sidekiq.

**Comment by mperham** [comment]
Yes.  If you have 90 things running, each will get 1% of the CPU, max.  MRI doesn't use multiple cores.

Yes, you can spin up as many processes as you want.  That's why you want multiple Sidekiq processes, to use all cores.  Sidekiq Enterprise's multi-process feature will do this automatically for you.

Sidekiq 4.2.10 supports Rails 3.2.  Sidekiq is not preventing you from upgrading, likely another gem or plugin.
