### ISSUE TITLE
Halting from a middleware

### ISSUE THREAD

**Issue by dsantosmerino** [mperham/sidekiq#4027]
**Ruby: 2.4.4
Sidekiq Pro: 3.5.3**

We are currently exploring the way to set our entire system in **maintenance mode**. For the API we are using the Rack Middleware approach, so we thought that we could achieve something similar for Sidekiq.

The last goal is to be able to **stop processing workers** while we have enabled this maintenance mode, but not increasing the error rate, or the retries count.

We have already checked this [issue on StackOverflow](https://stackoverflow.com/questions/39780767/sidekiq-delete-or-kill-job-inside-a-middleware?rq=1) that you mention in the [Wiki](https://github.com/mperham/sidekiq/wiki/Middleware), and we are trying with something like this:
```ruby
module Middleware
  class MaintenanceMode
    def call(*_args)
      return if maintenance_mode?

      yield
    end
  end
end
```

The issue here is that the code above doesn't halt the worker process.
Do you have any idea of how we can get our goal?

**Comment by mperham** [comment]
The only way to get Sidekiq to stop completely is to shut down the worker processes.  Since Sidekiq jobs are async by nature, this is reasonable to do in a maintenance situation.

One alternative: Sidekiq Pro offers an API to pause a queue.  You can pause all queues, which will stop all job execution:

```ruby
Sidekiq::Queue.all.each(&:pause!)
```

But various features will still keep working with Redis in the background, e.g. scheduled jobs and retries will be enqueued, cron jobs enqueued, etc.

**Comment by dsantosmerino** [comment]
Hey @mperham, thanks for your fast reply. The first alternative it's maybe the best one, but our concern is that we'd like to do it dynamically with this method that says if we are in a maintenance frame. Otherwise, in multi-instance environments, we should access all the instances and stop Sidekiq completely.

The second alternative could work as well, but we have some queues that are not always active. We have some scheduled workers stoping them in specific timeframes; We think that it could be hard then the unpause action.

Do you have any suggestion here?

Thank you again!

**Comment by dsantosmerino** [comment]
It looks perfect to starting the maintenance mode, but there is an option to restart them again with the same API?

Thanks!

**Comment by mperham** [comment]
Nope, you'd need to use whatever deploy tool you use to start Sidekiq again.

**Comment by dsantosmerino** [comment]
I'm wondering if this `pause` action it's something achievable from the `Sidekiq::ProcessSet API`. I know that is not implemented right now, but do you think that is something that we can implement?  Does it make sense?

**Comment by dsantosmerino** [comment]
I mean, kind of pause than then we can reactivate again. Is it something that could make sense to implement? We can take a look if you think that is something useful.

**Comment by mperham** [comment]
That would add a level of complexity I don't want, especially since no one else is asking for anything similar.  If you are in maint mode, it's dangerous for any components of your app to be running.  What if you want to maint the DB or Redis?  How does Sidekiq work then?  I'd like to hear a better defined use case and its pros/cons because this is not a trivial change.
