### ISSUE TITLE
Support to push bulk with different delays?

### ISSUE THREAD

**Issue by dsantosmerino** [mperham/sidekiq#4096]
**Ruby version: 2.5.3
Sidekiq PRO: 3.5.3**

We are currently exploring the way to improve performance when **creating huge batches**. We are using the **push bulk approach** suggested in the [wiki](https://github.com/mperham/sidekiq/wiki/Batches#huge-batches), but we'd like to distribute those single workers in a specific timeframe.

It's something that we are already doing with the old approach of calling our Redis for every single worker, and we'd like to use the same approach even we are calling the Redis once. Is it something that the current push bulk API permits? We've found something similar [here](https://github.com/mperham/sidekiq/blob/ddb0c8b3a876087ceed65df1c58d749e3a30725f/test/test_api.rb#L321-L323), but it looks like it's scheduling all of them at the same time.

Thanks!

**Comment by mperham** [comment]
push_bulk only supports variants based on args.  It can't vary based on schedule because that would require us to adjust where each payload is going and call a different command (LPUSH vs ZADD). I think it is theoretically possible to add `push_bulk_at` and support varying schedules but there's been little demand for it so far.
