### ISSUE TITLE
Feature request for enterprise unique jobs

### ISSUE THREAD

**Issue by 97jaz** [mperham/sidekiq#4164]
Ruby version: 2.5.1
Sidekiq / Pro / Enterprise version(s): Sidekiq 5.2.5 / Pro 4.0.5 / Ent 1.8.1

Before we purchased Sidekiq Enterprise, we were (and at this moment still are) using the 3rd party unique jobs plugin.

I'd like to use the unique jobs functionality in Sidekiq Enterprise, but it turns out that we depend on the 3rd party library's `unique: :until_and_while_executing` option -- which is not the same thing as Enterprise's default `unique_until: :success`. 

Specifically, it uses two different locks: one prevents duplicate jobs from being on the queue at the same time; the other prevents them from executing at the same time. I think this is the same issue that @mperham was musing about [here](https://github.com/mperham/sidekiq/issues/3471#issuecomment-302217397) while considering `unique_until: :start` -- namely, the fact that the latter allows duplicates to execute at the same time. This wasn't a problem for the user who reported that issue, but it is for us.

Our case is similar to the one reported in that issue, except that if our dups execute concurrently they interfere with one another.

**Comment by mperham** [comment]
You can use `unique_until: :start` and a concurrent rate limiter of 1 as an execution Mutex.

**Comment by 97jaz** [comment]
Ah -- I was unaware of this feature. Thank you very much. I think this is exactly what we need.

**Comment by mperham** [comment]
Great. The Enterprise features are listed right here, I bet you'll learn a lot reviewing these pages: https://github.com/mperham/sidekiq/wiki#sidekiq-enterprise  😎

**Comment by J-Swift** [comment]
Sorry for necrobumping this @mperham but it was exactly what I was thinking through and wanted clarification on this. I originally came to the same conclusion as you recommend to replace `until_and_while_executing` but then thought it wouldnt work because by the time the limiter is being checked, we have already started the job and thus released the uniqueness lock. Is that not accurate? Am I missing some nuance with how these subsystems work that would allow them which Im not seeing?

```
  class MyWorker
    include Sidekiq::Worker

    sidekiq_options unique_until: :start

    LIMITER = Sidekiq::Limiter.concurrent(:my_limiter, 1)

    def perform(id)
      LIMITER.within_limit do
        # ... do work ...
      end
    end
  end
```

**Comment by mperham** [comment]
@J-Swift Yes, once the lock is released at :start, another job can be enqueued and started but the jobs can't execute that block at the same time due to the Limiter.

**Comment by J-Swift** [comment]
@mperham right so the scenario Im thinking is:

- job A starts, unique lock released
- job A acquires limiter
- job B scheduled, unique lock acquired
- job B starts, unique lock released
- job B fails to acquire limiter so raises over limit
- now what?

Does job B now fight for the unique ness lock? Does it ignore uniqueness lock now thats going into the scheduled set? This is the part that breaks down in my mental model and what I was hoping to understand better, especially as a hypothetical job C tries to get added to the queue while B is in over limit

**Comment by mperham** [comment]
I think you're understanding everything correctly. The unique lock serves to prevent duplicate job creation as long as that lock exists. Once the job A executes and the lock is removed on :start, another duplicate job B can be created. Job A could fail and will continue to exist and execute during any retry period, possibly concurrently with Job B. The default uniqueness strategy, :success, avoids this.

Like the docs say, uniqueness should be considered best effort. It is not a replacement for a true Mutex or concurrency limiter. The concurrent rate limiter is a much stronger guarantee that a block of Ruby code will execute exclusively.

**Comment by J-Swift** [comment]
Understood, thanks for the follow up. i think its useful to get this documented here for future me to find again too : D

I do think theres a space for something closer to the `until_and_while_executing` semantics. Im not sure if their implementation is _actually_ a stronger guarantee or not, but I think my usecase is fairly common:

We have essentially a periodic job that finds all records marked as dirty and runs an update task to regenerate statistics on the current state. We use the mark/sweep strategy because 1) during busy periods we can thrash pretty hard on a single items updates and 2) it can sometimes be an expensive update

So that means if a job is currently running, then we want to schedule a new one to run "sometime" after the current, because its queries are not necessarily going to be fully up to date now. But we ~dont~ do want to ignore pending updates if one is already there because like I said, it can thrash pretty hard at times.

The suggested solution is ok but not great. Good enough for this / for now at least. But if you can think of a way to provide a stronger "one running + one pending" semantic then I think theres value in that.

**Comment by mperham** [comment]
I try to provide as many useful tools as possible but there will always be drawbacks and I always have to consider scalability and safety. It may be that background jobs aren’t the right tool for this need or you need to rethink your implementation at a higher level.
