### ISSUE TITLE
Sidekiq Batch memory consumption before flushing to redis

### ISSUE THREAD

**Issue by rperryng** [mperham/sidekiq#4202]
Ruby version: 2.5.3
Sidekiq / Pro / Enterprise version(s): 5.2.7 / 4.0.5 / 1.8.1

We have a workflow in which we read a CSV file from S3 (which could be as large as 80MB sometimes) and enqueue a Sidekiq job for each row.

We use the `SmarterCSV` gem along with its `chunk`ing feature in order to read X number of rows at a time to avoid loading the entire file in memory.

We recently introduced adding all these jobs to a single Sidekiq batch so we can see when all the jobs for a given CSV file have completed.  This workflow looks something like

```ruby
s3_response = S3_CLIENT.get_object(bucket: bucket, key: key)

batch = Sidekiq::Batch.new
batch.on(:success, SomeClass, { bucket: bucket, key: key })
batch.jobs do
  SmarterCSV.process(s3_response.body, { chunk_size: CSV_CHUNK_SIZE }) do |rows|
    rows.each do |row|
      job_args = convert_to_job_args(rows)
      SomeWorker.perform_async(job_args)
    end
  end
end
```

When we perform this workflow with large CSV files (last night ~40MB) the container responsible for running the code above would run out of memory (~512MB limit).  I'm assuming the Sidekiq is storing all these job arguments in memory before flushing to redis at the end of the `Sidekiq::Batch#jobs` block.  What would be the recommended approach to avoid this scenario?  I've considered creating a batch for each csv chunk but that would somewhat defeat the purpose of why we introduced batches in the first place: to identify when all the jobs related to the CSV have completed.

Thanks in advance!

**Comment by mperham** [comment]
It looks like you are doing everything right.  The quick and easy answer is to upgrade your dynos to 1GB.  As an Enterprise customer, I assume you are a professional with a budget. 😎

The harder answer is to optimize your app's memory usage more.  The Batch code can't flush the jobs early, as that creates a big race condition.  If you find any memory optimizations for Sidekiq::Client and those 80k jobs sitting in memory, I'd be happy to hear them but I'm not aware of any quick optimizations in that regard.

**Comment by rperryng** [comment]
Thank you, just wanted to make sure we weren't missing anything obvious before reaching for the money gun. 🙇

**Comment by chadrschroeder** [comment]
I wanted to add a note here in case anyone else who runs into this.  If the file or dataset you're working with is very large, the memory use in your Ruby process can increase to several GBs while the `batch.jobs` code block is in progress.  To avoid this, you can follow the suggestion for [Huge Batches](https://github.com/mperham/sidekiq/wiki/Batches#huge-batches) which is to start a batch, enqueue a Loader job (or set of jobs), and then let the Loader enqueue additional work into the batch in smaller chunks.  You may want a way to track what these Loader jobs are doing so that you can deal with any unexpected crashes.

You'll still need enough space in Redis to be able to hold everything you are enqueuing.  But using the huge batches approach avoids the Ruby memory issue and allows you to have lots of moderately-sized worker boxes and one large Redis box.
