### ISSUE TITLE
Support for Multi-Tenant Queueing

### ISSUE THREAD

**Issue by jcarlson** [mperham/sidekiq#4208]
My Sidekiq implementation processes jobs for a multi-tenant system. Some customers in this system are larger, and therefore create more jobs, than others.

It would be great if Sidekiq offered a way to give each tenant an equal opportunity at getting their jobs processed. For example, if Customer A has 1,000 pending jobs, and Customer B has only 10 pending jobs, then Customer B should not have to wait for all 1,000 jobs belonging to Customer A to finish.

Ideally, in the above scenario, there are 1,010 jobs in total to process. The first 20 jobs pulled off the queue should be an equal split between Customer A (10 jobs) and Customer B (10 jobs). This gives each customer an equal share of the available Sidekiq resources to get jobs done. After the initial 20, since Customer B has no remaining jobs, Customer A may utilize all available resources to complete the remaining 990 jobs. However, if Customer B creates additional jobs before Customer A has finished, then the system would return to an "equal share" mode.

As noted in the documentation, neither a "queue per customer" nor a "worker per customer" solution would be appropriate, as both solutions are difficult to scale.

**Comment by mperham** [comment]
Here's some thoughts.  The best impl I can think of today:

1. Add an API to push a "customer" job or use a client middleware to dynamically reroute customer jobs.  This will push the job to a queue per customer.
2. Occasionally scan Redis (e.g. SCAN "queue:customer:*" every 10 seconds) for the existing set of customer queues.
3. loop { Pick a random queue, pop and perform job }

A big issue is how to integrate this with the rest of Sidekiq and its existing means of processing jobs.  I wonder if you could implement this with a client middleware + custom fetch implementation.  You'd have to dedicate special Sidekiq processes for customer processing.

**Comment by jcarlson** [comment]
Custom middleware and a fetch strategy was exactly the route I was thinking. I think the trick is, for the middleware, to re-route the customer job into a customer-specific queue, and then place a “marker” job on the regular queues. Then, during fetch, if a “marker” job is fetched, then before the fetch completes, it should fetch a job from a a customer-specific queue.

That allows Sidekiq to pull customer jobs from the queue based on available work process capacity, but when a customer job is pulled, we have an opportunity to select a specific customer at random from those waiting for a job to be processed.

I have a little time ahead of me before I can start implementing something, so I will noodle on it a little more, perhaps document a more detailed process flow and see what you think.

**Comment by epchris** [comment]
@jcarlson Have you had any chance to think about this more? I don't know the Sidekiq source that well, but I'm also very interested in this capability!

**Comment by epchris** [comment]
This thought is half baked:
1. Every time you queue a tenanted job, you include the tenant ID via client middleware.  You also increment, via `HINCRBY`, something to track the number of jobs queued for that tenant in that queue.
1. Via server middleware, whenever you are about to process a potential job: if it has a tenant ID on it, gather two pieces of data:

    2. Number of workers servicing each tenant
    2. How many tenants have jobs queued (via HGETALL on the hash to store queued job counts)

1. With those two pieces of info:

    2. *IF* `total number of workers working for this job's tenant` is the lowest (or tied for lowest)  among all tenants _with queued jobs_, *THEN* increment workers for tenant (via `HINCRBY`) and do the job
    2. *IF NOT*, *THEN* requeue the job at "some later time interval" and don't do any work

1. When a job is worked (via server middleware) decrement the number of jobs queued for that tenant, via `HINCRBY -1`


Remaining questions:

- How does the number of tenants affect this approach?
- How do we clean up the hashes that we increment/decrement when they get to 0?

@mperham @jcarlson 

1. When job is done (via server middleware) decrement (via `HINCRBY -1`) the `total number of workers working for tenant`

**Comment by mperham** [comment]
This is my latest thinking on the subject.  WDYT?

https://www.mikeperham.com/2019/12/17/workload-isolation-with-queue-sharding/

**Comment by epchris** [comment]
Hi Mike!
Thanks for writing this up, it has been very helpful!  I'm just writing
back now because we're finally getting close to shipping our first worker
(hopefully one of many to come).  One idea occurred to me: what if we had
all workers listen to all shards with a weight of 1?  This seems to mean to
me that we would never have idle workers and that workers would randomly
select from a shard to pull from when getting the next jobs, more or less
balancing the work done.

Does this make sense?

Thanks,
Chris

**Comment by gearnode** [comment]
Maybe you can discuss with @wittydeveloper, he have done this work at Algolia

**Comment by epchris** [comment]
> Maybe you can discuss with @wittydeveloper, he have done this work at Algolia

I would love to hear from @wittydeveloper, maybe mentioning his name again will get him here faster ;-)

**Comment by wittydeveloper** [comment]
Hi guys,

I am currently getting confirmation from Algolia of which levels of details I can communicate this design 

I'll come back to you soon!

**Comment by mperham** [comment]
As there's no right answer or conclusion here, I'm closing this; I don't want a nebulous issue here in the backlog. Please open a new issue if you find something that works or have implementation changes to discuss.

**Comment by jasonperrone** [comment]
@mperham I know this issue is closed and that's fine, this isn't the issue I am having. I just thought it would be a good place for me to ask about a much simpler multi-tenancy scenario and how I would implement it. 

The scenario is merely that I have 100 databases spread across 3 Rails environments: qa, stage and production. Within each environment, like production for example, I have many databases. So in the production environment, I have 50 clients each with a separate database.

My desire is:
1. I want a separate Sidekiq process for each Rails environment (qa, stage, production).
2. I want to be able to send a job to the correct Sidekiq process depending on which Rails environment is scheduling the job.
3. I want to use Sidekiq cron to schedule my jobs for each of my 50 clients
4. I want my ActiveJob to run on a given client database


After researching for a while this is what I think I need to do:
1. Start each Sidekiq process with one queue named after the Rails Env, like bundle exec sidekiq -q production -e production
2. When scheduling the job with Sidekiq cron, provide the queue named after my environment and in the args (which will be passed to the perform method of my ActiveJob) provide an argument which is the name of a db connection.
3. In my ActiveJob, simply use ActiveRecord connection switching with ActiveRecord::Base.establish_connection to run my job on the correct database based on the parameter passed in from Sidekiq cron.

I see a lot of people here are in multi-tenant situations so I am hoping to get thoughts and advice on the topic. Is what I plan to do best practice or am I way off base?

Thanks!
