### ISSUE TITLE
Dead batches are not always cleaned in redis

### ISSUE THREAD

**Issue by dnorth98** [mperham/sidekiq#4217]
Ruby version: 2.6.3
Sidekiq Pro /  version(s): 4.0.5

Found while emailing with Mike/Support about the cleanup time for batches.  The issue is:

> If last dead job in a dead batch is run successfully, the dead batch callbacks fire but they do not clean up the "died" set in Redis.  This set can be large and takes 6 months to expire

Dead batches expire on the same frequency as dead jobs which is 180 days.  The issue above is that a batch should be purged from Redis if the final job is successful...but they are not it seems.

**Comment by mperham** [comment]
Thanks for the report, this structure is now deleted when the success callback for the batch runs.  If the batch never succeeds, it will expire after six months.

Unfortunately this is a lot of overhead because this set may contain a large amount of job data; I want to fix this.  If your batch dies and has 1000 dead jobs, the structure will contain a full copy of all 1000 jobs. 🤦🏻‍♂️

Sidekiq Pro 4.0.0+ provides an API,` Sidekiq::Batch::Status#dead_jobs`, which returned the full copy of the jobs that had died in the batch.  Storing a copy of this data for easy access entails significant memory overhead, especially those with large jobs (e.g. big arguments), and (due to this bug) was never removed until the batch expired.

4.1.0 will remove this API and instead provide `dead_jids`, which returns the JID for each dead job, meaning much more efficient storage.  The DeadSet contains the canonical copy of the job and can be scanned for the job with that JID using 'sidekiq/api'.
