### ISSUE TITLE
Sidekiq 6.0 fails with rails_semantic_logger

### ISSUE THREAD

**Issue by MisterFine1** [mperham/sidekiq#4239]
Ruby version:
Sidekiq / Pro / Enterprise version(s): 6.0 with Professional

Running Rails 5.2 with rails_semantic_logger 4.4, sidekiq did not boot because rails_semantic_logger over-rode the built-in logger with semantic_logger by specifying Sidekiq::Logger -- This was fixed with the following modification to rails_semantic_logger

https://github.com/rocketjob/rails_semantic_logger/pull/95

which sets the logger explicitly to SemanticLogger:
```
Sidekiq::Logging.logger = SemanticLogger[Sidekiq]
```

However, when running sidekiq, I now receive the following error: 

```
Sidekiq -- NoMethodError: undefined method `with_context' for #<SemanticLogger::Logger:0x00007fbad91bb778>
```
It appears that sidekiq requires it's internal logger to support a new method: _with_context ?

**Comment by mperham** [comment]
Internal APIs are not documented and can change from version to version, especially with major version bumps.  `Sidekiq.logger` has existed from day one.

**Comment by mperham** [comment]
@Tensho I think one thing this issue brings up is that if the user does this, it will break Sidekiq because of the `with_context` thing:

```ruby
Sidekiq.logger = ::Logger.new(STDOUT)
```

Ideally Sidekiq's Logger will work with ::Logger.

**Comment by MisterFine1** [comment]
I get that... been a sidekiq user for many years, and a pro user for 4+.  Internal apis can chance at any time... but it is worth noting that Sidekiq is so pervasive that many other libraries have "connected" to to it, and a common use case is changing the logger for a more rich logger, as long as it meets the same API as the standard Ruby or Rails loggers.  This version adds a method that will break any other logger, I think.

**Comment by Tensho** [comment]
@mperham Just a thought, it's not a good option to extend any outter logger with the context module [**implicitly**](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq.rb#L207) because it may introduce inner (module's) and outter (3rd-party logger) methods clash. Sidekiq allows extending `JobLogger` with the custom context. What do you think if we expose context API (`with_context ` or `ctx`) in the next major version opening customization at basic `Sidekiq::Logger` level and forcing all 3rd-party loggers to conform it? I understand it's another one breaking change, but it could establish a more specific contract for other loggers. I guess extra research is required to understand the commonalities between popular 3rd-party loggers for Sidekiq to make the right decision.

**Comment by kranzky** [comment]
@MisterFine1 I'm using this workaround to the `with_context` issue:

```
Sidekiq.logger = SemanticLogger[Sidekiq]
Sidekiq.logger.class.alias_method(:with_context, :tagged)
```

**Comment by collimarco** [comment]
Related: https://github.com/mperham/sidekiq/issues/4254
