### ISSUE TITLE
Sidekiq not stopping to take new jubs during deployment even with TSTP signal

### ISSUE THREAD

**Issue by feliperaul** [mperham/sidekiq#4401]
Ruby version: 2.5.3
Sidekiq / Pro / Enterprise version(s): Sidekiq Open Source 5.2.2

At the beginning of our deploy, we issue a `sudo systemctl reload sidekiq`, which we assume should trigger the ExecReload command in the sidekiq.service file.

Ours ExecReload command is ExecReload=/bin/kill -TSTP $MAINPID

The whole file is below. 

However, we can confirm that sidekiq is not stopping to take new jobs during the deployment, and even clicking on the 'stop' button in the web interface makes the process disappear for a few seconds, but it comes right back and starts processing new jobs.

Here's ou sidekiq.service file:

```
{{ ansible_managed | comment }}

[Unit]
Description=Sidekiq
After=network.target syslog.target redis.service mysql.service
Wants=network.target syslog.target redis.service mysql.service

[Install]
WantedBy=multi-user.target

[Service]
Type=simple

WorkingDirectory=/var/www/{{ param_app_name }}/application

ExecStart=/bin/bash -lc 'cd /var/www/{{ param_app_name }}/application; /home/{{ param_user_name }}/.rbenv/shims/bundle exec sidekiq -e production -C /var/www/{{ param_app_name }}/shared/config/sidekiq.yml'

ExecReload=/bin/kill -TSTP $MAINPID

ExecStop=/bin/kill -TERM $MAINPID

User={{ param_user_name }}

Group={{ param_user_name }}

UMask=0002

RestartSec=3
Restart=always

StandardOutput=file:/var/www/{{ param_app_name }}/shared/log/sidekiq.log

SyslogIdentifier=sidekiq

Environment=MALLOC_ARENA_MAX=2
```

**Comment by mperham** [comment]
I’d guess the issue is the overly complex ExecStart line, so MAINPID is bash rather than Sidekiq? Start Sidekiq directly.

**Comment by feliperaul** [comment]
@mperham Mike, we followed the content of the example you provided in https://github.com/mperham/sidekiq/blob/master/examples/systemd/sidekiq.service

It reads:
```
# If you use rbenv:
# ExecStart=/bin/bash -lc '/home/deploy/.rbenv/shims/bundle exec sidekiq -e production'
```

This is all a little bit greek to us 😬 So the correct ExecStart would be:

```
ExecStart=/home/{{ param_user_name }}/.rbenv/shims/bundle exec sidekiq -e production -C /var/www/{{ param_app_name }}/shared/config/sidekiq.yml
```

**Comment by feliperaul** [comment]
Any idea how I can debug this?

**Comment by spaceform** [comment]
Here's one thought which may help.

The ExecStart line starts a bash shell and the bash shell starts sidekiq, and so sidekiq is likely running as a child process under the bash process.

The ExecReload line will send the TSTP signal to the $MAINPID process which is bash, but the bash process won't send this process to the sidekiq child process. Therefore the sidekiq process never gets the TSTP signal.

Perhaps you could resolve this by prefixing the bundle command with `exec`. `exec` will make the bash shell be replaced by the sidekiq process and so the $MAINPID process will be sidekiq instead of bash. e.g.:

`ExecStart=/bin/bash -lc 'cd /var/www/{{ param_app_name }}/application; exec /home/{{ param_user_name }}/.rbenv/shims/bundle exec sidekiq -e production -C /var/www/{{ param_app_name }}/shared/config/sidekiq.yml'`

Side note: The ExecReload line as is doesn't seem to actually reload sidekiq. It just sends the TSTP signal. Perhaps that's what you expect to happen but I thought I'd mention it just in case
