### ISSUE TITLE
Is there a better solution to make logrotation?

### ISSUE THREAD

**Issue by skyeagle** [mperham/sidekiq#446]
How do you make log rotation guys?

Logrotate with copytruncate loses the some data. Re-running sidekiq which was run from deploy user is not possible by logrotate scripts. I would like to store all app logs in deploy user's folder. Is there hidden supported signal to tell sidekiq to reopen logs?

 Thank you.

**Comment by nextofsearch** [comment]
@mperham I am wondering if your comment is outdated. Is it still the only way to pipe sidekiq's output to syslog if I want to logrotate logs?

> We pipe sidekiq's output to syslog with | logger -t sidekiq and let the OS rotate syslog for us.

I found a logrotate script using USR2 but I am not proficient enough to edit the logrotate script in order to make a universal script which can handle different numbers of sidekiq processes in multi environments

`
/Data/my_rails_app/shared/log/*.Log {
  daily
  missingok
  rotate 10
  size 10M
  dateext
  notifempty
  copytruncate

  compress
  delaycompress

  lastaction
    Unicorn_pid = /Data/my_rails_app/shared/tmp/pids/unicorn.Pid
     Test -S $ Unicorn_pid  Andoando  Kill -USR1 "$ (Cat $ Unicorn_pid)"

    Sidekiq_pid = /Data/my_rails_app/shared/tmp/pids/sidekiq.Pid
     Test -S $ Unicorn_pid  Andoando  Kill -USR2 "$ (Cat $ Sidekiq_pid)"
  endscript
}
`

**Comment by mperham** [comment]
@nextofsearch Use Upstart or Systemd to control Sidekiq and log rotation is automatically handled for you.  Modern versions of them both support syslog output.  I don't recommend using USR2, -L or any custom logfile code; let the OS deal with it.

**Comment by nextofsearch** [comment]
@mperham got it!
