### ISSUE TITLE
Exposing complete job hash in context for logging

### ISSUE THREAD

**Issue by erikcheung** [mperham/sidekiq#4475]
Ruby version: 6.0.5 
Pro version(s): 4.0.5

At this moment I use a custom json logging format in which I log additional data such as args, queue's etc.
This is done by a Custom formatter class that inherits from `::Sidekiq::Logger::Formatters::JSON` and by overriding `Sidekiq::JobLogger.job_hash_context`. Which works for now. However, I wonder if there is a cleaner way to fix this without the monkey patch or a fork.

**Comment by mperham** [comment]
I don't believe you don't need to override anything, just add a server middleware which does this:

```ruby
def call(worker, job, queue, &block)
  Sidekiq::Context.with("queue" => queue, "args" => job["args"], &block)
end
```

**Comment by yboulkaid** [comment]
I tried the server middleware approach, but unfortunately this doesn't work. After digging into the code, it's because the logging is started _before_ the middleware chain: 

https://github.com/mperham/sidekiq/blob/1d11ae3a01d12cc67ff6d31dc7e09143000e733b/lib/sidekiq/processor.rb#L125

In other words, the `job_logger` uses to the old context, and only the code ran in the `yield worker` inner yield gets access to the enhanced context.

Since we need to hook into the logger, @mperham, would you be open to a PR enabling the logging of job arguments, as an opt-in option? I figure I'd ask before starting to write code :)

(Sorry for bumping this issue out of the graveyard btw..)

**Comment by mperham** [comment]
No, I would not support any changes which log job args; IMO it's a bad idea. They add a lot of noise to the logs, they can be huge and they can be sensitive. If you want to log them, prepend a module which overrides `perform` and logs the args as the job starts executing, e.g.

https://stackoverflow.com/questions/23962212/wrapping-sidekiqs-perform-method-to-add-timezone-awareness

**Comment by yboulkaid** [comment]
Gotcha, thanks for the quick answer and the pointer to a solution :)
