### ISSUE TITLE
Deploy Sidekiq (crons) without downtime

### ISSUE THREAD

**Issue by DanOfir** [mperham/sidekiq#4490]
Ruby version: 2.2.6
Sidekiq / Pro / Enterprise version(s): 5.1.3 / 4.0.3 / 1.7.1

Hello,
I am facing an issue with deployments of sidekiq on Kubernetes specifically Sidekiq crons.

I am using sidekiq cron, and as mentioned in the documentation, crons being registered only on bootstrap. it is considered as a migration of data.

in k8s the default deployment procedure is rolling update, it assures no downtime during deployment. but when adding new cron to sidekiq it forces us to go to downtime in order to make new configuration to work.

Any suggestions?
Can someone share if they are doing rolling updates with sidekiq crons?

**Comment by mperham** [comment]
I just checked the code. Looks like this should happen:

0. Rolling restart kicks off.
1. Old leader goes quiet but continues to tick and push cron jobs.
2. New processes start up, do not get leadership.
3. Old leader eventually shuts down, new process gets leadership.
4. Upon leadership, the new process persists its cron jobs to Redis and starts pushing cron jobs.

Sounds like your issue is that the old leader process is taking a significant amount of time to shut down. During that shutdown period, the new code might have cron changes deployed but they will not be active until the old leader stops and a new leader is elected.

Does that sound right? I'm not sure of the right answer here but I want to make sure I understand the root issue before pondering potential solutions.

**Comment by DanOfir** [comment]
Hi @mperham, thanks for the response.

Currently, it's not my scenario. I don't have any long-running jobs, also the deployment is very quick.
but I could push new crons only when terminating all old processes.

If I understand what you wrote, when the old leader stop and a new leader takes place new crons should start working. this is not what I'm experiencing, so it might be an implementation issue.
so, this is how I implemented it in sidekiq.rb
```
Sidekiq.configure_server do |config|
  config.periodic do |mgr|
    CRONS_CONFIG.map { |name,options|
      if options['enable'] == true
        job_options = options['job_options'] || {}
        mgr.register(options['cron'], name.to_s, job_options )
      end
    }
  end
end
```
and an example of my config:
```
MyWorker:
  enable: true
  cron: "5 */1 * * *"
  job_options:
    queue: :my_queue
    retry: 0
```

while long-running jobs are not my current scenario, can you please share some solutions for that case, because i will definitely have such jobs in the near future.

**Comment by mperham** [comment]
I need to know how to reproduce your current scenario if you want me to solve it. The code has a callback to load the new crons when the new leader steps up so I'm not clear how to get your described behavior.

**Comment by DanOfir** [comment]
Thanks for your help @mperham, after you confirmed that new leader should register new crons, I found the actual problem, I had a bug in my signals handling, I didn't pass the SIGTERM to the child process and it actually causes the pod to stay up for a couple of hours.

I fixed it and everything seems to work now.
