### ISSUE TITLE
Consult RACK_ENV after RAILS_ENV

### ISSUE THREAD

**Issue by roberts1000** [mperham/sidekiq#4493]
[This commit](https://github.com/mperham/sidekiq/commit/95fa5d90192148026e52ca2902f1b83c70858ce8) changed sidekiq to consult `RACK_ENV` before `RAILS_ENV`. This triggered an error in our staging environments. I'm just starting to research the issue, but my initial discovery suggests `RACK_ENV` was never intended to hold a specific environment name (see the discussion [here](https://github.com/rack/rack/pull/831)).  Internally, rack only cares about values of `"development"`, `"deployment"` and `"none"` (see [here](https://github.com/rack/rack/blob/1.6.0/lib/rack/server.rb#L157-L162)). 

From RACK's point of view `ENV["RACK_ENV"] = "staging"` is meaningless . rack uses `RACK_ENV` to select middleware to inject into the app (see [here](https://github.com/rack/rack/blob/d9cf9e8be60845d4297e87237f46adc874d416f3/lib/rack/server.rb#L259)). Setting `RACK_ENV` to "staging" or "production" (or some other environment name) effectively makes rack use `none` ... which stops rack from adding `"deployment"` middleware that is probably desired in staging/production. If `RACK_ENV` isn't set, rack defaults to `"development"` mode and adds middleware that probably isn't needed in staging/production (and likely reduces performance).

Rails issued a PR in 2015 to stop using `RACK_ENV` as a fallback for `RAILS_ENV` via [this PR](https://github.com/rails/rails/pull/19404). However, a quick search of the rails repo shows traces of `RACK_ENV` holding values other than the 3 listed above, so it has probably crept back in over the years.

1. Is it possible to move `ENV["RACK_ENV"]` back to it's previous position after `ENV["RAILS_ENV"]`?  `RAILS_ENV` is definitely more of an authority on the environment name that `RACK_ENV` - at least for Rails apps.  
2. Given the above discussion, `RACK_ENV` shouldn't be treated as an authority on the environment name. Maybe it should be totally removed...

**Comment by mperham** [comment]
Send me a PR to fix the behavior, this has proven more troublesome than I can justify, happy to merge.

**Comment by zarqman** [comment]
The reversion here/in #4494 seems good, so I have no concerns about this. However, the commentary here concerned me enough to need to go research the issue. In hopes of saving others some of that time, I want to add a few additional thoughts:

The comments in PR rack/rack#831 challenge the arguments of the OP. Given that it hasn't been merged after 5 years, I think it's fair to suggest the argument that "proper" values of `RACK_ENV` are limited to `development`, `deployment`, and `none` is not agreed upon. In fact, the comments argue that values like `production` and `staging` remains very common use and *is considered valid*.

Rack's injection of middleware for `RACK_ENV` values of `deployment` and `development` is true, but appears to be relevant primarily when using `rackup`. Many frameworks/web servers handle such things on their own, so a value like `production` that causes Rack to inject no middleware is often the desired outcome.

PR rails/rails#19404 from 2015 was reverted just a day later, hence why the repos still contains `RAILS_ENV`-like values in `RACK_ENV`. As of today in Rails 6.0, `RACK_ENV` is still used a valid fallback for `RAILS_ENV`.

**Summary for devs of Rails apps:** If you're using `RAILS_ENV`, keep using it. If you're using `RACK_ENV` instead, keep using it. Nothing substantive has changed in Rails up through 6.0, nor in Rack up through 2.2, which are the current versions as of today.

**Comment by roberts1000** [comment]
Thanks for digging deeper and adding more info @zarqman.

> I think it's fair to suggest the argument that "proper" values of RACK_ENV are limited to development, deployment, and none is not agreed upon.

Good point. Internally, Rack doesn't care about values other than `development`, `deployment`, or `none`, but `RACK_ENV` is used in many other projects and something like `RACK_ENV=production` has perfectly valid meaning elsewhere. Rack's been coded in such a way as to play nice with these other values. This is the unfortunate reality, which leads me to:

> If you're using RACK_ENV instead, keep using it. 

Here is where we disagree. The fact that `RACK_ENV` can have different types of values, is a problem that broke applications at my organization, cost hours of developer time to identify & fix, and ultimately led to this bug report. Since the community hasn't been able to agree on a standard meaning for `RACK_ENV` in half a decade, I would recommend that we avoid using it when possible. A quick look at how a project uses `RACK_ENV` might show that something more precise can be used instead (like `APP_ENV` or `RAILS_ENV`).

**Comment by zarqman** [comment]
@roberts1000, I wrote what I did because given the huge number of Rack apps in production, this is clearly a fringe issue. That's not to say that your team did not experience a multi-hour debugging challenge as a result. I'm sure you did and I'm sure it was frustrating. I agree that it is appropriate to revert to the previous behavior, as has been done. 😃

The reason I weighed in, however, was because the way this issue was phrased *cost my organization several hours of research* as we became concerned something might be broken in our environment (we use `RACK_ENV` across a wide array of Rails apps). In the process it was discovered that some of the original assertions were incorrect and our concerns were unfounded.

The bugreport and fix made sense and it has hopefully prevented others from wasting the debugging time your organization spent. Thank you for that! My comments were made to hopefully prevent others from wasting the research time my organization spent.

I stand by what I said, but I will add a qualifier:
**For Rails apps:** *If you're using `RAILS_ENV`, keep using it. If you're using `RACK_ENV` (and its value is not `deployment`), feel free to keep using it. There is no need to worry, spend further time on this, or change anything.* Both the Rack and Rails developers have indicated no desire to change the existing, working behavior.

For anyone who is using `RACK_ENV=deployment`, then you may want to investigate more carefully.

Further, for anyone doing anything unusual with regards to `RACK_ENV` (or using a value of `deployment`), I suggest adding a test to your app that validates the contents of the middleware stack for production (or production-like) environments. Then, if something does change, you'll know immediately and be able to quickly remedy anything necessary.
