### ISSUE TITLE
Another thought for supporting Redis Cluster

### ISSUE THREAD

**Issue by bgroupe** [mperham/sidekiq#4519]
Ruby version: 2.5.1
Sidekiq / Pro / Enterprise version(s): 5.2.8 / 4.0.5 (pro)

Please include your initializer and any error message with the full backtrace.

~~~ruby
SIDEKIQ_REDIS_PARAMS = {
  :url => EnvConfig::REDIS_URL,
  :pool_timeout => 60,
  :network_timeout => 60,
  :timeout => 60,
  :size => 30
}

Sidekiq::Client.reliable_push!

Sidekiq.configure_client do |config|
  config.redis = SIDEKIQ_REDIS_PARAMS
end

Sidekiq.configure_server do |config|
  config.super_fetch!
  config.reliable_scheduler!
  config.redis = SIDEKIQ_REDIS_PARAMS
end
~~~

Are you using an old version? Yes however, Wwe cannot upgrade Rails version of production application at this time. 
Have you checked the changelogs to see if your issue has been fixed in a later version?
Yes
https://github.com/mperham/sidekiq/blob/master/Changes.md
https://github.com/mperham/sidekiq/blob/master/Pro-Changes.md
https://github.com/mperham/sidekiq/blob/master/Ent-Changes.md

I have read in other issues in this repo about supporting Redis cluster, and I understand from [this document](https://github.com/mperham/sidekiq/wiki/Using-Redis#architecture) that Sidekiq is not designed for Redis cluster, but I noticed [this issue](https://github.com/mperham/sidekiq/issues/3492) for fixing the Web UI, so I have two questions: 

1. What is the use case for the Web UI running against an unsupported configuration fo Redis? Is there a way to run Sidekiq against a sharded Redis cluster? 

2. Have you considered the (my) use case for running Sidekiq against a multi-master Redis for the purpose of migrating environments? It is difficult to migrate a heavily utilized Sidekiq cluster (replete with scheduled sets) from one cloud provider to another without a significant amount of downtime. Multi-master replication would also enable multi-regional implementations without having to build some kind of tenancy model.

**Comment by mperham** [comment]
1. There is no usecase. Each Sidekiq process can only target one shard but you can run N shards with M Sidekiq processes each.
2. Migrating Sidekiq is akin to any database migration: non-trivial but not conceptually difficult.  There are two ways:
  * You run the old Redis and new Redis as shards. New jobs should go to the new shard. 2-3 weeks later, the scheduled and retry queues should be empty and you can shut off the old shard. No downtime at all.
  * You run the new Redis as a replica of the old Redis. During a quiet period, you shut down all Sidekiqs, flip the replica to a primary and restart the Sidekiqs pointing to the new primary. Downtime can be less than a minute with a good migration script. Since Sidekiq is async and not user-facing, no one should notice a thing.

**Comment by bgroupe** [comment]
@mperham thanks for your response. Yes I was opting to go for the second method, was just looking for an absolute zero-downtime technique. I actually misunderstood the configuration of my own cluster (my replication configuration does not require clustering) so I am all good. 

Cheers

**Comment by aka47** [comment]
@mperham - It might be helpful to collect all the information around shards from the different tickets into a wiki.. 
I have to migrate our redis to a 2 shard setup, the Database is 40GB in size and we use redislabs as redis hoster, and they require multiple shards once you reach 25GB of server size. A redis database might start small, but over the years, with more users, more data, that grows easily. 

I will try to move the sidekiq redis and some other redis data to its own redis server, that does run on one shard. Hope it all works out, seems like it should be possible.

**Comment by mperham** [comment]
> A redis database might start small, but over the years, with more users, more data, that grows easily.

This is not true and not normal with Sidekiq. Think about Sidekiq's dataset: queues. They are normally empty. You will get some persistent data due to Retries and Scheduled data, Batches, etc but that is not normally tens of GBs. It's typical for Sidekiq's dataset to be less than 1GB.

I suspect you are using Redis for caching, sessions or some other use that is the main hog of space.

**Comment by aka47** [comment]
That is not true for sidekiq, sure. And I will move sidekiqs redis to its own database/server due to its different requirements and purpose. 

But it is true for our app and when I look at the market and the packages AWS/Redislabs are offering. Seems like people are running TB sized redis databases. :)

**Comment by adamniedzielski** [comment]
> And I will move sidekiqs redis to its own database/server due to its different requirements and purpose.

It looks like you found the solution already 😉 

> It might be helpful to collect all the information around shards from the different tickets into a wiki.

I think that the solution that you found is already documented - https://github.com/mperham/sidekiq/wiki/Using-Redis#multiple-redis-instances

**Comment by untitaker** [comment]
With sidekiq 3 it appears one can define multiple redis servers and assign different jobs to each of them, briefly documented here: https://github.com/mperham/sidekiq/wiki/Advanced-Options#jobs

you can do exactly the same using redis cluster protocol and hashtags in key names to spread jobs or queues (whichever granularity you need) horizontally across a single redis cluster. the difference would have been that scaling of a redis cluster:

* does not require a custom data migration between redis nodes, as online keyspace migration is well-defined in the cluster protocol and needs to be supported by the client
* does not require you to manually define a mapping from job to redis connection. instead you define a list of redis connections and the keyspace is sharded across it

so i don't really get why it was done this way instead

why do you claim that redis cluster is only useful for the caching usecase? you can build a HA, persistent redis cluster all the same, and supporting it in sidekiq would've saved the user a bunch of manual migration + config work
