### ISSUE TITLE
APP_ENV overrides RAILS_ENV

### ISSUE THREAD

**Issue by prem-prakash** [mperham/sidekiq#4560]
Ruby version: 2.7.0
Sidekiq / Pro / Enterprise version(s): 6.0.5

https://github.com/mperham/sidekiq/blob/22e812d3f1ae9a3e5faa79637a61705186d6961e/lib/sidekiq/cli.rb#L244

Although APP_ENV will possibly become a default soon, a user may inadvertently or unintentionally overwrite RAILS_ENV by setting APP_ENV.

**Comment by mperham** [comment]
Correct. By design.

**Comment by prem-prakash** [comment]
If Rails does not use APP_ENV, it is not correct, it is unexpected behavior and it is not documented. It is at least an incompatibility with the most current Rails.

**Comment by mperham** [comment]
Then let’s get it documented. 💪🏻

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/wiki/Advanced-Options#environment

**Comment by prem-prakash** [comment]
Thank you 🙏

**Comment by TheKidCoder** [comment]
@mperham This is causing issues in our app and will require us to change lots of area - is there a reason we can't just simplify this all to a `SIDEKIQ_ENV`?

**Comment by mperham** [comment]
@TheKidCoder Have you tried `sidekiq -e`? 😂

**Comment by stevehanson** [comment]
This is also causing an issue for me as I use `APP_ENV` for other purposes. A simple solution would be to also support `SIDEKIQ_ENV` and have it take precedence over any other ENV variables. Happy to make a PR if we're open to this.

**Comment by mperham** [comment]
@stevehanson Is there some reason you can't use `-e`?

**Comment by stevehanson** [comment]
We have a script to launch sidekiq that is used in different environments and doesn't have access to the `dotenv` config where `RAILS_ENV` is set. I just updated our app to use something other than `APP_ENV` since that seemed to be the simplest recourse in my case.

More generally, it seems like if Sidekiq uses a generic name like `APP_ENV`, it should provide a mechanism to get around it without having to modify build scripts. Another gem or app code could just as easily also use `APP_ENV` but in a different way.

**Comment by mperham** [comment]
I've opened an issue with puma about the variable. https://github.com/puma/puma/issues/2692
