### ISSUE TITLE
Rolling restarts of worker processes may be losing jobs with Super Fetch

### ISSUE THREAD

**Issue by wfarr** [mperham/sidekiq#4635]
Ruby version:
Sidekiq / Pro / Enterprise version(s): 6.0.7 / 5.0.1 / 2.0.1

Initializer:

```ruby
Sidekiq::Client.reliable_push! unless Config.deployment == "test"

Sidekiq.configure_server do |config|
  config.super_fetch!
  config.reliable_scheduler!
end
```

Config:

```yaml
---
:verbose: false
:timeout: 25
:concurrency: 10

:queues:
  - ["critical", 55]
  - ["upgrades", 15]
  - ["default", 25]
  - ["low", 5]
```

We're running this sidekiq as a formation on Heroku Private Spaces. What we're seeing is that even with Super Fetch that some jobs can get lost in the face of rolling restarts:

1. App has a pool of Sidekiq workers on Dyno A and Dyno B
1. Job is running on Dyno A worker
1. Dynos start rolling restart
1. Dyno A gets SIGTERM and worker shuts down
1. Job is orphaned
1. Dyno A worker restarts
1. Dyno A worker SuperFetch recovers job and places back in queue
1. Dyno B worker starts working the job
1. Dyno B gets SIGTERM and worker shuts down
1. Job is orphaned again
1. Dyno B worker SuperFetch [does not the recover job because an hour has not past.](https://github.com/mperham/sidekiq/wiki/Reliability#recovering-jobs)
1. After an hour, the same thing happens so the job never ends up getting recovered and worked to completion.

In this case, the Job is a poller that runs with code roughly like so:

```ruby
loop do
  break if condition
  sleep 10
end
```

We're currently contemplating a couple workarounds:

* Restarting Dyno A once per hour, every hour, reclaims the job(s) upon restart
* Invoking `Sidekiq::Pro::SuperFetch.check_for_orphans` directly periodically reclaims the job(s)

And so we're wondering:

* Is this a bug?
* If not a bug, is there a better approach we're missing?
* Are our workarounds here reasonable?

Thanks!

**Comment by mperham** [comment]
It sounds like the job isn't being lost so much as it isn't finishing do to the combination of long-running + frequent deploys. Jobs shouldn't orphan unless the Sidekiq process can't cleanly shutdown before being `kill -9`'d by the platform. Are you sending the quiet signal first, to maximize the time for jobs to stop gracefully? What's your `-t` timeout value? Setting it to 25 leaves 5 more seconds for Sidekiq to stop all threads and push in-progress jobs back to Redis, which is generally plenty of time. If it's not enough time, Heroku sends `kill -9` and orphans any jobs in progress.

Generally Sidekiq jobs should not be long-running loops, since Heroku gives you 30 seconds to shutdown, your loop must check and break within that time limit. One mechanism is to use the `$shutdown_pending` trick to re-schedule if the process is restarting, e.g.

```ruby
  loop do
    break if condition
    raise Sidekiq::Shutdown if $shutdown_pending
    sleep 10
  end
```

See https://github.com/mperham/sidekiq/wiki/Deployment#events

**Comment by mperham** [comment]
Ah, I see the timeout is set to 25. Good. And now I realize that you're using USR2, not TERM.  Make sure you are sending TSTP to quiet the process and use the $shutdown_pending flag. I think that will solve your problem.

**Comment by wfarr** [comment]
I should have been more clear about "rolling restart" here. I do not mean the sidekiq rolling restart feature, but rather the Heroku platform's formation restart behavior that occurs on any release, which should be sending `SIGTERM`.

I don't know that we have the ability to customize the signal Heroku sends to include `SIGTSTP` in this manner.

I will try the `$shutdown_pending` check above and attempt to reproduce.

**Comment by mperham** [comment]
Ok, if you are only using TERM, then you should be able to use `on(:shutdown)` instead of `on(:quiet)` and get the same result.

**Comment by wfarr** [comment]
Okay, we're going to try the following for now:

1. Adding release phase to the app to call `Sidekiq::ProcessSet.new.each(&:quiet!)` (aka pre-deploy hook)
1. Having handlers for both `on(:quiet)` and `on(:shutdown)` set a `$shutdown_pending`
1. Update our polling loop to `raise Sidekiq::Shutdown if $shutdown_pending`

We'll do some testing on our end to verify, but we should be able to follow up tomorrow on whether we can still reproduce or not.
