### ISSUE TITLE
Catching Sidekiq OOM errors

### ISSUE THREAD

**Issue by echan00** [mperham/sidekiq#4680]
Based on my issue [here](https://github.com/mperham/sidekiq/issues/4679) I would like to be able to catch terminated sidekiq processes due to memory issues. 

It appears like the [wiki](https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#my-sidekiq-process-is-disappearing) doesn't have any tips for this besides improving memory usage. It would be great to be able to get alerts/error catching when it happens.

Any suggestions?

**Comment by donaldong** [comment]
I'm using the logline: `WARN: SuperFetch recovered job:` to provide more contexts on my workers' OOM alerts.

It'd might be difficult to throw an error in sidekiq since the OOMing process could be killed by force.

Though, I wonder if the sidekiq monitoring process could send some warnings if the process has used more memory than `SIDEKIQ_MAXMEM_MB`.

**Comment by mperham** [comment]
Sidekiq enterprise already has a memory monitoring feature, see the multi process wiki page.

**Comment by echan00** [comment]
Thanks for the info @mperham. 

It would be great to discover other solutions as my project is not an enterprise.

**Comment by mperham** [comment]
You can look for 3rd party plugins or build something yourself but I'm not aware of other solutions.
