### ISSUE TITLE
NoMethodError: undefined method `check_for_orphans' for Sidekiq::Pro::SuperFetch:Class

### ISSUE THREAD

**Issue by faun** [mperham/sidekiq#4693]
Ruby version: 2.6.5
Rails version: 6.0.3.3
Sidekiq / Pro / Enterprise version(s): 6.1.2, 5.2.0

We were calling this method explicitly in a cron job and recently updated our sidekiq-pro version:

```
Sidekiq::Pro::SuperFetch.check_for_orphans
```

We periodically check for orphaned jobs and re-enqueue them for Sidekiq. It appears that this method has disappeared in a recent version of Sidekiq Pro. Is there an alternative to this method? Was the refactor related to https://github.com/mperham/sidekiq/pull/4602? I can't search the history of Sidekiq Pro, as it's closed source.

Thanks in advance.

**Comment by mperham** [comment]
Yes, that API was never considered a public API so it was considered fair to refactor outside of a major version bump. I don't have an alternative API to suggest, do you still need to make that call at all?

**Comment by faun** [comment]
I'm not sure. I'll check with my team and see if we can restart workers on some sort of cadence to recover orphaned jobs.

**Comment by faun** [comment]
Is that the only mechanism to recover orphaned jobs?

**Comment by mperham** [comment]
super_fetch's orphan recovery is triggered by process startup. Jobs are almost always lost on process crash or deploy, both of which lead to process startup. I'm not sure why someone wanted to run this periodically but you might want to double check their assumptions are true.

**Comment by faun** [comment]
Thanks for the quick response. Closing.

**Comment by fotinakis** [comment]
@mperham this was intentional, we relied on that API because we run sidekiq on Google Cloud Platform [preemptible instances](https://cloud.google.com/compute/docs/instances/preemptible), which have loose guarantees about uptime and may not have a fully clean shutdown procedure, so they're more prone to orphan jobs. In production, we found that relying on worker startup to scan for orphaned jobs was not regular/consistent enough and could cause multi-hour delay in picking up orphaned jobs. In our environment we need this delay to be minimized, so we explicitly added calls to this API to more regularly check for orphans.

Definitely would be helpful to have an alternative here or to make that API public and supported.

**Comment by mperham** [comment]
The equivalent updated API is:

```ruby
Sidekiq::Pro::SuperFetch.new(Sidekiq.options).check_for_orphans
```

Try that.

**Comment by fotinakis** [comment]
That works great, thanks much @mperham

**Comment by fotinakis** [comment]
Note for anyone else who relies on this (internal) API: we upgraded from sidekiq-pro (5.3.1) to sidekiq-pro (5.5.1) and we had to update this to remove `.options`:

```ruby
Sidekiq::Pro::SuperFetch.new(Sidekiq.options).check_for_orphans
```
-->
```ruby
Sidekiq::Pro::SuperFetch.new(Sidekiq).check_for_orphans
```
