### ISSUE TITLE
Rate limiter Tagging

### ISSUE THREAD

**Issue by bnorton** [mperham/sidekiq#4695]
I have started to use concurrent and bucketed limiters to enforce restrictions on API calls from my customers to a relatively expensive set of APIs provided by our backend.

The issue is that when looking through metrics I see a key like this => `account-54fe3b303533320003070000-profiles_count` I need to cross reference this ID in the database or a spreadsheet to know how certain key customers are doing (or if there is an issue). This process would benefit from "tags" on each limiter -- I would, at minimum, tag the customer account domain to the limiter (not unique enough to use instead of the ID). I might also add information like the SLA level they are subscribed to if I had the functionality.

![Example with hypothetical tags](https://user-images.githubusercontent.com/401631/93730238-a4587b00-fb7c-11ea-8b74-2d9cc7a4a772.jpg)

Does anyone else have this need?

**Comment by mperham** [comment]
Sounds like a promising start. It would help if you would flesh out your use cases a little more so we have a common understanding and direction. Since it's common to have many dynamic rate limiters, I can see how filtering and search might be useful.

I've granted you source access to sidekiq-ent so you can send PRs or we can collaborate on improvements.

**Comment by mperham** [comment]
@bnorton Check out the latest sidekiq-ent commit which adds filtering based on name substring. Adding support for user-supplied tags is a much heavier lift requiring special data structures in Redis. I suspect that tags would solve 95% of your problem but that simple filtering might give you the most useful 80% with 1/10th of the effort.
