### ISSUE TITLE
Include process RSS on Busy page

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#4717]
Seeing the process RSS can be really helpful in determining at a glance if a Sidekiq process is "healthy" or not. If RSS is high, one click on the Stop button can fix it.

While nice, things like sparklines or historical data or graphs are not in scope. This issue does not aim to compete with NewRelic or DataDog.

**Comment by mperham** [comment]
<img width="835" alt="Screen Shot 2020-10-14 at 2 52 52 PM" src="https://user-images.githubusercontent.com/2911/96049903-94575280-0e2d-11eb-9a0e-bb4da127d361.png">

**Comment by TALlama** [comment]
We use a multi-tenant architecture where each tenant is run as its own Rails app, on shared app and db servers. The sidekiq workers follow that same pattern: each tenant gets its own worker on the shared box, and its own queues, but they all share a Redis db so that we can monitor them all from one place.

Today we got an alert that the worker box was low on memory, and we used the Sidekiq Web UI to quickly identify which tenant was having the problem, allowing us to easily find the offending job. 

(the underlying bug, for the curious: the bulk download created by the job in a question was doing a FileMagic scan to identify the file type of the ZIP file it had just created, which apparently involves FileMagic reading the entire 14GB file into memory. Needless to say this didn’t work out; we made that job skip the scan and assume that our zip creation code does indeed create zip files)
