### ISSUE TITLE
Sidekiq and Ruby 3

### ISSUE THREAD

**Issue by gearnode** [mperham/sidekiq#4761]
Ruby 3 will be released at the end of the year and comes with many exciting features. Sidekiq is a core system in the Ruby ecosystem, especially in Rails one.

## Concurrency
Currently, Sidekiq uses processes and threads as concurrency primitive. Moving to Ractor might improve thread safety and performance. In the same topic, the new scheduler for async IO can maybe improve performance too.

## Static Analysis
Ruby 3 comes with RBS, which can help to keep Sidekiq codebase even more robust than today. Moreover, it can help engineers to reduce the number of errors they have with their Sidekiq jobs.

The goal of this issue is to start a discussion about Sidekiq and Ruby 3. Maybe the response must be not to use Ruby 3 features.

**Comment by mperham** [comment]
Since there's no specific issue or resolution here, I'm going to close this as there's no action to take. Please feel free to open new issues with specific concerns or suggestions to discuss.

As to Ruby 3 feature usage, Sidekiq won't depend on any Ruby 3 features until we've dropped support for Ruby 2.7, which should be many years from now.
