### ISSUE TITLE
trying to finetune my sidekiq configuration so I can increase the number of workers

### ISSUE THREAD

**Issue by slopeofhope81** [mperham/sidekiq#4765]
Ruby version: '2.5.8'
Rails version: '5.1.7'
Sidekiq / Pro / Enterprise version(s): 
    sidekiq (6.1.1)
      connection_pool (>= 2.2.2)
      rack (~> 2.0)
      redis (>= 4.2.0)
    sidekiq-batch (0.1.6)
      sidekiq (>= 3)
    sidekiq-throttled (0.13.0)
      concurrent-ruby
      redis-prescription
      sidekiq

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.

sidekiq initializer:
```
require 'sidekiq/api'
require 'sidekiq/web'
require "sidekiq/throttled"
Sidekiq::Throttled.setup!

module Sidekiq
  class Client

    # items example
    # {"class" => FooJob, "args" => [[Time.current.to_f, [argument_1, argument_2]]]}
    def push_bulk_with_diff_schedules(items)
      arg = items['args'].first
      return [] unless arg # no jobs to push
      raise ArgumentError, "Bulk arguments must be an Array of Arrays: [[1], [2]]" if !arg.is_a?(Array)

      normed = normalize_item(items)
      payloads = items['args'].map do |args|
        copy = normed.merge(
                   'at' => args.first,
                 'args' => args.last,
                  'jid' => SecureRandom.hex(12),
          'enqueued_at' => Time.now.to_f
        )
        result = process_single(items['class'], copy)
        result ? result : nil
      end.compact

      raw_push(payloads) if !payloads.empty?
      payloads.collect { |payload| payload['jid'] }
    end

  end
end
```
procfile worker file
`
```
main_worker: env QUEUE=default RAILS_ENV=production bundle exec rake jobs:work
main_worker: env QUEUE=default RAILS_ENV=production bundle exec rake jobs:work
onboarding_worker: env QUEUE=onboarding RAILS_ENV=production bundle exec rake jobs:work
onboarding_worker: env QUEUE=onboarding RAILS_ENV=production bundle exec rake jobs:work
small_worker: env QUEUE=small RAILS_ENV=production bundle exec rake jobs:work
small_worker: env QUEUE=small RAILS_ENV=production bundle exec rake jobs:work
sidekiq_default_worker: bundle exec sidekiq -q default -c 30
sidekiq_records_worker: bundle exec sidekiq -q records -c 1
sidekiq_updates_worker: bundle exec sidekiq -q updates -c 1
sidekiq_matcher_worker: bundle exec sidekiq -q matcher -c 1
sidekiq_onboarding_worker: bundle exec sidekiq -q onboarding -c 1
single_thread_worker: env QUEUE=single_thread RAILS_ENV=production bundle exec rake jobs:work
single_thread_worker: env QUEUE=single_thread RAILS_ENV=production bundle exec rake jobs:work
```
`
sidekiq.yml
```
:queues:
  - records
  - default
  - onboarding
```

If you are using an old version, have you checked the changelogs to see if your issue has been fixed in a later version?

https://github.com/mperham/sidekiq/blob/master/Changes.md
https://github.com/mperham/sidekiq/blob/master/Pro-Changes.md
https://github.com/mperham/sidekiq/blob/master/Ent-Changes.md

**Comment by mperham** [comment]
You need to remove sidekiq-batch and sidekiq-throttled if you want to use Sidekiq Pro, they conflict and they can significantly affect performance. The Pro features are well-tuned but I can't speak to or control those libraries.

Which queue is overloaded? How many worker dynos are you running of each worker type? `-c 30` is too much, I don't recommend more than 10 threads per core. If you are running `perf-l` dynos, Sidekiq Enterprise's multi-process feature will allow you to take advantage of all the cores on the perf-l, which can greatly reduce the number of dynos you need. Sidekiq only uses one core because Ruby is limited to one core per process.

**Comment by slopeofhope81** [comment]
1) I am currently running 1 dyno for all the sidekiq workers and the default queue is now overloaded with 6 days of latency and close to 6 million jobs are enqueued. So if I were to go with the Sidekiq Enterprise version.. How many threads of workers can I run on perf-l? 

2) Also I would like to kill some specific workers that are in a default queue that are over 10 days old.. is there a way to do it? 

3) Can you offer some guidance in how to migrate Sidekiq::Batch and Sidekiq::Throttle to SidekiqPro api..?

**Comment by mperham** [comment]
1. I believe perf-l dynos have 4 or 8 cores, so you'd get 4 or 8 Sidekiq workers, instead of 1 today. This should dramatically improve your job throughput. All you have to do is change `bundle exec sidekiq` in your Procfile to `bundle exec sidekiqswarm`. See https://github.com/mperham/sidekiq/wiki/Ent-Multi-Process.

2. You'd need to restart the dyno. This usually indicates you have a deadlocked or stuck job somehow. There's no way to kill a running job safely, only process restart.

3. sidekiq-batch uses the same API, just remove the gem from the Gemfile. Your code will use Pro's Batch API instead. For sidekiq-throttled, remove the gem and remove the two lines from your initializer. I don't know if any other changes need to be made.

**Comment by mperham** [comment]
RE: 1. Today you have 1 process with 30 threads, but 30 is too high. With 10 and since perf-l has 8 vCPUs, with `sidekiqswarm` you'd get 8 x 10 = 80 which should scale much better.
