### ISSUE TITLE
Queue latency showing wrong values

### ISSUE THREAD

**Issue by raivil** [mperham/sidekiq#4768]
Ruby version: 2.6.5
Rails version: 6.0.3.4
Sidekiq / Pro / Enterprise version(s): 6.1.2/5.2.0/2.2.0
Redis: 5.0.5

Initializer:
```
Sidekiq::Pro.dogstatsd = -> { StatsD::Monitoring.instance("sidekiq") }
Sidekiq.configure_server do |config|
  redis_attributes = { url: Redis::ConnectionPool.sidekiq_connection_url, driver: "hiredis" }

  config.redis = redis_attributes

  config.super_fetch! # https://github.com/mperham/sidekiq/wiki/Pro-Reliability-Server
  config.reliable_scheduler! # https://github.com/mperham/sidekiq/wiki/Reliability#scheduler

  config.log_formatter = Sidekiq::Logger::Formatters::JSON.new

  config.retain_history(10) do |s| # history is captured every 10 seconds
    s.batch do |b|
      %w(critical low mailers medium reports).each do |qname| # default queue latency is already captured
        q = Sidekiq::Queue.new(qname)
        b.gauge("sidekiq.queue.latency", q.latency, tags: ["queue:#{qname}"])
      end
    end
  end
```

Hey Mike,

I've been testing sidekiq metrics with Statsd/Newrelic and looks like it work almost perfectly. I've done many tests locally and the data is correctly sent to newrelic. Production/Staging also send data as expected.

Example of a queue where latency is high (one or more minutes)
```
TIMESTAMP | SIDEKIQ.SIDEKIQ.QUEUE.LATENCY | QUEUE
December 21, 2020 13:10:00 | {"type":"gauge","count":2,"sum":163.5219344,"min":81.7609672,"max":81.7609672,"latest":81.7609672} | low
```

There's only one issue I've found.
Sometimes latency is reported as zero on production/staging, usually when it's supposed to be a higher number (few seconds).

Debugging locally didn't help a lot, but I was able to find some weird numbers when running a lot of jobs with errors:

Checking latency manually on rails console with different values.
```
=> 1564.9766800403595
irb(main):207:0> Sidekiq::Queue.new("low").latency
=> 1565.5197169780731
irb(main):208:0> Sidekiq::Queue.new("low").latency
=> 0.15608349809e4
irb(main):209:0> Sidekiq::Queue.new("low").latency
=> 0.15613699239e4
irb(main):210:0> Sidekiq::Queue.new("low").latency
=> 0.15618994289e4
irb(main):211:0> Sidekiq::Queue.new("low").latency
=> 0.15560977541e4
irb(main):212:0> Sidekiq::Queue.new("low").latency
=> 0.15567279791e4
irb(main):213:0> Sidekiq::Queue.new("low").latency
=> 0.15574004711e4
irb(main):214:0> Sidekiq::Queue.new("low").latency
=> 1549.4603247642517
irb(main):215:0> Sidekiq::Queue.new("low").latency
=> 0.15460637132e4

irb(main):224:0> entry = Sidekiq.redis { |conn|
        conn.lrange(@rname, -1, -1)
      }.first
=> "{\"retry\":true,\"queue\":\"low\",\"backtrace\":true,\"class\":\"MyJob\",\"args\":[],\"jid\":\"9f051904aaf3d828779fcc75\",\"created_at\":1608568559.536787,\"enqueued_at\":\"1608568955.8690119\",\"error_message\":\"wrong number of arguments (given 0, expected 1)\",\"error_class\":\"ArgumentError\",\"failed_at\":1608568933.468019,\"retry_count\":4,\"error_backtrace\":\"removed\\n\",\"retried_at\":1608571474.982704}"

(at some point I remember seeing "enqueued_at" with values similar to " 0.15574004711e4", but I've lost the evidence. 

## "enqueued_at" is a quoted string here, not a number.

irb(main):227:0> job = Sidekiq.load_json(entry)
=> {"retry"=>true, "queue"=>"low", "backtrace"=>true, "class"=>"MyJob", "args"=>[], "jid"=>"1d19b1d2a576b3383feb1a17", "created_at"=>1608568557.968181, "enqueued_at"=>"1608568948.7720928", "error_message"=>"wrong number of arguments (given 0, expected 1)", "error_class"=>"ArgumentError", "failed_at"=>1608568920.47653, "retry_count"=>4, "error_backtrace"=>"removed", "retried_at"=>1608571473.045738}
irb(main):234:0> now = Time.now.to_f
      thence = job["enqueued_at"] || now
      now - thence
=> 1608572684.1363788
=> "1608568948.7720928"
Traceback (most recent call last):
        2: from (irb):236
        1: from (irb):236:in `-'
TypeError (String can't be coerced into Float)

(This error happened after I manually stopped sidekiqswarm)
```

Jobs execution log:
```
2020-12-21T17:39:08.039Z pid=97335 tid=ounuatdo3 INFO: Booting Sidekiq 6.1.2 with redis options {:url=>"redis://localhost:6379/", :driver=>"hiredis"}
{"ts":"2020-12-21T17:39:08.046Z","pid":97335,"tid":"ounuatdo3","lvl":"INFO","msg":"Booting Sidekiq 6.1.2 with redis options {:url=>\"redis://localhost:6379/\", :driver=>\"hiredis\"}"}
{"ts":"2020-12-21T17:39:09.560Z","pid":97335,"tid":"ounuatdo3","lvl":"INFO","msg":"Booted Rails 6.0.3.4 application in development environment"}
{"ts":"2020-12-21T17:39:09.561Z","pid":97335,"tid":"ounuatdo3","lvl":"INFO","msg":"Running in ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin19]"}
{"ts":"2020-12-21T17:39:09.561Z","pid":97335,"tid":"ounuatdo3","lvl":"INFO","msg":"Sidekiq Pro 5.2.0 / Sidekiq Enterprise 2.2.0, commercially licensed."}
{"ts":"2020-12-21T17:39:09.565Z","pid":97335,"tid":"ounuatdo3","lvl":"INFO","msg":"Starting processing, hit Ctrl-C to stop"}
{"ts":"2020-12-21T17:39:09.570Z","pid":97335,"tid":"ounw5nik7","lvl":"INFO","msg":"SuperFetch activated"}
{"ts":"2020-12-21T17:39:09.614Z","pid":97335,"tid":"ounw5nhyb","lvl":"INFO","msg":"Managing 44 periodic jobs"}
{"ts":"2020-12-21T17:39:09.618Z","pid":97335,"tid":"ounw5nhyb","lvl":"INFO","msg":"Sending processing metrics to #<Sidekiq::Pro::Metrics::Dogstatsd:0x00007f87332346e8 @statsd=#<ConnectionPool:0x00007f8733234698 @size=12, @timeout=5, @available=#<ConnectionPool::TimedStack:0x00007f8733234620 @create_block=#<Proc:0x00007f8733234710@/app/config/initializers/sidekiq/sidekiq.rb:64 (lambda)>, @created=0, @que=[], @max=12, @mutex=#<Thread::Mutex:0x00007f87332345a8>, @resource=#<Thread::ConditionVariable:0x00007f8733234580>, @shutdown_block=nil>, @key=:\"pool-70109327631120\", @key_count=:\"pool-70109327631120-count\">>"}
{"ts":"2020-12-21T17:39:09.625Z","pid":97335,"tid":"ounw5nhyb","lvl":"INFO","msg":"Gained leadership of the cluster"}
{"ts":"2020-12-21T17:31:16.534Z","pid":93828,"tid":"owvqwgons","lvl":"INFO","msg":"fail","ctx":{"class":"MyJob","jid":"5ec73091fb56aa6f096571e6","elapsed":"0.01"}}
{"ts":"2020-12-21T17:31:16.535Z","pid":93828,"tid":"owvqwgons","lvl":"WARN","msg":"{\"context\":\"Job raised exception\",\"job\":{\"retry\":true,\"queue\":\"low\",\"backtrace\":true,\"class\":\"MyJob\",\"args\":[],\"jid\":\"5ec73091fb56aa6f096571e6\",\"created_at\":1608568560.369355,\"enqueued_at\":1608571831.886658,\"error_message\":\"wrong number of arguments (given 0, expected 1)\",\"error_class\":\"ArgumentError\",\"failed_at\":1608568940.121059,\"retry_count\":4,
```

Any ideas of what might be causing this and what else to look for?

Best regards,

**Comment by mperham** [comment]
I suspect that sidekiq is re-enqueuing a job which had previously failed many minutes or hours before and the enqueued_at value in that job is from when it was first created and pushed. That would lead to unpredictable spikes in latency which are false alarms.

**Comment by mperham** [comment]
You have the reliable scheduler enabled so the question is does it update the enqueued_at value?

**Comment by mperham** [comment]
It does update enqueued_at, so that's not the issue.

1. Latency should never be 0. This indicates the job was pushed to Redis without an `enqueued_at` value so it can't be calculated.
2. Latency of 0.15 is healthy and normal, that's 150ms.
3. Any time a job is pushed to Redis with Sidekiq's APIs, [it gets a fresh enqueued_at value](https://github.com/mperham/sidekiq/blob/66a815524801b5f58c62930c9e22bf8582dc5b43/lib/sidekiq/client.rb#L206).

So I'm not sure why you are seeing these wild swings but double check any code which is pushing Sidekiq jobs directly to Redis without using Sidekiq's APIs.

**Comment by jeffblake** [comment]
Do you have the OJ gem and recently update to 3.10.17? 

If so, take a look at this issue... it could be related.

https://github.com/ohler55/oj/issues/628

**Comment by raivil** [comment]
@jeffblake yes, OJ 3.10.17 is present.

I'll check the issue you mentioned.

I redid the tests locally after flushing Redis, disabling scheduled jobs.
Jobs are only enqueued on console.
Similar results.

```
irb(main):284:0> 1.upto(10000) { MyJob.perform_async }
=> 1
=> 1.6197261810302734
irb(main):291:0> Sidekiq::Queue.new("low").latency
Traceback (most recent call last):
        1: from (irb):291
TypeError (String can't be coerced into Float)
irb(main):292:0> Sidekiq::Queue.new("low").latency
=> 1.1833012104034424
irb(main):293:0> Sidekiq::Queue.new("low").latency
=> 2.8698670864105225
irb(main):294:0> Sidekiq::Queue.new("low").latency
=> 1.567234754562378
irb(main):302:0> Sidekiq::Queue.new("low").latency
=> 0
irb(main):303:0> Sidekiq::Queue.new("low").latency
=> 0
irb(main):304:0> Sidekiq::Queue.new("low").latency
=> 0.970972e-1
irb(main):305:0> Sidekiq::Queue.new("low").latency
=> 0.13546412e1
irb(main):306:0> Sidekiq::Queue.new("low").latency
=> 0.23888452e1
irb(main):307:0> Sidekiq::Queue.new("low").latency
=> 0
irb(main):308:0> Sidekiq::Queue.new("low").latency
=> 0
irb(main):309:0> Sidekiq::Queue.new("low").latency
=> 0
irb(main):310:0> Sidekiq::Queue.new("low").latency
=> 0.4762990474700928
irb(main):311:0> Sidekiq::Queue.new("low").latency
=> 2.0065109729766846
irb(main):312:0> Sidekiq::Queue.new("low").latency
=> 3.233980894088745
irb(main):313:0> Sidekiq::Queue.new("low").latency
=> 0.21631789207458496
irb(main):314:0> Sidekiq::Queue.new("low").latency
=> 1.4458849430084229
irb(main):315:0> Sidekiq::Queue.new("low").latency
=> 0
irb(main):316:0> Sidekiq::Queue.new("low").latency
=> 0.3447341e0
irb(main):317:0> Sidekiq::Queue.new("low").latency
=> 0.16370092e1
irb(main):318:0> Sidekiq::Queue.new("low").latency
=> 0.23484682e1
irb(main):319:0> Sidekiq::Queue.new("low").latency
Traceback (most recent call last):
        1: from (irb):319
TypeError (String can't be coerced into Float)
```

**Comment by jeffblake** [comment]
Yes it looks like that OJ issue is affecting, it appeared OJ made a breaking change in a minor dot release.. the OJ defaults were changed.

Sometimes `Time.current.to_f` returns a 17 digit float, which causes the new OJ version to load it as a BigDecimal and end up as a string in Sidekiq...
https://github.com/ohler55/oj/issues/628#issuecomment-747656559

To fix it I added this
```
Oj.default_options = {
  bigdecimal_load: :float
}
```

**Comment by mperham** [comment]
Note that Oj has been on the "problematic" gems list for a few months now:

https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#thread-unsafe-gems-do-not-use

**Comment by raivil** [comment]
Updating `Oj.default_options` seems to fix the issue related to the exceptions/errors.

However, sending data to `statsd` is not working as expected.
I've made a staging system queue a lot of jobs to generate some latency. 
I followed the latency using console using `Sidekiq::Queue.new("medium").latency` and grafana with https://github.com/Strech/sidekiq-prometheus-exporter. Both got correct values.

Data reported using statsd is not correct. Looks like it doesn't update and keep repeating the values.

One thing that caught my attention is that when I forced a "Stop All" workers, once they returned the value updated once and then kept repeating again.

![Screen Shot 2020-12-21 at 18 37 36](https://user-images.githubusercontent.com/2623565/102824560-db2c7000-43bb-11eb-8006-b19afa458680.png)

Not sure what is going on and will keep investigating.

**Comment by raivil** [comment]
@mperham I've noticed that whenever there is a larger load, let's say 1 million jobs in 60 minutes, sidekiq seems to suddenly stop sending data to statsd server (which forwards to Newrelic).
I've tried restarting the statsd server without effect. Nothing on logs, memory consumption really low.

Then I killed the the leader worker after putting in quiet mode to finalize processing jobs. Metrics started to show on right after.

![Screen Shot 2021-02-08 at 15 28 36](https://user-images.githubusercontent.com/2623565/107265251-cd41b580-6a22-11eb-8277-c16c05818523.png)

Do you have any clues on what I can look for or what might be causing this? Thank you.

Best,

**Comment by mperham** [comment]
@raivil Statsd is UDP, which is best effort; it's really difficult to track down missing metrics. I don't have any specific advice and no one's reported similar behavior before.

**Comment by raivil** [comment]
> @raivil Statsd is UDP, which is best effort; it's really difficult to track down missing metrics. I don't have any specific advice and no one's reported similar behavior before.

ok, I understand.
What I'm seeing is the leader worker not sending data to statsd whenever the number of jobs is high. It only fixes the issue when the leader worker is changed.

Thanks for your help, I'll try to find more data on this.

**Comment by mperham** [comment]
For the record, the only codepath I know of which does not reset enqueued_at when enqueuing a job is super_fetch. If an orphaned job is rescued, it will have a large latency.

**Comment by wjessop** [comment]
This is all Heroku, so the clocks are /probably/ accurate, but I don't have anything more concrete than that without doing more diagnostics. We've not got any issues with NewRelic web/job metrics, skylight or Datadog so I'd bet that the clocks are fine, but if needed we can try to check.

What would the JID tell us? There's an affected JID in the diagnostics I did in the previous comment, but all I think that the diagnostic tells us us that when the `enqueued_at` value is stored in Redis is already inaccurate.

**Comment by mperham** [comment]
The fact that enqueued_at is a String is a good clue. Sidekiq Pro's reliable scheduler adds the enqueued_at value by hand with a gross hack in Lua. I wonder if this results in a String value in the job payload and perhaps the Lua clock is bad or returning a bad value somehow.

**Comment by wjessop** [comment]
In that case it could be clock drift somehow in Lua? You can see the latency arcs over the month in the first graph above, but here's all of the queues with a linear scale:

![Screenshot 2023-05-23 at 19 31 19](https://github.com/sidekiq/sidekiq/assets/9440/f7ddd2d1-6a7c-4923-bb7d-705b8acd4767)

I thought the latency reset might have been when the last Heroku maintenance happened on our Redis instance (April 26) but unfortunately it doesn't line up with the early May reset:

![Screenshot 2023-05-23 at 19 32 55](https://github.com/sidekiq/sidekiq/assets/9440/9340c7e6-5a72-4437-ab84-3af666df265c)

The maintenance might not have caused the servers to restart though. We do have queues on the same Redis instance that are seemingly unaffected by this issue so that would suggest to me that there is nothing wrong with the server clock or we'd see issues with all queues, but that doesn't seem to be the case:

![Screenshot 2023-05-23 at 19 35 41](https://github.com/sidekiq/sidekiq/assets/9440/17e925fa-0642-4eb8-9a52-54b8c8cc7513)

I'm not familiar with Lua and Redis, is there anything further we can check there?

**Comment by wjessop** [comment]
OK, well I bet this has something to do with Oj which is a bit cursed. I'll see if I can confirm that and work out how to patch it somehow. Unfortunately removing Oj at this point is too big a task.

**Comment by mperham** [comment]
Ugh, OJ. Just say no, everyone. You might see if you can at least turn off OJ within `Sidekiq.server?`

**byroot** `As for Oj. It looks good on benchmark, but it’s incredibly unstable. It Segfault and leak memory very easily, I’m trying to get rid of it but it’s a huge pain as all its monkey patchs don’t behave exactly like what it patches, and now the behavior is calcified in the app.`
**byroot** `Also stdlib JSON used to be quite slow, but it got lots of improvements a couple years back, now Oj only make a significant difference on very large payloads.`

**Comment by wjessop** [comment]
I've been looking at upgrading (3.11.3 to 3.11.4 has significant breaking API changes) or preferably removing Oj, but it's hard to do in a mature app where we're not confident every use of Oj is covered by tests.

In a new app I'd not install it, but for now Oj is a fact of life for at least the short to medium term.

I'll see if we can disable Oj in Skidekiq, though I'm not sure that will help because I suspect that the float-as-string issue is happening client side (given the data is like it is in Redis already) which is where we're least able to disable it. Alternatively perhaps there's a way of intercepting whatever writes enqueued_at and convincing it to not be a string.

**Comment by mperham** [comment]
I'll look into adding support for String values. That's likely easier.

**Comment by wjessop** [comment]
Thanks Mike, I appreciate it.

**Comment by mperham** [comment]
*narrator's voice*: It was indeed easier.

Fixed in 7.1.2, now available.

**Comment by wjessop** [comment]
Whoah, that was quick! Thanks, will give it a go ASAP.

**Comment by goalaleo** [comment]
We're still seeing strange spikes in our `queue_latency` metric even though we're using
```
sidekiq (7.3.9)
sidekiq-ent (7.3.4)
sidekiq-pro (7.3.6)
```
And perhaps relevant:
```
oj (3.16.9)
```
Was the support for String values meant to address the compatibility issue with Oj or is that still outstanding?

<img width="1977" height="543" alt="Image" src="https://github.com/user-attachments/assets/51cf9b0a-7d08-4e8d-a760-705da0a67e71" />

**Comment by mperham** [comment]
could those be retries?

**Comment by wjessop** [comment]
I think they're retries. I think the metric should not include them though. In my mind queue latency is effectively something like "how long does it take to get to a job in the queue" If a job is retried once after 10 minutes (say, due to backoff) after the first attempt, but each time the job spent 1 second in the queue, the queue_latency is 1 second, not 10 minutes + 2 seconds.

Taking into account retry time throws off queue latency and makes it hard to scale based on this figure, a queue latency of several hours is likely to push past an upscaling threshold even though the "real" queue latency is sub-second.

**Comment by goalaleo** [comment]
@mperham yes, it's possible. Our assumption was that the `enqueued_at` would also be reset when the job is moved from RetrySet to the queue, but it seems this was the wrong assumption to make. The [JobRecord](https://github.com/sidekiq/sidekiq/blob/32567d7cf2a465d93d69be2754d6f899ea655848/lib/sidekiq/api.rb#L456-L464) has both `enqueued_at` and `created_at` attributes, and their usage feels a bit inconsistent to me. Or perhaps the meaning of `latency` for `queue.latency` and `job.latency` is unintuitive to me.

I agree with @wjessop - by using `queue.latency` our intention was to monitor throughput and ensure that we have enough workers. @mperham maybe your intention was for queue size to be used for that?

If I wanted to monitor how long it took for an individual job to complete (including retries), then I would intuitively use `job.latency`, which imo should be calculated as `now - created_at` where `created_at` is the original time the job was created - not the last `enqueued_at` time.

**Comment by mperham** [comment]
Well, latency shouldn’t increase more than real time so if latency is 0 and then 10 seconds later latency is 1000 seconds, something is wrong.

The scheduler Lua could reset enqueued_at but that would add significant overhead, which is why we’ve left it as a known edge case. Maybe we could clear enqueued_at when we create the retry? That would return 0 as the latency in the future but maybe 0 is better than an obvious wrong value?

**Comment by mperham** [comment]
@goalaleo latency is meant to represent how long the job sits in the queue and is the main metric to be used for worker autoscaling. That’s not the same as created_at, because of schedule or retry delay.

**Comment by goalaleo** [comment]
@mperham thanks for the comments!

> Maybe we could clear enqueued_at when we create the retry? That would return 0 as the latency in the future but maybe 0 is better than an obvious wrong value?

Do you mean that the job would not get a new `enqueued_at` even when it's returned from the RetrySet to the queue, so it would always have 0 latency if it has gone through a retry? Are you suggesting this as the lesser of two evils between a latency spike and showing 0 latency? If yes, then I think:

PROS
- it would prevent the [latency spike](https://github.com/sidekiq/sidekiq/issues/4768#issuecomment-3486165292), so if latency was used for autoscaling then it would prevent a sudden and unnecessary scale-up, SLO alerts etc.

CONS
- information is still not correct
- There will be a dip in the metric instead of a spike if the last job is a retried job
- if there was a systematic error that caused a large amount of jobs to go to retry, then when they're returned to the queue they would all have 0 latency, which would result in the autoscaling not scaling up correctly leading to congestion.

**Comment by mperham** [comment]
@goalaleo Can we stop using a years old, closed issue for discussion? If there is a current issue in Sidekiq, please open a new issue or discussion and I would be happy to talk changes there.
