### ISSUE TITLE
Option to disable skipped enqueue log

### ISSUE THREAD

**Issue by mcfadden** [mperham/sidekiq#4775]
Is there an option to disable the INFO log every time a non-unique enqueue is skipped?

> Skipping enqueue for [JobClass], not unique.

Thanks!

**Comment by mperham** [comment]
There is not.

**Comment by mcfadden** [comment]
I'd love one if it were added. But I can manage filtering them out elsewhere in logging for now. Thanks!

**Comment by mperham** [comment]
The logic is that I don’t want to user confused by a job mysteriously
disappearing. If I logged nothing a lot of people would spend a lot of
hours debugging why.

**Comment by pboling** [comment]
@mperham I'd love to have this feature also.  The logic is sound for wanting to have logging be the default, but it does not hold up for being unable to turn off the logging.

I have a gem, [`silent_stream`](https://github.com/pboling/silent_stream) that could silence anything within a block, but that can be a dangerous hammer to use because it silences STDOUT and / or STDERR indiscriminately.

**Comment by Sybe** [comment]
I agree with @pboling, disabling the warning should not be default, but it really should be possible.
