### ISSUE TITLE
Guidance: handle Sidekiq Exceptions for jobs sending Exception Tracking

### ISSUE THREAD

**Issue by apfranzen** [mperham/sidekiq#4941]
Ruby version: 2.6.6
Rails version: 5.0.7
Sidekiq / Pro / Enterprise version(s): 6.2.1

When using Sidekiq to send Exceptions to an Exception Tracker such as Sentry, what is the recommended way to handle Exceptions that occur in Sidekiq while the background job is sending the initial Exception to Sentry? My understanding is that it is best practice to let the Exception be handled by Sidekiq, and that way the job can be subject to Sidekiq job configuration. In our case, we are not currently retrying jobs, so the job should end up in dead state. Once picked up in the dead state, we could manually retry the job. When an Exception is raised in the background job as shown in sentry_job.rb, this causes a cascade of jobs to be queued, and immediately end up in the Dead pile. It seems to stop queuing at around 10 jobs for some reason. I am concerned this scenario will queue a huge number of Sidekiq jobs. 

One solution we have tried is to rescue the exception and log the failure in some way, but then the original exception cannot be retried.

I would greatly appreciate any guidance! I have reviewed the [Error Handling page](https://github.com/mperham/sidekiq/wiki/Error-Handling) in detail.

sidekiq.ym:
```
---
:verbose: true
:timeout: 25
:max_retries: 0
:queues:
  - sentry_errors

development:
  logfile: log/sidekiq_development.log

production:
  pidfile: tmp/pids/sidekiq.pid
  logfile: log/sidekiq_production.log
  concurrency: 2
```

sentry_job.rb
```
class SentryJob < ActiveJob::Base
  queue_as :sentry_errors

  def perform(event)
    raise 'This is inside sentry job'
    Raven.send_event(event)
  end
end
```

sidekiq.rb
```
# Suppress warning
Redis.exists_returns_integer = true

redis_config = { ... }

Sidekiq.configure_client do |config|
  config.redis = redis_config
end

Sidekiq.configure_server do |config|
  config.redis = redis_config
  config.failures_default_mode = :all
end
```

**Comment by mperham** [comment]
I’m not sure I really understand your concern. Sidekiq is designed to handle hundreds of thousands of job retries. Just enable the default retry system for all jobs.

It looks like maybe you are using a sidekiq-failures plugin which keeps all failed jobs? That’s going to be a big problem if you do see a spike in job errors because it will balloon up your Redis data size.

**Comment by apfranzen** [comment]
Thanks for taking a look. It isn't so much the retry system that is my concern. Let me ask it in a different way: Is sending Exceptions to a service like Sentry via Sidekiq a concern, when there could be exceptions in the job itself? Is the behavior I described of testing by raising an exception in `perform`, which results in another SentryJob concerning? It seems like this could really balloon.

**Comment by mperham** [comment]
It’s only a potential problem if Sentry is using Sidekiq itself to send
error reports. I think if you are using the default settings, it should be
fine.

**Comment by allocatedev** [comment]
I have encountered recursive job issues with Sentry in the past https://github.com/getsentry/sentry-ruby - An exception would occur in a web process and a job would be queued to Sidekiq. Then, attempting to post the exception to Sentry's servers, the job would throw an exception, which would queue a job, which would blow up, rinse and repeat.

I've seen Sentry trying to send themselves performance traces that are too large which their servers reject with a 413 status code, which then throws an exception because their gem doesn't gracefully handle that response. Another fun one has been Sentry trying to queue a job with a reserved key, causing an exception along the lines of `ERROR: Can't serialize a Hash with reserved key "_aj_globalid"`

My advice is to not run Sentry in async mode if it's already in an async context. I have had hundreds of thousands of jobs pushed into redis from Sentry blowing up on something and then blowing up trying to report that it blew up 😂 

Here's how I setup Sentry's config in my initializer file.

```ruby
# Don't async exceptions or traces if already in a background job
if Sidekiq.server?
  config.async = false
  config.background_worker_threads = 0
else
  config.async = lambda { |event, hint| Sentry::SendEventJob.perform_later(event, hint) }
end
```

Hope this helps!
