### ISSUE TITLE
Avoid recovering OOMing jobs via SuperFetch

### ISSUE THREAD

**Issue by donaldong** [mperham/sidekiq#4992]
sidekiq version: sidekiq-6.1.1

Hi 👋 

I have a job that can consume all the memory on a worker given some args combination. Once the heartbeat expires, super-fetch immediately recovers, and the job gets picked up by a worker right away.

I'd like to rerun this job manually on a very large machine, and stop this job from being picked up by other workers. Are there existing APIs that can help?

Thanks!

**Comment by mperham** [comment]
Since super_fetch is in sidekiq pro, it would be very helpful to know the version of sidekiq pro you are running.￼

Did you check the changelog and see that sidekiq pro 5.2 handles poison pill jobs better?￼ that might help. 

The way to target jobs to a particular machine is to route those jobs to a particular queue that is only processed by sidekiq on that machine.￼

**Comment by donaldong** [comment]
Woo, thanks!! #4633 would be great in this case! I will upgrade our sidekiq-pro version.

Right now we're on sidekiq-pro 5.1.1.
