### ISSUE TITLE
Custom ActiveRecord Connection Pool Size

### ISSUE THREAD

**Issue by Ragmaanir** [mperham/sidekiq#503]
Hi,

is it possible to specify an ActiveRecord Pool Size for Sidekiq that differs from the rails environment settings? We have the default database pool size of 5 for our unicorn workers, but since we want to use ~20 sidekiq workers we would like to customize the pool size for sidekiq. 

Some worker threads fail with an "could not obtain a database connection within 5 seconds [...] The max pool size is currently 5". We are not 100% sure wether this is due to the small connection pool, but decreasing the worker count to 5 made the error rate drop significantly.

Thanks

**Comment by waiting-for-dev** [comment]
@stevenharman the problem is that usually you want your `database.yml` not to be tracked by git, so you and other developers can have its own configuration. Has anyone find an usable workaround to push `database.yml` while still allowing each developer to easily work in its environment? I know every developer could set its own `DATABASE_URL` but it is quite annoying dealing with both `development` and `test` environments.

**Comment by stevenharman** [comment]
@waiting-for-dev While not an ideal solution to your problem, perhaps you could ignore the `database.yml` file locally, and then make the changes you need for `development` and `test` environments?

```bash
git update-index --assume-unchanged config/database.yml
```

**Comment by espen** [comment]
@waiting-for-dev https://github.com/bkeepers/dotenv ?

**Comment by waiting-for-dev** [comment]
Thanks both @stevenharman and @espen for your provided workarounds. Both work well and can be really useful also in other scenarios. Ideally, I wanted to deal with the situation without having to "bother" the other developers. The only option for that would be to execute a custom script during the deployment to copy a `config/databases.yml.production` to `config/databases.yml`. As I'm in heroku, maybe I'll check if adding a custom buildpack (or modifying rails one) pays off.
