### ISSUE TITLE
Question: Is it possible to use rolling restarts on heroku?

### ISSUE THREAD

**Issue by mintuhouse** [mperham/sidekiq#5051]
We have a few long running (~30min) non-idempotent jobs
Wondering if some mechanism to ensure heroku keeps those dynos up (without killing midway) even after restart/recycle

Saw https://github.com/mperham/sidekiq/wiki/Ent-Rolling-Restarts , but doesn't appear to be relevant for heroku

We are using enterprise sidekiq

**Comment by sobrinho** [comment]
It's not possible due to the Heroku limitations about how long the process have to terminate before being killed.

You could do a TSTP signal and wait until the running jobs finishes before doing a deployment but this would stop processing new jobs until they finish.

The best you can do is to split the job into smaller pieces in a Sidekiq Batch to be able to recover from deployments/failures without redoing the entire process again.

If you can't, you need to move Sidekiq to another infra-structure to be able to do rolling deploys in that scenario.

**Comment by sobrinho** [comment]
@mperham this is stale and can be closed.
