### ISSUE TITLE
I18n locale is not set correctly for active record validations

### ISSUE THREAD

**Issue by TTD93** [mperham/sidekiq#5052]
We have an issue with the following use case: 
We update the locale based on a user setting, the user then calls an endpoint and it starts a async job. The new locale can be read, and is properly set when we log from rails logger both before and within the job. But when using  `ActiveRecord::Validation`, the output from the `validate` function returns the text in the base locale in config. This magically fixes it self if we just wait 5-10 minutes - somehow, after the locale is updated. We have not added any additional cache

Code example:
```

# Outbox model
class Outbox < ActiveRecord
  validates :client_id,
            presence: { message: I18n.t('activerecord.outbox.errors.client_cannot_be_empty') }
end

# locales
# 
# en.yml
# 
# activerecord:
#     models:
#       outbox:
#         errors:
#           client_cannot_be_empty: Client cannot be empty
# 
# nb.yml
# 
#  activerecord:
#      models:
#        outbox:
#          errors:
#            client_cannot_be_empty: Kunden må være satt

# Controller method
def upload_attachment
  I18n.with_locale(@user.locale.to_sym) do
    Rails.logger.info("This is the locale before the job is called: #{I18n.locale}")
    params = some_filter_params(params)
    UploadAttachmentJob.perform_async(params)
  end
end

# Job
class UploadAttachmentJob
  include Sidekiq::Worker

  def perform(params)
    Rails.logger.info("This is the locale within the job: #{I18n.locale}")
    # ... some business logic
    outbox = Outbox.new(some_data)
    outbox.validate
    Rails.logger.info("This is the errors: #{outbox.errors.messages.join(", ")}")
  end
end
```

Given the startup locale is :nb and the user.locale = :en
The given output is as following:

This is the locale before the job is called: en
This is the locale within the job: en
This is the errors: Kunden må være satt

This happens even if we change `I18n.default_locale` before starting the job. 

Ruby version: 2.6.7
Rails version: 6.1.4
Sidekiq / Pro / Enterprise version(s): 6.0.0

Sidekiq.yml:
```
concurrency: 5
queues:
  - default
  - mailers
```

**Comment by TonsOfFun** [comment]
Sidekiq will run in the default locale just as Rails does. Setting the locale in Rails will not modify the locale in Sidekiq, since `UploadAttachmentJob.perform_async(params)` only enqueues to Redis with `params` for the sidekiq process to perform.

You have to pass the locale as an argument to the worker class `UploadAttachmentJob` when calling `perform_async` or retrieve the user.locale within the `perform` method.

**Comment by TTD93** [comment]
Hi, I already tried that

**Comment by mperham** [comment]
1. Upgrade Sidekiq. 6.0.0 is old.
2. Sounds like you just haven't actually activated the i18n middleware? Like the issue template says, please show us your initializer.

**Comment by TonsOfFun** [comment]
1. I wasn't aware for the [I18n middleware Sidekiq](https://github.com/mperham/sidekiq/blob/main/lib/sidekiq/middleware/i18n.rb) ships with, but it does exactly what you need without doing it manually as I was describing. As @mperham said, please share your initializer, so we can see if you're setup correctly. 
2. There is also an issue with your namespace in the model not matching your namespace in the locales YAML. 

Your model:
`activerecord.outbox.errors.client_cannot_be_empty`
Your locales:
`activerecord.models.outbox.errors.client_cannot_be_empty`
These don't match, so I could cause unexpected behavior. 

Also be sure to check the Rails guide for [Error Message Scope](https://guides.rubyonrails.org/i18n.html#error-message-scopes) conventions. 

Since you're essentially using:
`validates :clients_id, presence: true` 

The conventional namespace would be:
`activerecord.errors.models.outbox.attributes.client_id.blank`

Then you wouldn't have to pass the message option to the presence validator.

**Comment by TTD93** [comment]
Yes, the issue was that we did not use the middleware in the initialiser. Sorry about that! @TonsOfFun I know, was just a fast markup for show the problem.
