### ISSUE TITLE
Question about the licensing and usage of the project

### ISSUE THREAD

**Issue by dominikduda** [mperham/sidekiq#5057]
Hello

I am in the process of releasing my project and I want to make sure I can use the gem inside of it.

Sidekiq uses an LGPLv3 license.
https://github.com/mperham/sidekiq/blob/main/LICENSE

My question is can I use sidekiq inside my **closed** source SAAS commercial app? Or does it force me to publish the source code of the app?

I am asking because the license is formulated in a hard-to-understand way for a simple developer like me. 

I am simply installing the sidekiq inside my app through bundler (it is attached through Gemfile). I am not modifying the source code in any way.

It is running inside the docker container inside the machine on AWS.

Can we use it like that in a commercial app or is this forbidden by the license?

**Comment by mperham** [comment]
Yes, that is 100% ok. My reading of the LGPL is this:

* If you modified Sidekiq in some way (monkey patch or edit the files); AND
* If you distribute those changes to a customer (like in a Docker image that they download)
* Then you must also provide the source of those changes (e.g. in a GitHub repo)

Since you are a SaaS, you are not distributing Sidekiq and the LGPL allows that usage. This is why the AGPL exists.

**Comment by vfonic** [comment]
I believe this could be worth mentioning in the README. Licensing language is difficult to understand for many people. I was sure that LGPL means I have to open-source my entire project codebase if I want to use Sidekiq legally.

This is confusing:
https://choosealicense.com/licenses/

:/
