### ISSUE TITLE
Migrating from sidekiq-limit_fetch to enterprise rate limiting - best approach

### ISSUE THREAD

**Issue by olegantonyan** [mperham/sidekiq#5118]
We want to migrate from this OSS gem https://github.com/brainopia/sidekiq-limit_fetch to enterprise rate limiting. But it works differently, so I'd like to double-check everything.

sidekiq-limit_fetch basically limits the number of concurrent jobs per queue. This is very convenient b/c we don't have to think about limiting specific jobs - it all happens on queue level. We have some critical jobs - they must run no matter what, and some low-priority/heavy jobs - they can wait in queue for a few hours and that's fine. With sidekiq-limit_fetch it's possible by limiting max number of jobs in all queues to be less than number of threads and also limiting number of jobs in low priority queues.

Enterprise Rate Limiting works differently. From my understanding, we can use "concurrent" lock and wrap all heavy jobs in it. But if there's traffic spike and we get 1000 of heavy jobs in the queue we still want them to be executed in small chunks, like 5 concurrent and no more. With rate limiting it's possible to create concurrent lock for 5. B/c we don't want to block all the threads (and quickly run out of threads), `wait_timeout` should be 0. This way any exceeding jobs will be executed and immediately fail with `OverLimit`, then re-tried and so on. This will create a lot of extra traffic between Redis and Sidekiq.

B/c those heavy jobs are potentially long running and unpredictable in nature we cannot really throttle them in application code, but we need a way to slow down their execution before running out of threads.

What is the best approach for solving this problem? Is my understanding of rate limiting correct? If so, maybe extra traffic due to retries is not an issue?

**Comment by mperham** [comment]
Sidekiq does not provide throttling. As you note and the docs point out, rate limiting is not throttling and it only approximates what a throttle does. Unfortunately the complexities of implementing reliability and throttling for Sidekiq mean that those two features are essentially mutually exclusive, both are extremely complex interactions with Redis when fetching a job. I've chosen to implement reliability.

If you want throttling, the easiest way is to dedicate a Sidekiq process to the heavy queue and autoscale it based on your app's load signals.

Faktory does [implement throttling](https://github.com/contribsys/faktory/wiki/Ent-Throttling) because its different architecture makes it easier to implement.

**Comment by olegantonyan** [comment]
Got it, thanks for the quick response.
We don't want autoscale b/c it doesn't matter how long those jobs will take. We want to make sure that critical jobs won't be blocked and the rest can sit in queue for hours.
So to understand the tradeoffs, if rate limiting only approximates throttling and we still want to go this route - how bad it could be? Like, extra traffic/load on redis, constant retries and re-schedules, etc

**Comment by mperham** [comment]
That's really hard to say, there's too many variables to speculate. You can purchase a monthly license for Enterprise, try it out and see how it handles your app's load. If it doesn't work well, with more data we can tune it or you can revert.
