### ISSUE TITLE
Sidekiq Batches stuck in pending state

### ISSUE THREAD

**Issue by Blokh** [mperham/sidekiq#5143]
Ruby version:
2.5.5
Rails version:
5.1.6
Sidekiq / Pro / Enterprise version(s):
sidekiq-pro (5.0.0)

Greetings,
For some reason, we've been encountering an issue of disappearing/stuck batch jobs.

Those jobs do not finish. does not enqueue and cannot be found in either Queue, Busy or Retryset.

they are stuck in a pending state in the batch until for some unknown reason they get "start" working again.
this time is random. sometimes at 3 am sometimes at 1 pm.

Does anyone else encounter this issue? was it resolved in the more recent sidekiq versions?

Thanks in advance, 
Daniel

![image](https://user-images.githubusercontent.com/35891501/150973845-cbda4655-2c8c-4220-ae4d-3c9175388109.png)

**Comment by Blokh** [comment]
One more question.
What are the possible reason for the batch, on success not to be called?

Currently, I've got a batch with all of his jobs finished successfully.
and the batch's on_success callback is not being received. even though the queue is empty.

What might be the cause of it?

**Comment by mperham** [comment]
If you have issues, it's always a good idea to update Sidekiq Pro. There have been numerous releases since 5.0.0. `bundle up sidekiq-pro`

Stuck batches are probably the #1 issue in Sidekiq.

* The cause is always the same: deployment kills the process, which leads to lost jobs.
* The workaround: enable super_fetch and restart the process to rescue any orphaned jobs.
* The solution: rework your deployment process so Sidekiq can shut down cleanly and not lose jobs in the first place.

https://github.com/mperham/sidekiq/wiki/Deployment#overview
