### ISSUE TITLE
Are there plans to support security fixes for older versions?

### ISSUE THREAD

**Issue by MaSven** [mperham/sidekiq#5151]
Just asking as I don't see any information about supported versions. Or what the general release lifecycle is. 

Is only the latest major version supported? If so, is this also true for security patches?

A wiki entry for which versions are supported would be great.

**Comment by mperham** [comment]
I don't have a firm policy. Generally I support the current major and past major versions. Once I release 7.x this year, 5.x will become EOL. Sidekiq 5.2.9 was released in June 2020, 5.0.0 was released April 2017.

If an issue is deemed severe, I will backport it to the previous major version. I don't classify the recent `days` issue as severe because it requires access to the Web UI, which everyone knows to run behind a login wall. If a hacker can get past your login wall, they can do things like clear queues and other far more destructive actions. So `days` is low priority to me.

If someone wants to send me backport PRs for 5.x, I'd be happy to merge it.

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/wiki/Commercial-Support#version-policy
