### ISSUE TITLE
Delay job push within DB transaction

### ISSUE THREAD

**Issue by mperham** [mperham/sidekiq#5239]
Pushing jobs to Redis before the DB transaction has been a thorn in our side since Day One. I'd like to solve this if possible for Sidekiq 7.0. The simplest solution I can see is:

0. Prepend an AR transaction-aware module to override `Sidekiq::Client#raw_push`.
2. Collect the payloads created during a transaction into a thread-local array.
3. Use an after_commit callback which will be run by Rails' Executor to actually push the payloads.

**Comment by ni3t** [comment]
What about jobs that would need to be queued even if the transaction is rolled back?

**Comment by mperham** [comment]
@ni3t I've never heard of such a thing.

**Comment by ianhall** [comment]
> @ni3t I've never heard of such a thing.

I have - when the transaction involves an update to another external resource (like a SaaS or similar), and a compensating action must be enqueued if the transaction fails.

Under those circumstances, it can be useful to push a job to Sidekiq that will run even if the transaction fails.

**Comment by ni3t** [comment]
Sure, sorry I could have been more descriptive in my initial comment. 

We have several operations we perform that are designed to be composed *and* used individually. Because AR transactions can be nested, each of the composable operations is wrapped in an AR transaction on its own, and when composed, the outer composer will wrap them *all* in a separate, _outer_ AR transaction in order to avoid partial completion issues. 

A simplified code example might look like this:

```rb
class CreateOrder
	def self.call(params:)
		ActiveRecord::Base.transaction do
			order = Order.create(params)
			charge_result = ChargeCustomer.call(amount: params[:amount])
			order.transactions << charge_result
			# maybe a dozen other steps, each one of which could fail and roll back the order creation
			
			OrderGeocoder.perform_async(order: order)
		end
 	end
end

class ChargeCustomer
	def self.call(amount:)
		ActiveRecord::Base.transaction do
			transaction = Transaction.create(amount: amount)
			stripe_charge = StripeApi.create_charge(amount: amount)
			unless stripe_charge.success?
				ChargeFailureNotifier.perform_async(stripe_charge_id: stripe_charge.id)
				raise ActiveRecord::Rollback
			end
			transaction.update(stripe_charge_id: stripe_charge.id)
			transaction
		end
	end
end
```

In the example above, we would want the ChargeFailureNotifier to *always* perform, even if the transaction is rolled back, whether the failure rolls it back, or a later step rolls it back. However, we would need the OrderGeocoder to *not* perform if the transaction is rolled back.

**Comment by mperham** [comment]
Does Rails support something like an after_rollback callback which you could use in your code?

**Comment by Envek** [comment]
Yes, ActiveRecord supports `after_commit`, `before_commit` (since Rails 5.0), and `after_rollback` callbacks.

You can either cherry-pick implementation of [after_commit_everywhere](https://github.com/Envek/after_commit_everywhere) gem (which implements all three callbacks outside of models by using corresponding callbacks on virtual ActiveRecord objects) or use it as an optional dependency (like how aasm does, see https://github.com/aasm/aasm/pull/668 for details).

**Comment by ni3t** [comment]
I have strong feelings about avoiding AR callbacks wherever possible, but I won't bikeshed on the topic, other than to say it is a preferable experience to me to explicitly know when callbacks are being run.

Related to that, being able to explicitly control when a job is synced with the AR transaction would be a preferable DX to me. Others could disagree though.

**Comment by Envek** [comment]
> when the transaction involves an update to another external resource (like a SaaS or similar),

I believe that it is an antipattern to make e.g. web requests during open database transactions. There are a lot of good reasons: problems with database performance due to long transactions (long holding locks and/or bloat), inconsistency problems (what if something would fail after a call to SaaS but before the COMMIT?). And this is why [isolator](https://github.com/palkan/isolator) gem was created to detect and avoid such things in tests.

>  and a compensating action must be enqueued if the transaction fails.

You just described [Sagas pattern](https://microservices.io/patterns/data/saga.html). IMO, it is important to separate application-level transactions and database-level transactions. And Sagas (with compensating actions) are all about acting outside of database transactions.

I think, that the best way to avoid problems with enqueuing Sidekiq jobs within transactions is just never enqueue them from your application code. Instead, use [Transactional outbox pattern](https://microservices.io/patterns/data/transactional-outbox.html) — write event to the database and let some handler (which can be Sidekiq job) to pick it up after transaction commit, when it becomes visible.

**Comment by ianhall** [comment]
@Envek I completely agree - in an ideal world, such things would never exist. Unfortunately, they do, especially in more mature code bases. 

Allowing some control over this great new Sidekiq feature / behavior would make it even more awesome. Defaulting to current behavior may also be helpful.

**Comment by Envek** [comment]
And that's why [isolator](https://github.com/palkan/isolator) and [after_commit_everywhere](https://github.com/Envek/after_commit_everywhere) gems has been created as they combination allows to quickly “fix” these “non-database side effects during a database transaction” problems in mature code bases (given decent test coverage).

And it would be awesome if Sidekiq had ActiveRecord integration with automatic after_commit behavior as it would allow to “fix” mature codebases in even more simple and quick way.  

This solution is not ideal though as it is still possible to lost job enqueues e.g. if process or server fails right after transaction was committed and before after_commit callback is run (or in case if one of these callbacks raises an exception). But I believe that this is an orders of magnitude less critical issue. AFAIK the only way to fix it altogether is the before mentioned [Transactional outbox](https://microservices.io/patterns/data/transactional-outbox.html) pattern.

**Comment by adamniedzielski** [comment]
Awesome idea 👏 👏 👏 

I've used https://github.com/Envek/after_commit_everywhere in production for a few years and only had positive experience with it. Thank you @Envek 💛 Sidekiq can just use it, there's no need to reinvent the wheel.

@mperham When it comes to the implementation:
1. I'm not sure if "override Sidekiq::Client#raw_push" is the best idea
2. `Sidekiq::Client` is de-factor "Redis Client". I'd not add database-related logic there.
3. Do you remember when I wanted to introduce a configurable client implementation between `Worker` and `Client` - https://github.com/mperham/sidekiq/pull/5182#discussion_r805027580 ?
4. We could introduce "transaction-aware client" which wraps `Client` with extra logic.
5. After that we either document how to configure it, or configure it automatically after detecting Active Record.

What do you think?

**Comment by kirs** [comment]
I think this might be as well an opportunity to offer an API that would let developers do the right thing, and avoid the mistake of `raw_push` inside a transaction. In other words, less Ruby magic (like collecting payloads into thread-local array) and more explicit API methods. This also fits into the "transaction-aware client" idea that Adam mentioned above.

`raw_push` as it is a dangerous API method when used within ActiveRecord transaction because it's ambiguous. We can solve that by making developers declare their intensions when they enqueue a job: whether they'd like to enqueue it now or only after the transaction commit.

The plan might be something like this:

1) Require that developers always specify the behaviour when using `raw_push`, for instance `raw_push(after_commit: true)` or `raw_push(ignore_transaction_safety_and_push_even_on_rollback: true)`
2) Announce that `raw_push` called inside a transaction _without_ the behaviour specified is deprecated

I'm not native in English and I believe there's better naming possible, but this should illustrate the idea.

**Comment by mperham** [comment]
Sidekiq has always been database-unaware. I'm not sure anymore if it's a good idea to integrate database awareness.

1. There's a large number of existing apps that do nothing and expect that default behavior today.
2. There's a large number of existing apps which integrate 3rd party gems which provide transaction integrate today, as linked above.
3. Adding transaction support meaning risking backwards compatibility with these gems and forcing some number of apps to migrate.
4. Adding transaction support means adding a large amount of cognitive complexity and complex integrate testing.

Is this just matter of missing documentation? Should we provide a wiki page "DBs and Transactions" which explains the default Sidekiq behavior and the functionality of different gems above, allowing people to opt-in if they want to take on the additional complexity?

**Comment by adamniedzielski** [comment]
> Sidekiq has always been database-unaware.

👀 https://github.com/mperham/sidekiq/blob/b83c8e3ae3963cd309a3293b336ffb27a62ec085/lib/sidekiq/extensions/active_record.rb

This is gone on `7-0` now (and that's good 👍), but you hopefully get my point 😆 

What if this was implemented in a similar way to https://github.com/mperham/sidekiq/blob/b83c8e3ae3963cd309a3293b336ffb27a62ec085/lib/sidekiq/rails.rb#L34? So an optional initializer when Active Record is loaded?

A more conservative approach would be to enable easier extension (dependency injection between `Worker` and `Client` 😉 😉 😉 ), allow the open source community to create a gem that provides pushing jobs after transaction commits, wait until it's stable, and document in an official wiki page.

**Comment by mperham** [comment]
@adamniedzielski That's not really what I mean by database-aware, that's injecting `delay` support into ActiveRecord::Base. We're talking about RDBMS commit and rollback.

I'm game for anything if people can provide a PR to discuss. This functionality isn't something I want to tackle because I wouldn't be a user of it but I do think it's reasonable to prototype something between S::Job (nee S::Worker) and S::Client.

**Comment by adamniedzielski** [comment]
There you go #5248. This is what I meant. I haven't run this code, but it should give you an idea about the direction.

**Comment by adamniedzielski** [comment]
> I think, that the best way to avoid problems with enqueuing Sidekiq jobs within transactions is just never enqueue them from your application code. Instead, use [Transactional outbox pattern](https://microservices.io/patterns/data/transactional-outbox.html) — write event to the database and let some handler (which can be Sidekiq job) to pick it up after transaction commit, when it becomes visible.

If only somebody created a gem that implements that for Sidekiq... 🤔 https://github.com/adamniedzielski/sidekiq-staged_push. You're welcome.

**Comment by letiesperon** [comment]
If you're just starting out and trying to make sense of all this, you might find an article I previously wrote on this topic helpful for clearing things up and understanding how to use it:
https://medium.com/@esperonleticia/transactional-push-the-sidekiq-feature-you-need-to-enable-right-now-d3fc1787f6ce
