### ISSUE TITLE
Busy Processes not visible

### ISSUE THREAD

**Issue by aniljaiswal** [mperham/sidekiq#5262]
Ruby version: Jruby-9.3.3.0
Rails version: 6.0.2.1
Sidekiq / Pro / Enterprise version(s): 6.4.1

<img width="1276" alt="Screenshot 2022-03-25 at 5 40 11 PM" src="https://user-images.githubusercontent.com/43805107/160118435-09ec37df-e14e-4d88-bc29-b63741e4d3fa.png">

I upgraded to version 6.4.1 yesterday and now jobs that are being processed at the moment are not visible as displayed in the screenshot. I can see the enqueued jobs number going down and workers showing busy.

Let me know what other information might be needed to debug this. I'll add it here.

**Comment by mperham** [comment]
Do you still have a problem? Web UI issues after upgrade usually are due to the Web UI's Cache-Control policy of one day for all assets. After 24 hours your browser will pull the latest version which will work.

**Comment by aniljaiswal** [comment]
Yep, the issue still persists. The running jobs are still not visible. I have tried hard-refreshing the page multiple times. Even used the UI in incognito.

**Comment by mperham** [comment]
I can't imagine what the problem is. Maybe you have the Web UI pointed at a different Redis from the Sidekiq processes.

**Comment by itobler** [comment]
Ruby: 2.7.3p183
Rails: 5.0.7 -> 5.1.7
Sidekiq: 5.2.10 (Pro 4.0.5, Ent 1.8.1)

It's interesting, because we just started having this same issue in our project recently. We are trying to upgrade our Rails version but leaving Sidekiq/Redis and all its configuration alone.

This is from a dev environment where we are testing it out. I get the same issue on a staging environment based on the same branch that is completely hosted in the cloud (AWS). If I switch to my main branch (Rails 5.0.7) and restart everything on my dev environment, I can see the jobs being listed just fine.
![Screenshot from 2022-03-30 15-09-29](https://user-images.githubusercontent.com/12463779/160944032-518150fe-76bf-40c1-8712-f1a50b259915.png)

**Comment by mperham** [comment]
Please verify you are using Redis gem version v4.5.x.

**Comment by mperham** [comment]
It works for everybody else and I just verified it works locally for me with v4.5.1. I suspect you have a monkeypatch or something else mucking about with the Redis client API?

```
Loading development environment (Rails 5.2.7)
irb(main):005:0> Sidekiq.redis{|c| c.exists?("Mikes-MacBook-Pro.local:84646:4844ac15f098")}
=> true
irb(main):007:0> Sidekiq.redis{|c| c.exists("Mikes-MacBook-Pro.local:84646:4844ac15f098")}
=> 1
```

**Comment by itobler** [comment]
Sure! Just confirmed, redis-rb version 4.5.1.
Using Sidekiq 5.2.8 - shows jobs
Using Sidekiq 5.2.10 - no jobs

Thanks! I will look around for a monkey-patch

**Comment by mperham** [comment]
Ok. Redis-namespace is not recommended and support will likely be dropped
in Sidekiq 7.0.

**Comment by mperham** [comment]
I’ve no clue. I’ve never seen this problem that I can recall.

**Comment by aniljaiswal** [comment]
Yes, I still can't see any jobs in progress.
