### ISSUE TITLE
Clarification of queue weight "overhead"?

### ISSUE THREAD

**Issue by NielsKSchjoedt** [mperham/sidekiq#5619]
Let's say I have a sidekiq config like this:

```yaml
:queues:
  - [critical_jobs, 10000]
  - [other, 1]
```

Obviously jobs from `critical_jobs` are likely 10.000x more likely to be consumed first - however - I'm concerned if that also means a HUGE overhead (e.g. roundtrips to Redis), because the documentation says:

>  A queue with a weight of 2 will be checked twice as often as a queue with a weight of 1:

It's this word "checked" I'm concerned about - does it mean that it will likely "poll" from redis 10.000 times before picking up a job from `other` queue even if e.g. there is nothing in `critical_jobs`? So all in all, what kind of overhead does it produce to use "large" 1000x priority weights in sidekiq conf?

**Comment by mperham** [comment]
"checked" really should say "checked first".

Sidekiq will create an array of `total_weight` Strings to randomly shuffle the queue checks. For every fetch:

1. shuffle that array of 10,001 items.
2. uniq it to two items.
3. check those two entries in order.

You can see that large weights cause unnecessary overhead in shuffling and uniqing. That's why I don't recommend a weight more than 20 or so. Diminishing returns, if you have multiple threads fetching your critical queue will still be checked frequently and the fetch overhead will be much lower.
