### ISSUE TITLE
Suggestion: Sidekiq 7 with unsupported Redis version should fail harder!

### ISSUE THREAD

**Issue by ConfusedVorlon** [mperham/sidekiq#5631]
Ruby version: 3.0.2
Rails version: 7.0.4
Sidekiq / Pro / Enterprise version(s): 7

When running with an unsupported version of Redis (6.0.2), Rails queues up jobs which appear in the Sidekiq web console, however the jobs don't run.
There is no obvious error other than the silent failure.

It would be better if there was an error thrown when the job was queued to let people know that they're using a broken setup.

**Comment by mperham** [comment]
Sidekiq 7 will fail loudly if you are using Redis <6. The issue is that the Sidekiq client will work with Redis 6.0-6.2 but the Sidekiq server will fail if <6.2.

I'm ok with this. I'm sorry you happened to come across this but Redis 6.0 hasn't been current for 2.5 years now; I don't think it's worth the trouble to check for this version window.

**Comment by jarthod** [comment]
I just noticed this and wanted to add that `redis 6.0.16` is the version in [Ubuntu Server 22.04 LTS](https://packages.ubuntu.com/search?keywords=redis-server&searchon=names&suite=all&section=all), it was released [1.5 year ago](https://raw.githubusercontent.com/antirez/redis/6.0/00-RELEASENOTES) and will continue to be there for _at least_ 1.5 more years (until 24.04 LTS is released) on many servers until people notice it and decide to wait or install a custom redis version.

I also feel like Sidekiq 7 should fail harder in this case as it could be pretty dangerous and make people waste some time (I caught this in staging fortunately). No need to reopen as you already made this decision but I just wanted to add my 2 cents :coin:

**Comment by mperham** [comment]
@jarthod Yeah, that's unfortunate. Sidekiq 6.5 will be around for years; Sidekiq 7 is meant to be cutting edge, with all that implies. Redis 6.2 had a larger number of command updates and deprecations and I really wanted to be able to rely on those changes otherwise I would have stuck with 6.0. 🤷🏻‍♂️

**Comment by jarthod** [comment]
Yes that is totally understandable, I am not suggesting more compatibility.
I'll stick with Sidekiq 6.5 on my end until Ubuntu 24.04 and try sidekiq 7 upgrade then which is fine.

All I'm saying (like @ConfusedVorlon) is that I believe Sidekiq 7 client should fail more explicitely when used with redis < 6.2, in order to avoid bad surprises (basically applying the "Principle of least astonishment" if we wanted to sound fancy). We are surely not the only/last ones to whom this will happen.

**Comment by mperham** [comment]
If you are using the 7 client, it stands to reason you are using the 7 server also. There is no clean, clear "boot" point for the client to validate the Redis version. That's why only the server complains.

**Comment by jarthod** [comment]
Fair enough :+1:
