### ISSUE TITLE
Many ConnectionPool::TimeoutErrors on Sidekiq 7.0.2

### ISSUE THREAD

**Issue by BobbyMcWho** [mperham/sidekiq#5684]
Ruby version: 2.7
Rails version: 7.0.4
Sidekiq / Pro / **Enterprise** version(s): 7.0.2

We began getting a ton of `ConnectionPool::TimeoutError: Waited 5 sec, 0/10 available` errors in production after upgrading to Sidekiq 7.0.2 from 6.5.6. 

Looking at code from [6.5.6](https://github.com/mperham/sidekiq/blob/e7d154eeb5e237a6e6e591a3bfca0a8f7bce32f6/lib/sidekiq/redis_connection.rb#L22) and [7.0.2](https://github.com/mperham/sidekiq/blob/acf143f6d0f60db8a8c951dd799b788865436789/lib/sidekiq/capsule.rb#L77), it appears that the default pool size has been reduced by 5, but there doesn't appear to be a way to increase that pool size for the capsule.  Was this reduction intended? If so, would you be open to a capsule config option to increase it?

**Comment by mperham** [comment]
Each capsule always gets the same number of Redis connections as the capsule concurrency. If you use `-c 10`, the default capsule will get a pool size of 10.

Sidekiq 7 reduced the default size of the default capsule from 10 to 5 to prevent CPU saturation on low-end dynos and VMs.

**Comment by geoffharcourt** [comment]
We are also seeing this issue since we upgraded. We're consistently way under the allowed connection count when it happens, and our Redis instance doesn't appear to be overtaxed (low CPU use, etc.).

The issue seems to happen only when there's a large number of jobs being enqueued, but we can't tell if it's the enqueueing or the presence of a large number of jobs or lots of jobs happening at once that's leading to this.

Here's our Redis configuration:

```ruby
shared_redis_config = {
  db: ENV["REDIS_DATABASE_NUMBER"].to_i,
  # this is 2 for us, but the timeout we see is 5s in the exception
  network_timeout: REDIS_NETWORK_TIMEOUT_SECONDS, 
  ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE },
  url: ENV["REDIS_URL"],
}
```

We saw this with Sidekiq 7.0.1 and 7.0.2. We're running Ruby 3.1.3, Rails 7.0.4, and using Elasticache Redis on an m6g.xlarge (12 GB).

**Comment by mperham** [comment]
Are you spinning up any Threads on your own which are using Redis?

**Comment by geoffharcourt** [comment]
@mperham the web processes are using Redis for enqueueing. When we've seen this happen (most often late at night), we've only been using 150-170 Redis connections (from AWS dashboard), and we're often at over 300 during the day.

**Comment by BobbyMcWho** [comment]
> Each capsule always gets the same number of Redis connections as the capsule concurrency.

Indeed, but the behavior on 6.5 connection pool was concurrency + 5. I'm going to keep digging to see if there is anything else potentially causing this, because we had to roll back unfortunately

**Comment by mperham** [comment]
That +5 "slack" was necessary because Sidekiq has internal threads which need a Redis connection. In 7, Sidekiq has a global pool of 5 connections for miscellaneous use, separate from the capsule pools. The capsule pools are devoted to running jobs.

Outside of jobs executing within capsules, any needed redis connections come from this global pool. The pool is at `Sidekiq.default_configuration.redis_pool`.

Are y'all seeing these errors within a Sidekiq process, or within another client process like puma?

**Comment by geoffharcourt** [comment]
As far as we can tell from exception data, these exceptions have only happened to us within a Sidekiq process, we haven't yet seen it occur in Puma. So even when we've had a burst of thousands of exceptions, there hasn't been any effect on web traffic or the ability of web processes to continue enqueueing jobs.

**Comment by geoffharcourt** [comment]
We've noticed the same thing @BobbyMcWho mentioned, the connection pool described is always `5s, 0/10` even though our concurrency is 15 and our timeout is 2s.

**Comment by mperham** [comment]
Ah, that's the Statsd connection pool which I hardcoded to 5, thinking that would be enough connections to share amongst N Threads. Sigh.

**Comment by BobbyMcWho** [comment]
We're also configured to use dogstatsd w/ datadog

**Comment by mperham** [comment]
Oh, poop. 💩 So an executing job holds a Statsd connection in lib/sidekiq/middleware/server/statsd.rb line 41. If you have more than 10 long-running jobs executing at the same time, it can raise that error.

The fix is to not use that `b.time` call but release the connection back to the pool while the job is executing and record the time later. I'll get this fixed.

**Comment by BobbyMcWho** [comment]
Thanks @mperham!

**Comment by mperham** [comment]
Pro 7.0.3 is now available with this fix.
