### ISSUE TITLE
Is Sidekiq suitable for executing jobs as alternative to infinite loop?

### ISSUE THREAD

**Issue by romiras** [mperham/sidekiq#5703]
Sidekiq Pro version: 5.5.x

I have a handler for processing messages in queue using Redis.

```ruby
conn = Redis.new(...)
...

loop do
  channel, message = conn.blpop(key)
  handler(channel, message)
end
```

Here we use [BLPOP](https://redis.io/commands/blpop/) command and it can take very long time potentially. We can run `handler` and schedule some job to Sidekiq, so no problem with it.

My question is: whether it possible to use some middleware or something else to let Sidekiq manage this loop as well by invoking callback so I can get rid of loop and don't have dedicated process for that loop?

**Comment by mperham** [comment]
Sidekiq is essentially a blpop loop like that. It just requires that every message be a job payload hash. I can think of several ideas:

1. You can start a separate thread inside Sidekiq which performs that loop.
2. You can schedule a job once per minute using cron to drain the queue.
3. You can dump a bunch of messages into the queue and then enqueue a job for a Sidekiq worker thread to drain the queue.

But ultimately Sidekiq cannot directly handle the queue processing for you because your message is not a job payload.
